"""
Django settings for apiSystem project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(str(BASE_DIR.parent))

# 从环境变量读取配置（生产环境建议使用 python-dotenv）
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR.parent / '.env')
except ImportError:
    pass  # python-dotenv 未安装时跳过

# ============================================================
# 统一配置管理系统集成
# ============================================================
# 延迟初始化统一配置管理器（在基本配置设置后）
CONFIG_MANAGER_AVAILABLE = False
config_manager = None
env_config = None

def get_config(key, default=None):
    """回退函数：从环境变量获取配置"""
    return os.environ.get(key, default)

def _initialize_config_manager():
    """延迟初始化配置管理器"""
    global CONFIG_MANAGER_AVAILABLE, config_manager, env_config, get_config
    
    try:
        from apps.core.config import get_config_manager, get_config as _get_config
        from apps.core.config.providers.django import DjangoProvider
        from apps.core.config.environment import EnvironmentConfig
        
        # 获取配置管理器实例
        config_manager = get_config_manager()
        
        # 加载配置（不包含 Django 提供者，避免循环依赖）
        config_manager.load()
        
        # 初始化环境配置
        env_config = EnvironmentConfig()
        
        # 启用自动热重载（开发环境）
        if os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes'):
            config_manager.enable_auto_reload()
        
        # 更新全局函数
        get_config = _get_config
        
        # 配置管理器可用标志
        CONFIG_MANAGER_AVAILABLE = True
        
        return True
        
    except Exception as e:
        # 如果配置管理器初始化失败，保持回退方式
        print(f"配置管理器初始化失败，使用传统配置方式: {e}")
        return False


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ============================================================
# 安全配置 - Requirements: 6.6, 12.2, 12.5
# ============================================================
# 
# 安全默认值策略：
# 1. 生产环境（DEBUG=False）强制要求设置 SECRET_KEY
# 2. 敏感配置不会在日志中输出
# 3. CORS 白名单默认只允许本地访问
#

# 检测是否为生产环境
_is_production = os.environ.get('DJANGO_DEBUG', 'True').lower() not in ('true', '1', 'yes')

# 安全的默认密钥（仅用于开发环境）
_DEV_SECRET_KEY = 'django-insecure-dev-only-do-not-use-in-production'

# SECURITY WARNING: keep the secret key used in production secret!
if CONFIG_MANAGER_AVAILABLE:
    SECRET_KEY = get_config('django.secret_key', _DEV_SECRET_KEY)
    DEBUG = get_config('django.debug', True)
    ALLOWED_HOSTS = get_config('django.allowed_hosts', ['*'])
else:
    _env_secret_key = os.environ.get('DJANGO_SECRET_KEY', '')
    
    # 生产环境安全检查
    if _is_production:
        # 生产环境必须设置 SECRET_KEY
        if not _env_secret_key or _env_secret_key in ('change-me-in-production', 'change-me-in-production-use-generated-key', _DEV_SECRET_KEY):
            import warnings
            warnings.warn(
                "生产环境必须设置安全的 DJANGO_SECRET_KEY！"
                "请使用以下命令生成: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
            )
            # 在生产环境中，如果没有设置密钥，使用一个随机生成的临时密钥
            # 注意：这会导致每次重启后 session 失效
            from django.core.management.utils import get_random_secret_key
            SECRET_KEY = get_random_secret_key()
        else:
            SECRET_KEY = _env_secret_key
    else:
        # 开发环境使用默认密钥
        SECRET_KEY = _env_secret_key if _env_secret_key else _DEV_SECRET_KEY
    
    DEBUG = not _is_production
    
    # ALLOWED_HOSTS 安全默认值
    _allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
    if _allowed_hosts:
        ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]
    elif _is_production:
        # 生产环境默认只允许 localhost
        ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    else:
        # 开发环境允许所有
        ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 'unfold',  # django-unfold 主题（已禁用，与自定义模板冲突）
    # 'unfold.contrib.filters',
    # 'unfold.contrib.forms',
    'apps.organization',  # 必须在 admin 之前，以覆盖登录模板
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nested_admin',
    'corsheaders',
    'ninja_jwt',
    # === Django Admin 侧边栏顺序（按以下顺序显示）===
    'apps.client',       # 1. Client CRM（当事人管理）
    'apps.contracts',    # 2. Contracts（合同管理）
    'apps.cases',        # 3. CASES（案件管理）
    'apps.automation',   # 4. 自动化工具
    'apps.core',         # 5. 核心系统
    'django_q',          # 6. DJANGO Q
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'apps.organization.middleware.ApiTrailingSlashMiddleware',
    'django.middleware.common.CommonMiddleware',
    'ninja.compatibility.files.fix_request_files_middleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.organization.middleware.OrgAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apiSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 全局模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apiSystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ============================================================
# Docker 环境变量支持
# ============================================================
# DATABASE_PATH: SQLite 数据库文件路径（Docker 部署时使用）
# 示例: DATABASE_PATH=/app/data/db.sqlite3
DATABASE_PATH = os.environ.get('DATABASE_PATH', None)

if CONFIG_MANAGER_AVAILABLE:
    # 优先使用 DATABASE_PATH 环境变量（Docker 部署）
    db_name = DATABASE_PATH if DATABASE_PATH else get_config('database.name', BASE_DIR / 'db.sqlite3')
    DATABASES = {
        'default': {
            'ENGINE': get_config('database.engine', 'django.db.backends.sqlite3'),
            'NAME': db_name,
            'USER': get_config('database.user', ''),
            'PASSWORD': get_config('database.password', ''),
            'HOST': get_config('database.host', ''),
            'PORT': get_config('database.port', ''),
            'CONN_MAX_AGE': get_config('database.conn_max_age', 600),
            'OPTIONS': {
                'timeout': get_config('database.timeout', 20),
            }
        }
    }
else:
    # 优先使用 DATABASE_PATH 环境变量（Docker 部署）
    db_name = DATABASE_PATH if DATABASE_PATH else BASE_DIR / 'db.sqlite3'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_name,
            'CONN_MAX_AGE': 600,  # 连接复用 10 分钟，减少连接开销
            'OPTIONS': {
                'timeout': 20,  # 数据库锁超时时间（秒）
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# 静态文件收集目录（Docker 部署需要）
STATIC_ROOT = os.environ.get('STATIC_ROOT', BASE_DIR / 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'organization.Lawyer'

# ============================================================
# CORS 配置 - Requirements: 12.5
# ============================================================
# CORS (Cross-Origin Resource Sharing) 允许前端应用从不同域名访问 API
# 
# 安全策略：
# - 开发环境：允许所有来源（方便前端开发和测试）
# - 生产环境：默认只允许本地访问，通过环境变量配置白名单
#
# 环境变量配置示例：
#   CORS_ALLOWED_ORIGINS=https://example.com,https://app.example.com
#   CSRF_TRUSTED_ORIGINS=https://example.com,https://app.example.com
#
# Requirements: 5.1, 5.2, 5.3 (验证码识别 API), 12.5 (CORS 白名单)

# 安全的 CORS 默认白名单（仅本地访问）
_SAFE_CORS_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:3000',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

if CONFIG_MANAGER_AVAILABLE:
    if get_config('django.debug', True):
        CORS_ALLOW_ALL_ORIGINS = get_config('cors.allow_all_origins', True)
    else:
        CORS_ALLOWED_ORIGINS = get_config('cors.allowed_origins', _SAFE_CORS_ORIGINS)
    
    CORS_ALLOW_CREDENTIALS = get_config('cors.allow_credentials', True)
    CORS_ALLOW_HEADERS = get_config('cors.allow_headers', [
        'accept', 'accept-encoding', 'authorization', 'content-type',
        'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with'
    ])
    
    if get_config('django.debug', True):
        CSRF_TRUSTED_ORIGINS = get_config('csrf.trusted_origins_dev', _SAFE_CORS_ORIGINS)
    else:
        CSRF_TRUSTED_ORIGINS = get_config('csrf.trusted_origins', _SAFE_CORS_ORIGINS)
else:
    if DEBUG:
        CORS_ALLOW_ALL_ORIGINS = True
    else:
        # 生产环境从环境变量读取允许的来源，默认使用安全白名单
        cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
        if cors_origins:
            CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins.split(',') if origin.strip()]
        else:
            # 安全默认值：只允许本地访问
            CORS_ALLOWED_ORIGINS = _SAFE_CORS_ORIGINS

    # CORS 配置选项
    CORS_ALLOW_CREDENTIALS = True  # 允许携带认证信息（cookies, authorization headers）
    CORS_ALLOW_HEADERS = [
        'accept',
        'accept-encoding',
        'authorization',
        'content-type',
        'dnt',
        'origin',
        'user-agent',
        'x-csrftoken',
        'x-requested-with',
    ]

    # CSRF 信任的来源（用于表单提交）
    if DEBUG:
        CSRF_TRUSTED_ORIGINS = _SAFE_CORS_ORIGINS
    else:
        csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
        if csrf_origins:
            CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins.split(',') if origin.strip()]
        else:
            # 安全默认值：只允许本地访问
            CSRF_TRUSTED_ORIGINS = _SAFE_CORS_ORIGINS

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# django_q2 配置：确保 retry 大于 timeout，避免任务在完成前被重试
if CONFIG_MANAGER_AVAILABLE:
    Q_CLUSTER = {
        'name': get_config('q_cluster.name', 'default'),
        'workers': get_config('q_cluster.workers', 2),
        'timeout': get_config('q_cluster.timeout', 600),
        'retry': get_config('q_cluster.retry', 1200),
        'queue_limit': get_config('q_cluster.queue_limit', 50),
        'bulk': get_config('q_cluster.bulk', 10),
        'orm': get_config('q_cluster.orm', 'default'),
        'max_attempts': get_config('q_cluster.max_attempts', 1),
        'catch_up': get_config('q_cluster.catch_up', False),
    }
else:
    Q_CLUSTER = {
        'name': 'default',
        'workers': 2,  # 增加到 2 个 worker，提升并发能力
        'timeout': 600,  # 爬虫任务可能需要更长时间（10 分钟）
        'retry': 1200,  # 重试时间设为 timeout 的 2 倍
        'queue_limit': 50,
        'bulk': 10,
        'orm': 'default',
        'max_attempts': 1,  # 任务失败后不自动重试（由我们的重试机制控制）
        'catch_up': False,  # 不执行错过的定时任务
    }

# 调试开关：放开所有访问权限（True 时跳过权限校验）
if CONFIG_MANAGER_AVAILABLE:
    PERM_OPEN_ACCESS = get_config('permissions.open_access', True)
    
    # Moonshot AI 配置（保留兼容性）
    MOONSHOT_BASE_URL = get_config('services.moonshot.base_url', 'https://api.moonshot.cn/v1')
    MOONSHOT_API_KEY = get_config('services.moonshot.api_key', '')
    
    # 文档处理配置
    DOCUMENT_PROCESSING = {
        'DEFAULT_TEXT_LIMIT': get_config('features.document_processing.default_text_limit', 1500),
        'DEFAULT_PREVIEW_PAGE': get_config('features.document_processing.default_preview_page', 1),
        'MAX_TEXT_LIMIT': get_config('features.document_processing.max_text_limit', 10000),
        'MAX_PREVIEW_PAGES': get_config('features.document_processing.max_preview_pages', 5),
    }
    
    # 爬虫加密密钥（生产环境请使用环境变量）
    SCRAPER_ENCRYPTION_KEY = get_config('automation.scraper_encryption_key', None)
else:
    PERM_OPEN_ACCESS = True
    
    # Moonshot AI 配置（保留兼容性）
    MOONSHOT_BASE_URL = os.environ.get('MOONSHOT_BASE_URL', 'https://api.moonshot.cn/v1')
    MOONSHOT_API_KEY = os.environ.get('MOONSHOT_API_KEY', '')
    
    # 文档处理配置
    DOCUMENT_PROCESSING = {
        'DEFAULT_TEXT_LIMIT': 1500,  # 默认文字抽取数量
        'DEFAULT_PREVIEW_PAGE': 1,    # 默认预览页码（PDF）
        'MAX_TEXT_LIMIT': 10000,      # 最大文字抽取限制
        'MAX_PREVIEW_PAGES': 5,       # 最大预览页数限制
    }
    
    # 爬虫加密密钥（生产环境请使用环境变量）
    # 生成密钥: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
    SCRAPER_ENCRYPTION_KEY = os.environ.get('SCRAPER_ENCRYPTION_KEY', None)

# ============================================================
# 日志配置
# ============================================================
from apps.core.logging import get_logging_config
LOGGING = get_logging_config(BASE_DIR.parent, DEBUG)

# ============================================================
# 缓存配置
# ============================================================
from apps.core.cache import get_cache_config
CACHES = get_cache_config()

# ============================================================
# API 配置
# ============================================================
# APP_VERSION: 应用版本号（Docker 部署时显示）
APP_VERSION = os.environ.get('APP_VERSION', '1.0.0')
API_VERSION = "1.0.0"

# 请求限流配置
RATE_LIMIT = {
    "DEFAULT_REQUESTS": 100,  # 默认每分钟请求数
    "DEFAULT_WINDOW": 60,     # 默认时间窗口（秒）
    "AUTH_REQUESTS": 5,       # 认证接口每分钟请求数
    "AUTH_WINDOW": 60,        # 认证接口时间窗口
}

# ============================================================
# Ollama AI 配置
# ============================================================
OLLAMA = {
    "MODEL": os.environ.get("OLLAMA_MODEL", "qwen3:0.6b"),
    "BASE_URL": os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434"),
}

# ============================================================
# 群聊平台配置
# ============================================================

if CONFIG_MANAGER_AVAILABLE:
    # 飞书配置
    FEISHU = {
        "WEBHOOK_URL": get_config("chat_platforms.feishu.webhook_url"),
        "APP_ID": get_config("chat_platforms.feishu.app_id"),
        "APP_SECRET": get_config("chat_platforms.feishu.app_secret"),
        "TIMEOUT": get_config("chat_platforms.feishu.timeout", 30),
    }

    # 钉钉配置
    DINGTALK = {
        "APP_KEY": get_config("chat_platforms.dingtalk.app_key"),
        "APP_SECRET": get_config("chat_platforms.dingtalk.app_secret"),
        "AGENT_ID": get_config("chat_platforms.dingtalk.agent_id"),
        "TIMEOUT": get_config("chat_platforms.dingtalk.timeout", 30),
    }

    # 企业微信配置
    WECHAT_WORK = {
        "CORP_ID": get_config("chat_platforms.wechat_work.corp_id"),
        "AGENT_ID": get_config("chat_platforms.wechat_work.agent_id"),
        "SECRET": get_config("chat_platforms.wechat_work.secret"),
        "TIMEOUT": get_config("chat_platforms.wechat_work.timeout", 30),
    }

    # Telegram 配置
    TELEGRAM = {
        "BOT_TOKEN": get_config("chat_platforms.telegram.bot_token"),
        "TIMEOUT": get_config("chat_platforms.telegram.timeout", 30),
    }

    # Slack 配置
    SLACK = {
        "BOT_TOKEN": get_config("chat_platforms.slack.bot_token"),
        "SIGNING_SECRET": get_config("chat_platforms.slack.signing_secret"),
        "TIMEOUT": get_config("chat_platforms.slack.timeout", 30),
    }

    # 案件群聊管理配置
    CASE_CHAT = {
        "DEFAULT_PLATFORM": get_config("features.case_chat.default_platform", "feishu"),
        "AUTO_CREATE_ON_PUSH": get_config("features.case_chat.auto_create_on_push", True),
        "DEFAULT_OWNER_ID": get_config("features.case_chat.default_owner_id"),
    }
else:
    # 飞书配置
    FEISHU = {
        "WEBHOOK_URL": os.environ.get("FEISHU_WEBHOOK_URL"),
        "APP_ID": os.environ.get("FEISHU_APP_ID"),
        "APP_SECRET": os.environ.get("FEISHU_APP_SECRET"),
        "TIMEOUT": int(os.environ.get("FEISHU_TIMEOUT", 30)),
    }

    # 钉钉配置
    DINGTALK = {
        "APP_KEY": os.environ.get("DINGTALK_APP_KEY"),
        "APP_SECRET": os.environ.get("DINGTALK_APP_SECRET"),
        "AGENT_ID": os.environ.get("DINGTALK_AGENT_ID"),
        "TIMEOUT": int(os.environ.get("DINGTALK_TIMEOUT", 30)),
    }

    # 企业微信配置
    WECHAT_WORK = {
        "CORP_ID": os.environ.get("WECHAT_WORK_CORP_ID"),
        "AGENT_ID": os.environ.get("WECHAT_WORK_AGENT_ID"),
        "SECRET": os.environ.get("WECHAT_WORK_SECRET"),
        "TIMEOUT": int(os.environ.get("WECHAT_WORK_TIMEOUT", 30)),
    }

    # Telegram 配置
    TELEGRAM = {
        "BOT_TOKEN": os.environ.get("TELEGRAM_BOT_TOKEN"),
        "TIMEOUT": int(os.environ.get("TELEGRAM_TIMEOUT", 30)),
    }

    # Slack 配置
    SLACK = {
        "BOT_TOKEN": os.environ.get("SLACK_BOT_TOKEN"),
        "SIGNING_SECRET": os.environ.get("SLACK_SIGNING_SECRET"),
        "TIMEOUT": int(os.environ.get("SLACK_TIMEOUT", 30)),
    }

    # 案件群聊管理配置
    CASE_CHAT = {
        "DEFAULT_PLATFORM": "feishu",  # 默认群聊平台
        "AUTO_CREATE_ON_PUSH": True,   # 推送时自动创建群聊
        "DEFAULT_OWNER_ID": os.environ.get("FEISHU_DEFAULT_OWNER_ID"),  # 默认群主ID
    }

# ============================================================
# 法院短信处理配置
# ============================================================
if CONFIG_MANAGER_AVAILABLE:
    COURT_SMS_PROCESSING = {
        # 飞书配置（兼容旧配置，优先使用 FEISHU 配置）
        "FEISHU_WEBHOOK_URL": get_config("chat_platforms.feishu.webhook_url"),
        "FEISHU_APP_ID": get_config("chat_platforms.feishu.app_id"),
        "FEISHU_APP_SECRET": get_config("chat_platforms.feishu.app_secret"),
        # 重试配置
        "MAX_RETRIES": get_config("features.court_sms.max_retries", 3),
        "RETRY_DELAY": get_config("features.court_sms.retry_delay", 60),
        # 自动恢复配置
        "AUTO_RECOVERY": get_config("features.court_sms.auto_recovery", True),
    }
else:
    COURT_SMS_PROCESSING = {
        # 飞书配置（兼容旧配置，优先使用 FEISHU 配置）
        "FEISHU_WEBHOOK_URL": os.environ.get("FEISHU_WEBHOOK_URL"),
        "FEISHU_APP_ID": os.environ.get("FEISHU_APP_ID"),
        "FEISHU_APP_SECRET": os.environ.get("FEISHU_APP_SECRET"),
        # 重试配置
        "MAX_RETRIES": int(os.environ.get("COURT_SMS_MAX_RETRIES", 3)),
        "RETRY_DELAY": int(os.environ.get("COURT_SMS_RETRY_DELAY", 60)),
        # 自动恢复配置
        "AUTO_RECOVERY": os.environ.get("COURT_SMS_AUTO_RECOVERY", "True").lower() in ("true", "1", "yes"),
    }

# ============================================================
# 向后兼容性支持
# ============================================================

# 尝试初始化配置管理器（在所有基本配置设置完成后）
_initialize_config_manager()

# 提供全局配置管理器访问
if CONFIG_MANAGER_AVAILABLE:
    # 导出配置管理器实例供其他模块使用
    UNIFIED_CONFIG_MANAGER = config_manager
    
    # 提供便捷的配置访问函数
    def get_unified_config(key, default=None):
        """获取统一配置项"""
        return config_manager.get(key, default)
    
    # 配置变更监听器注册函数
    def register_config_listener(listener, key_filter=None, prefix_filter=None):
        """注册配置变更监听器"""
        config_manager.add_listener(listener, key_filter, prefix_filter)
else:
    UNIFIED_CONFIG_MANAGER = None
    
    def get_unified_config(key, default=None):
        """回退函数：从环境变量获取配置"""
        return os.environ.get(key, default)
    
    def register_config_listener(listener, key_filter=None, prefix_filter=None):
        """空实现：配置管理器不可用时"""
        pass
# ============================================================
# Django Admin 界面配置 (django-unfold)
# ============================================================

# 自定义 Django Admin 界面标题和头部信息
ADMIN_SITE_HEADER = "法穿案件管理系统"
ADMIN_SITE_TITLE = "免费开源，尽情使用"
ADMIN_INDEX_TITLE = "欢迎来到法穿案件管理系统"

# django-unfold 配置
# UNFOLD = {
#     "SITE_TITLE": "法穿案件管理系统",
#     "SITE_HEADER": "法穿案件管理系统",
#     "SITE_SUBHEADER": "免费开源，尽情使用",
#     "SITE_SYMBOL": "gavel",  # Material Symbols 图标
#     "SHOW_HISTORY": True,
#     "SHOW_VIEW_ON_SITE": True,
#     "ENVIRONMENT": "apps.core.admin.environment_callback",
#     "COLORS": {
#         "primary": {
#             "50": "250 245 255",
#             "100": "243 232 255",
#             "200": "233 213 255",
#             "300": "216 180 254",
#             "400": "192 132 252",
#             "500": "168 85 247",
#             "600": "147 51 234",
#             "700": "126 34 206",
#             "800": "107 33 168",
#             "900": "88 28 135",
#             "950": "59 7 100",
#         },
#     },
#     "SIDEBAR": {
#         "show_search": True,
#         "show_all_applications": True,
#         # 使用自动生成的导航，不手动指定 navigation
#     },
# }