# Generated by Django 5.2.8 on 2025-12-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="contracts.contract",
                verbose_name="关联合同",
            ),
        ),
        migrations.AddField(
            model_name="caseaccessgrant",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_grants",
                to="cases.case",
                verbose_name="案件",
            ),
        ),
    ]
