# Generated by Django 5.2.8 on 2025-12-24 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0002_initial"),
        ("client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="caseaccessgrant",
            name="grantee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_access_grants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="获授权律师",
            ),
        ),
        migrations.AddField(
            model_name="caseassignment",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="cases.case",
                verbose_name="案件",
            ),
        ),
        migrations.AddField(
            model_name="caseassignment",
            name="lawyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="律师",
            ),
        ),
        migrations.AddField(
            model_name="casechat",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="chats", to="cases.case", verbose_name="案件"
            ),
        ),
        migrations.AddField(
            model_name="caselog",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="case_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
        migrations.AddField(
            model_name="caselog",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="cases.case", verbose_name="案件"
            ),
        ),
        migrations.AddField(
            model_name="caselogattachment",
            name="log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="cases.caselog",
                verbose_name="日志",
            ),
        ),
        migrations.AddField(
            model_name="caselogversion",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="case_log_versions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作者",
            ),
        ),
        migrations.AddField(
            model_name="caselogversion",
            name="log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="cases.caselog",
                verbose_name="日志",
            ),
        ),
        migrations.AddField(
            model_name="casenumber",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_numbers",
                to="cases.case",
                verbose_name="案件",
            ),
        ),
        migrations.AddField(
            model_name="caseparty",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parties",
                to="cases.case",
                verbose_name="案件",
            ),
        ),
        migrations.AddField(
            model_name="caseparty",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_parties",
                to="client.client",
                verbose_name="当事人",
            ),
        ),
        migrations.AddField(
            model_name="chatauditlog",
            name="case",
            field=models.ForeignKey(
                blank=True,
                help_text="关联的案件",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_audit_logs",
                to="cases.case",
                verbose_name="关联案件",
            ),
        ),
        migrations.AddField(
            model_name="chatauditlog",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                help_text="关联的群聊，某些操作（如配置错误）可能没有关联群聊",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="cases.casechat",
                verbose_name="关联群聊",
            ),
        ),
        migrations.AddField(
            model_name="supervisingauthority",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervising_authorities",
                to="cases.case",
                verbose_name="案件",
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["contract"], name="cases_case_contrac_5f10b0_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["is_archived"], name="cases_case_is_arch_591fe0_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["start_date"], name="cases_case_start_d_a2435c_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["current_stage"], name="cases_case_current_1f80b8_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["-start_date"], name="cases_case_start_d_495660_idx"),
        ),
        migrations.AddIndex(
            model_name="casechat",
            index=models.Index(fields=["case", "platform"], name="cases_casec_case_id_bc52c8_idx"),
        ),
        migrations.AddIndex(
            model_name="casechat",
            index=models.Index(fields=["chat_id"], name="cases_casec_chat_id_d8fb11_idx"),
        ),
        migrations.AddIndex(
            model_name="casechat",
            index=models.Index(fields=["is_active"], name="cases_casec_is_acti_b70a82_idx"),
        ),
        migrations.AddIndex(
            model_name="casechat",
            index=models.Index(fields=["owner_id"], name="cases_casec_owner_i_14d2b1_idx"),
        ),
        migrations.AddIndex(
            model_name="casechat",
            index=models.Index(fields=["owner_verified"], name="cases_casec_owner_v_5bd906_idx"),
        ),
        migrations.AddIndex(
            model_name="casechat",
            index=models.Index(fields=["owner_verified_at"], name="cases_casec_owner_v_bb6dfd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="casechat",
            unique_together={("case", "platform", "chat_id")},
        ),
        migrations.AddIndex(
            model_name="caselog",
            index=models.Index(fields=["case", "-created_at"], name="cases_casel_case_id_81df24_idx"),
        ),
        migrations.AddIndex(
            model_name="caselog",
            index=models.Index(fields=["reminder_time"], name="cases_casel_reminde_a2637a_idx"),
        ),
        migrations.AddIndex(
            model_name="caselog",
            index=models.Index(fields=["actor"], name="cases_casel_actor_i_b1e312_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="caseparty",
            unique_together={("case", "client")},
        ),
        migrations.AddIndex(
            model_name="chatauditlog",
            index=models.Index(fields=["chat", "-timestamp"], name="cases_chata_chat_id_6f408c_idx"),
        ),
        migrations.AddIndex(
            model_name="chatauditlog",
            index=models.Index(fields=["case", "-timestamp"], name="cases_chata_case_id_6351d9_idx"),
        ),
        migrations.AddIndex(
            model_name="chatauditlog",
            index=models.Index(fields=["action", "-timestamp"], name="cases_chata_action_cd1c27_idx"),
        ),
        migrations.AddIndex(
            model_name="chatauditlog",
            index=models.Index(fields=["success", "-timestamp"], name="cases_chata_success_b9fb12_idx"),
        ),
        migrations.AddIndex(
            model_name="chatauditlog",
            index=models.Index(fields=["external_chat_id", "-timestamp"], name="cases_chata_externa_1e6bb7_idx"),
        ),
        migrations.AddIndex(
            model_name="chatauditlog",
            index=models.Index(fields=["platform", "-timestamp"], name="cases_chata_platfor_4346c4_idx"),
        ),
        migrations.AddIndex(
            model_name="chatauditlog",
            index=models.Index(fields=["-timestamp"], name="cases_chata_timesta_4973a8_idx"),
        ),
        migrations.AddIndex(
            model_name="supervisingauthority",
            index=models.Index(fields=["case"], name="cases_super_case_id_69b131_idx"),
        ),
        migrations.AddIndex(
            model_name="supervisingauthority",
            index=models.Index(fields=["authority_type"], name="cases_super_authori_710bc8_idx"),
        ),
    ]
