# Generated by Django 6.0.2 on 2026-02-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casenumber",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="是否已生效"),
        ),
    ]
