# Generated by Django 6.0.1 on 2026-01-25 06:13

import apps.cases.models
import apps.organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_materials'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='casematerial',
            new_name='cases_casem_case_id_746cf1_idx',
            old_name='cases_casem_case_id_168df1_idx',
        ),
        migrations.RenameIndex(
            model_name='casematerial',
            new_name='cases_casem_case_id_865002_idx',
            old_name='cases_casem_case_id_d806df_idx',
        ),
        migrations.RenameIndex(
            model_name='casematerial',
            new_name='cases_casem_case_id_928a97_idx',
            old_name='cases_casem_case_id_a9d1b0_idx',
        ),
        migrations.RenameIndex(
            model_name='casematerial',
            new_name='cases_casem_type_na_5a349e_idx',
            old_name='cases_casem_type_na_2374de_idx',
        ),
        migrations.RenameIndex(
            model_name='casematerialgrouporder',
            new_name='cases_casem_case_id_a1cffb_idx',
            old_name='cases_casem_case_id_7d945d_idx',
        ),
        migrations.RenameIndex(
            model_name='casematerialgrouporder',
            new_name='cases_casem_case_id_62c8f7_idx',
            old_name='cases_casem_case_id_7c1963_idx',
        ),
        migrations.RenameIndex(
            model_name='casematerialtype',
            new_name='cases_casem_categor_8f8db8_idx',
            old_name='cases_casem_category_0b8b1b_idx',
        ),
        migrations.RenameIndex(
            model_name='casematerialtype',
            new_name='cases_casem_law_fir_2bfd05_idx',
            old_name='cases_casem_law_fi_4c32e8_idx',
        ),
        migrations.RenameIndex(
            model_name='casematerialtype',
            new_name='cases_casem_is_acti_760b66_idx',
            old_name='cases_casem_is_acti_1c4e3b_idx',
        ),
        migrations.AlterField(
            model_name='caselogattachment',
            name='file',
            field=models.FileField(storage=apps.organization.models.KeepOriginalNameStorage(), upload_to='case_logs/', validators=[apps.cases.models.validate_log_attachment], verbose_name='相关文书'),
        ),
    ]
