# Generated by Django 6.0.1 on 2026-01-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_use_keep_original_name_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='preservation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='财产保全金额'),
        ),
    ]
