# Generated by Django 6.0.1 on 2026-01-25 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_add_preservation_amount'),
        ('documents', '0007_proxymatterrule_legal_status_match_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTemplateBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_source', models.CharField(choices=[('auto_recommended', '自动推荐'), ('manual_bound', '手动绑定')], default='auto_recommended', max_length=20, verbose_name='绑定来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_bindings', to='cases.case', verbose_name='案件')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_bindings', to='documents.documenttemplate', verbose_name='文书模板')),
            ],
            options={
                'verbose_name': '案件模板绑定',
                'verbose_name_plural': '案件模板绑定',
                'indexes': [models.Index(fields=['case', 'binding_source'], name='cases_caset_case_id_39590f_idx'), models.Index(fields=['template'], name='cases_caset_templat_8dfc20_idx')],
                'unique_together': {('case', 'template')},
            },
        ),
    ]
