# Generated by Django 6.0.2 on 2026-02-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0009_case_filing_number_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="filing_number",
            field=models.CharField(
                blank=True,
                help_text="格式: {年份}_{案件类型}_{AJ}_{序号}",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="建档编号",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="specified_date",
            field=models.DateField(blank=True, null=True, verbose_name="指定日期"),
        ),
    ]
