# Generated by Django 6.0.1 on 2026-02-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_add_case_filing_number_and_specified_date"),
        ("contracts", "0004_add_filing_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseFolderBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "folder_path",
                    models.CharField(
                        help_text="绑定的本地或网络文件夹路径", max_length=1000, verbose_name="文件夹路径"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="绑定时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "案件文件夹绑定",
                "verbose_name_plural": "案件文件夹绑定",
            },
        ),
        migrations.AlterModelOptions(
            name="casefilingnumbersequence",
            options={"verbose_name": "案件建档编号序列", "verbose_name_plural": "案件建档编号序列"},
        ),
        migrations.AlterField(
            model_name="case",
            name="cause_of_action",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="案由"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["filing_number"], name="cases_case_filing__2ecc17_idx"),
        ),
        migrations.AddIndex(
            model_name="casefilingnumbersequence",
            index=models.Index(fields=["year"], name="cases_casef_year_10c123_idx"),
        ),
        migrations.AddField(
            model_name="casefolderbinding",
            name="case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_binding",
                to="cases.case",
                verbose_name="案件",
            ),
        ),
        migrations.AddIndex(
            model_name="casefolderbinding",
            index=models.Index(fields=["case"], name="cases_casef_case_id_30addd_idx"),
        ),
        migrations.AddIndex(
            model_name="casefolderbinding",
            index=models.Index(fields=["created_at"], name="cases_casef_created_98b4c8_idx"),
        ),
    ]
