# Generated by Django 6.0.5 on 2026-06-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_make_start_date_editable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supervisingauthority',
            unique_together={('case', 'name')},
        ),
    ]
