# Generated by Django 6.1 on 2026-09-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0029_alter_historicalcase_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselog',
            name='event_date',
            field=models.DateField(blank=True, help_text='扫描文件夹导入或手动指定的工作日志业务日期', null=True, verbose_name='工作日志日期'),
        ),
    ]
