# Generated by Django 6.1 on 2026-09-06 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_add_caselog_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='previous_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_cases', to='cases.case', verbose_name='前序案件'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='previous_case',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.case', verbose_name='前序案件'),
        ),
    ]
