# Generated by Django 6.1.1 on 2026-09-28 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0032_alter_casefolderbinding_storage_account'),
        ('client', '0011_alter_historicalclient_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='case',
            name='cases_case_contrac_5f10b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_case_filing__2ecc17_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_case_start_d_495660_idx',
        ),
        migrations.RemoveIndex(
            model_name='caseaccessgrant',
            name='cases_casea_grantee_5cc332_idx',
        ),
        migrations.RemoveIndex(
            model_name='caseassignment',
            name='cases_casea_lawyer__3bf353_idx',
        ),
        migrations.RemoveIndex(
            model_name='casechat',
            name='cases_casec_case_id_bc52c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='casechat',
            name='cases_casec_is_acti_b70a82_idx',
        ),
        migrations.RemoveIndex(
            model_name='casechat',
            name='cases_casec_owner_v_5bd906_idx',
        ),
        migrations.RemoveIndex(
            model_name='casechat',
            name='cases_casec_owner_v_bb6dfd_idx',
        ),
        migrations.RemoveIndex(
            model_name='casefilingnumbersequence',
            name='cases_casef_year_10c123_idx',
        ),
        migrations.RemoveIndex(
            model_name='casefolderbinding',
            name='cases_casef_case_id_30addd_idx',
        ),
        migrations.RemoveIndex(
            model_name='caselog',
            name='cases_casel_actor_i_b1e312_idx',
        ),
        migrations.RemoveIndex(
            model_name='caselogattachment',
            name='cases_casel_log_id_e9778e_idx',
        ),
        migrations.RemoveIndex(
            model_name='caselogversion',
            name='cases_casel_log_id_12f3b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='caselogversion',
            name='cases_casel_actor_i_eab82d_idx',
        ),
        migrations.RemoveIndex(
            model_name='casematerialtype',
            name='cases_casem_law_fir_2bfd05_idx',
        ),
        migrations.RemoveIndex(
            model_name='casematerialtype',
            name='cases_casem_is_acti_760b66_idx',
        ),
        migrations.RemoveIndex(
            model_name='caseparty',
            name='cases_casep_client__76e55d_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatauditlog',
            name='cases_chata_success_b9fb12_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatauditlog',
            name='cases_chata_platfor_4346c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='supervisingauthority',
            name='cases_super_case_id_69b131_idx',
        ),
        migrations.AlterUniqueTogether(
            name='caseaccessgrant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='caseassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='casechat',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='caseparty',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supervisingauthority',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='caseaccessgrant',
            constraint=models.UniqueConstraint(fields=('case', 'grantee'), name='uniq_case_access_grant_case_grantee'),
        ),
        migrations.AddConstraint(
            model_name='caseassignment',
            constraint=models.UniqueConstraint(fields=('case', 'lawyer'), name='uniq_case_assignment_case_lawyer'),
        ),
        migrations.AddConstraint(
            model_name='casechat',
            constraint=models.UniqueConstraint(fields=('case', 'platform', 'chat_id'), name='uniq_case_chat_case_platform_chat'),
        ),
        migrations.AddConstraint(
            model_name='caseparty',
            constraint=models.UniqueConstraint(fields=('case', 'client'), name='uniq_case_party_case_client'),
        ),
        migrations.AddConstraint(
            model_name='supervisingauthority',
            constraint=models.UniqueConstraint(fields=('case', 'name'), name='uniq_supervising_authority_case_name'),
        ),
    ]
