# Generated by Django 6.1.1 on 2026-10-03 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0033_remove_case_cases_case_contrac_5f10b0_idx_and_more'),
        ('contracts', '0039_alter_contractassignment_lawyer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseaccessgrant',
            name='grantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_access_grants', to=settings.AUTH_USER_MODEL, verbose_name='获授权律师'),
        ),
        migrations.AlterField(
            model_name='caseassignment',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_assignments', to=settings.AUTH_USER_MODEL, verbose_name='律师'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('target_amount__gte', 0)), name='chk_case_target_amount_nonneg'),
        ),
    ]
