# Generated by Django 6.1.1 on 2026-10-03 08:34

from typing import Any

from django.db import migrations, models


def _normalize(apps: Any, app_label: str, model_name: str, fields: list[str]) -> None:
    """存量 NULL 归一为空字符串（双空态清理）。"""
    model = apps.get_model(app_label, model_name)
    for f in fields:
        model.objects.filter(**{f"{f}__isnull": True}).update(**{f: ""})


def normalize_null_to_empty(apps: Any, schema_editor: Any) -> None:
    _normalize(apps, "cases", "Case", ["cause_of_action", "case_type", "current_stage"])
    _normalize(apps, "cases", "CaseNumber", ["document_name", "document_content", "execution_manual_text", "remarks"])
    _normalize(apps, "cases", "CaseChat", ["owner_id"])
    _normalize(apps, "cases", "CaseParty", ["legal_status"])
    _normalize(apps, "cases", "CaseMaterial", ["side"])
    _normalize(apps, "cases", "CaseMaterialGroupOrder", ["side"])


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0034_alter_caseaccessgrant_grantee_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_null_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="case",
            name="case_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("civil", "民事"),
                    ("administrative", "行政"),
                    ("criminal", "刑事"),
                    ("execution", "申请执行"),
                    ("bankruptcy", "破产"),
                ],
                default="civil",
                max_length=32,
                verbose_name="案件类型",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="cause_of_action",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="案由"),
        ),
        migrations.AlterField(
            model_name="case",
            name="current_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_trial", "一审"),
                    ("second_trial", "二审"),
                    ("enforcement", "执行"),
                    ("labor_arbitration", "劳动仲裁"),
                    ("administrative_review", "行政复议"),
                    ("private_prosecution", "自诉"),
                    ("investigation", "侦查"),
                    ("prosecution_review", "审查起诉"),
                    ("retrial_first", "重审一审"),
                    ("retrial_second", "重审二审"),
                    ("apply_retrial", "申请再审"),
                    ("rehearing_first", "再审一审"),
                    ("rehearing_second", "再审二审"),
                    ("review", "提审"),
                    ("death_penalty_review", "死刑复核程序"),
                    ("petition", "申诉"),
                    ("apply_protest", "申请抗诉"),
                    ("petition_protest", "申诉抗诉"),
                ],
                default="",
                max_length=64,
                verbose_name="当前阶段",
            ),
        ),
        migrations.AlterField(
            model_name="casechat",
            name="owner_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="飞书用户的open_id或其他平台的用户标识符",
                max_length=64,
                verbose_name="群主ID",
            ),
        ),
        migrations.AlterField(
            model_name="casematerial",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("our", "我方当事人材料"), ("opponent", "对方当事人材料")],
                default="",
                max_length=32,
                verbose_name="当事人方向",
            ),
        ),
        migrations.AlterField(
            model_name="casematerialgrouporder",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("our", "我方当事人材料"), ("opponent", "对方当事人材料")],
                default="",
                max_length=32,
                verbose_name="当事人方向",
            ),
        ),
        migrations.AlterField(
            model_name="casenumber",
            name="document_content",
            field=models.TextField(
                blank=True, default="", help_text="从裁判文书自动提取的判决/调解主文内容", verbose_name="执行依据主文"
            ),
        ),
        migrations.AlterField(
            model_name="casenumber",
            name="document_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="如：民事判决书、民事调解书、执行证书等",
                max_length=128,
                verbose_name="文书名称",
            ),
        ),
        migrations.AlterField(
            model_name="casenumber",
            name="execution_manual_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="有值时模板生成优先使用该文本",
                verbose_name="申请执行事项（手工最终文本）",
            ),
        ),
        migrations.AlterField(
            model_name="casenumber",
            name="remarks",
            field=models.TextField(blank=True, default="", verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="caseparty",
            name="legal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plaintiff", "原告"),
                    ("defendant", "被告"),
                    ("third", "第三人"),
                    ("applicant", "申请人"),
                    ("respondent", "被申请人"),
                    ("criminal_defendant", "被告人"),
                    ("victim", "被害人"),
                    ("appellant", "上诉人"),
                    ("appellee", "被上诉人"),
                    ("orig_plaintiff", "原审原告"),
                    ("orig_defendant", "原审被告"),
                    ("orig_third", "原审第三人"),
                ],
                default="",
                max_length=32,
                verbose_name="诉讼地位",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="case_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("civil", "民事"),
                    ("administrative", "行政"),
                    ("criminal", "刑事"),
                    ("execution", "申请执行"),
                    ("bankruptcy", "破产"),
                ],
                default="civil",
                max_length=32,
                verbose_name="案件类型",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="cause_of_action",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="案由"),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="current_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_trial", "一审"),
                    ("second_trial", "二审"),
                    ("enforcement", "执行"),
                    ("labor_arbitration", "劳动仲裁"),
                    ("administrative_review", "行政复议"),
                    ("private_prosecution", "自诉"),
                    ("investigation", "侦查"),
                    ("prosecution_review", "审查起诉"),
                    ("retrial_first", "重审一审"),
                    ("retrial_second", "重审二审"),
                    ("apply_retrial", "申请再审"),
                    ("rehearing_first", "再审一审"),
                    ("rehearing_second", "再审二审"),
                    ("review", "提审"),
                    ("death_penalty_review", "死刑复核程序"),
                    ("petition", "申诉"),
                    ("apply_protest", "申请抗诉"),
                    ("petition_protest", "申诉抗诉"),
                ],
                default="",
                max_length=64,
                verbose_name="当前阶段",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcasenumber",
            name="document_content",
            field=models.TextField(
                blank=True, default="", help_text="从裁判文书自动提取的判决/调解主文内容", verbose_name="执行依据主文"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcasenumber",
            name="document_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="如：民事判决书、民事调解书、执行证书等",
                max_length=128,
                verbose_name="文书名称",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcasenumber",
            name="execution_manual_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="有值时模板生成优先使用该文本",
                verbose_name="申请执行事项（手工最终文本）",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcasenumber",
            name="remarks",
            field=models.TextField(blank=True, default="", verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="supervisingauthority",
            name="authority_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("investigation", "侦查机关"),
                    ("prosecution", "审查起诉机关"),
                    ("trial", "审理机构"),
                    ("detention", "当前关押地点"),
                ],
                default="trial",
                max_length=32,
                verbose_name="性质",
            ),
        ),
        migrations.AlterField(
            model_name="supervisingauthority",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="名称"),
        ),
    ]
