# Generated by Django 6.1.1 on 2026-10-03 10:39

import apps.core.filesystem.upload_paths
from typing import Any

from django.db import migrations, models, transaction


def _normalize(apps: Any, app_label: str, model_name: str, fields: list[str]) -> None:
    """存量 NULL 归一为空字符串（双空态清理）。"""
    model = apps.get_model(app_label, model_name)
    for f in fields:
        model.objects.filter(**{f"{f}__isnull": True}).update(**{f: ""})


def normalize_null_to_empty(apps: Any, schema_editor: Any) -> None:
    with transaction.atomic():
        _normalize(apps, "cases", "CaseNumber", ['document_file'])
        _normalize(apps, "cases", "HistoricalCaseNumber", ['document_file'])


class Migration(migrations.Migration):
    # UPDATE 后同事务内 ALTER 可能撞上 DEFERRABLE 外键的 pending trigger 事件
    # （PG 限制，contacts 0002 先例），数据步自包事务先提交。
    atomic = False

    dependencies = [
        ('cases', '0035_alter_case_case_type_alter_case_cause_of_action_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_null_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='casenumber',
            name='document_file',
            field=models.FileField(blank=True, default='', help_text='上传PDF格式的裁判文书，用于自动提取执行依据主文', upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('case_documents'), verbose_name='裁判文书文件'),
        ),
        migrations.AlterField(
            model_name='historicalcasenumber',
            name='document_file',
            field=models.TextField(blank=True, default='', help_text='上传PDF格式的裁判文书，用于自动提取执行依据主文', max_length=100, verbose_name='裁判文书文件'),
        ),
    ]
