# Generated by Django 6.1.1 on 2026-10-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0036_alter_casenumber_document_file_and_more'),
        ('documents', '0018_alter_documenttemplatefolderbinding_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casetemplatebinding',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='casetemplatebinding',
            constraint=models.UniqueConstraint(fields=('case', 'template'), name='uniq_case_template_binding_case_template'),
        ),
    ]
