# Generated by Django 6.1.1 on 2026-10-03 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0037_alter_casetemplatebinding_unique_together_and_more'),
        ('client', '0013_alter_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseparty',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_parties', to='client.client', verbose_name='当事人'),
        ),
    ]
