# Generated by Django 6.1.1 on 2026-10-04 08:18

from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, transaction


def clamp_folder_scan_progress(apps: Any, schema_editor: Any) -> None:
    """钳制存量越界 progress 入 [0, 100]，保证 AddConstraint 可执行。"""
    session = apps.get_model("cases", "CaseFolderScanSession")
    with transaction.atomic():
        session.objects.filter(progress__gt=100).update(progress=100)
        session.objects.filter(progress__lt=0).update(progress=0)


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0038_alter_caseparty_client'),
        ('contracts', '0044_remove_contracttypefolderrootpreset_contracts_c_case_ty_88f56d_idx_and_more'),
        ('organization', '0011_accountcredential_uniq_credential_lawyer_site_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='casetemplatebinding',
            name='cases_caset_templat_8dfc20_idx',
        ),
        migrations.AlterField(
            model_name='case',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='contracts.contract', verbose_name='关联合同'),
        ),
        migrations.AlterField(
            model_name='casematerialtype',
            name='law_firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_material_types', to='organization.lawfirm', verbose_name='律所'),
        ),
        migrations.RunPython(clamp_folder_scan_progress, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='casefolderscansession',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='chk_case_folder_scan_progress_range'),
        ),
    ]
