# Generated by Django 6.1.1 on 2026-10-04 17:40

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0039_remove_casetemplatebinding_cases_caset_templat_8dfc20_idx_and_more'),
        ('contracts', '0045_contract_contract_name_trgm'),
    ]

    operations = [
        # gin_trgm_ops 依赖 pg_trgm 扩展（幂等）：全新测试库按 app 字母序跑迁移时，
        # 本迁移可能先于携带 TrigramExtension 的 message_hub.0014 执行
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='case',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='cases_case_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
