# Generated by Django 6.1.1 on 2026-10-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_solution', '0003_alter_solutiontask_pdf_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solutionsection',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='solutionsection',
            constraint=models.UniqueConstraint(fields=('task', 'section_type'), name='uniq_solution_section_task_type'),
        ),
    ]
