# Generated by Django 6.0.6 on 2026-06-09 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAuth',
            fields=[
                ('token', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '临时授权码',
                'verbose_name_plural': '临时授权码',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='平台')),
                ('provider_uid', models.CharField(max_length=255, verbose_name='平台用户ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='平台昵称')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500, verbose_name='平台头像')),
                ('raw_profile', models.JSONField(default=dict, verbose_name='原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '社交账号',
                'verbose_name_plural': '社交账号',
                'unique_together': {('provider', 'provider_uid')},
            },
        ),
    ]
