# Generated by Django 6.1.1 on 2026-09-27 10:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0002_socialaccount_uniq_social_account_user_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempauth',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
