# Generated by Django 6.1.1 on 2026-10-03 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0003_alter_tempauth_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_uid'), name='uniq_social_account_provider_uid'),
        ),
    ]
