# Generated by Django 6.1.1 on 2026-10-04 13:49

import apps.core.model_fields.encrypted
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0004_alter_socialaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='与代码注册的 Provider 名一致：feishu / wechat / github / google', max_length=50, unique=True, verbose_name='平台标识')),
                ('display_name', models.CharField(help_text='登录页按钮上的文案', max_length=50, verbose_name='显示名称')),
                ('client_id', models.CharField(blank=True, default='', help_text='平台侧应用的客户端 ID。留空且平台支持共用凭证时自动借用（飞书扫码登录复用「系统配置 → 飞书配置」的 FEISHU_APP_ID，无需重复填写）', max_length=200, verbose_name='App ID / Client ID')),
                ('client_secret', apps.core.model_fields.encrypted.EncryptedTextField(blank=True, default='', help_text='平台侧应用的客户端密钥，加密存储；留空且平台支持共用凭证时自动借用', verbose_name='App Secret')),
                ('redirect_uri', models.CharField(blank=True, default='', help_text='后端可达地址（含协议 + Host + 路径，不是前端页面地址），必须与开放平台后台登记的完全一致——后缀、结尾斜杠差一点都会被平台拒绝。例：http://127.0.0.1:8002/social/github/callback/。上线换域名后须同步修改此处与平台后台', max_length=500, verbose_name='回调地址')),
                ('scope', models.CharField(blank=True, default='', help_text='空格分隔，留空用平台默认。例：read:user user:email', max_length=200, verbose_name='授权范围')),
                ('enabled', models.BooleanField(default=True, help_text='关闭后登录页立即隐藏该入口', verbose_name='启用')),
                ('priority', models.PositiveIntegerField(default=10, help_text='登录页按钮顺序，小的在前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '社交登录',
                'verbose_name_plural': '社交登录',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
