# Generated by Django 6.1.1 on 2026-10-04 14:40

from django.db import migrations, models

from apps.social_auth.migrations._microsoft_helpers import add_microsoft_provider, remove_microsoft_provider


class Migration(migrations.Migration):
    dependencies = [
        ("social_auth", "0006_adopt_social_auth_systemconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialauthprovider",
            name="name",
            field=models.CharField(
                help_text="与代码注册的 Provider 名一致：feishu / wechat / github / google / microsoft",
                max_length=50,
                unique=True,
                verbose_name="平台标识",
            ),
        ),
        migrations.RunPython(add_microsoft_provider, remove_microsoft_provider),
    ]
