# Generated by Django 6.1.1 on 2026-10-05 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0007_add_microsoft_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasskeyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='通行密钥', max_length=100, verbose_name='名称')),
                ('credential_id', models.CharField(max_length=512, unique=True, verbose_name='凭据ID')),
                ('public_key', models.TextField(verbose_name='公钥')),
                ('sign_count', models.PositiveBigIntegerField(default=0, verbose_name='签名计数')),
                ('rp_id', models.CharField(max_length=255, verbose_name='RP ID')),
                ('backed_up', models.BooleanField(default=False, verbose_name='可同步备份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最近使用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkey_credentials', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通行密钥',
                'verbose_name_plural': '通行密钥',
                'ordering': ['-created_at'],
            },
        ),
    ]
