# Generated by Django 6.0.1 on 2026-02-20 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecordproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat_record_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='chatrecordexporttask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_tasks', to='chat_records.chatrecordproject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='chatrecordrecording',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='chat_records.chatrecordproject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='chatrecordscreenshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='chat_records.chatrecordproject', verbose_name='项目'),
        ),
        migrations.AddIndex(
            model_name='chatrecordproject',
            index=models.Index(fields=['-created_at'], name='chat_record_created_e3135d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecordproject',
            index=models.Index(fields=['created_by'], name='chat_record_created_2cdaba_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecordexporttask',
            index=models.Index(fields=['project', '-created_at'], name='chat_record_project_514dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecordexporttask',
            index=models.Index(fields=['status', '-created_at'], name='chat_record_status_46ee60_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecordrecording',
            index=models.Index(fields=['project', '-created_at'], name='chat_record_project_03452e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecordrecording',
            index=models.Index(fields=['extract_status', '-created_at'], name='chat_record_extract_ec953d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecordscreenshot',
            index=models.Index(fields=['project', 'ordering'], name='chat_record_project_8855d4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecordscreenshot',
            index=models.Index(fields=['project', 'dhash'], name='chat_record_project_9ea8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecordscreenshot',
            index=models.Index(fields=['project', '-created_at'], name='chat_record_project_f2e392_idx'),
        ),
    ]
