# Generated by Django 6.0.1 on 2026-01-23 04:33

import apps.chat_records.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRecordRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to=apps.chat_records.models._recording_upload_to, verbose_name='录屏文件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='时长(秒)')),
                ('extract_status', models.CharField(choices=[('pending', '待处理'), ('running', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='抽帧状态')),
                ('extract_progress', models.PositiveIntegerField(default=0, verbose_name='抽帧进度百分比')),
                ('extract_current', models.PositiveIntegerField(default=0, verbose_name='抽帧当前项')),
                ('extract_total', models.PositiveIntegerField(default=0, verbose_name='抽帧总项')),
                ('extract_message', models.CharField(blank=True, max_length=255, verbose_name='抽帧进度信息')),
                ('extract_error', models.TextField(blank=True, verbose_name='抽帧错误信息')),
                ('extract_started_at', models.DateTimeField(blank=True, null=True, verbose_name='抽帧开始时间')),
                ('extract_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='抽帧完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '聊天记录录屏',
                'verbose_name_plural': '聊天记录录屏',
            },
        ),
        migrations.RenameIndex(
            model_name='chatrecordexporttask',
            new_name='chat_record_project_514dd4_idx',
            old_name='chat_records_project_7f5b5c_idx',
        ),
        migrations.RenameIndex(
            model_name='chatrecordexporttask',
            new_name='chat_record_status_46ee60_idx',
            old_name='chat_records_status_ae07c5_idx',
        ),
        migrations.RenameIndex(
            model_name='chatrecordproject',
            new_name='chat_record_created_e3135d_idx',
            old_name='chat_records_created_8f2b09_idx',
        ),
        migrations.RenameIndex(
            model_name='chatrecordproject',
            new_name='chat_record_created_2cdaba_idx',
            old_name='chat_records_created_5efc36_idx',
        ),
        migrations.RenameIndex(
            model_name='chatrecordscreenshot',
            new_name='chat_record_project_8855d4_idx',
            old_name='chat_records_project_f631f7_idx',
        ),
        migrations.RenameIndex(
            model_name='chatrecordscreenshot',
            new_name='chat_record_project_f2e392_idx',
            old_name='chat_records_project_4bb0d8_idx',
        ),
        migrations.AddField(
            model_name='chatrecordrecording',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='chat_records.chatrecordproject', verbose_name='项目'),
        ),
        migrations.AddIndex(
            model_name='chatrecordrecording',
            index=models.Index(fields=['project', '-created_at'], name='chat_record_project_03452e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecordrecording',
            index=models.Index(fields=['extract_status', '-created_at'], name='chat_record_extract_ec953d_idx'),
        ),
    ]
