# Generated by Django 6.0.1 on 2026-01-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_records', '0002_chatrecordrecording_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecordscreenshot',
            name='capture_time_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='截图时间点(秒)'),
        ),
    ]
