# Generated by Django 6.1.1 on 2026-10-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_records', '0003_alter_chatrecordexporttask_output_file'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatrecordproject',
            name='chat_record_created_2cdaba_idx',
        ),
    ]
