"""Module for django settings mapping."""

from __future__ import annotations


def build_django_settings_mapping() -> dict[str, str]:
    return {
        "SECRET_KEY": "django.secret_key",
        "DEBUG": "django.debug",
        "ALLOWED_HOSTS": "django.allowed_hosts",
        "INSTALLED_APPS": "django.installed_apps",
        "MIDDLEWARE": "django.middleware",
        "ROOT_URLCONF": "django.root_urlconf",
        "TEMPLATES": "django.templates",
        "WSGI_APPLICATION": "django.wsgi_application",
        "DATABASES": "database",
        "LANGUAGE_CODE": "django.language_code",
        "TIME_ZONE": "django.time_zone",
        "USE_I18N": "django.use_i18n",
        "USE_TZ": "django.use_tz",
        "STATIC_URL": "django.static_url",
        "STATIC_ROOT": "django.static_root",
        "MEDIA_URL": "django.media_url",
        "MEDIA_ROOT": "django.media_root",
        "AUTH_USER_MODEL": "django.auth_user_model",
        "AUTH_PASSWORD_VALIDATORS": "django.auth_password_validators",
        "CORS_ALLOW_ALL_ORIGINS": "cors.allow_all_origins",
        "CORS_ALLOWED_ORIGINS": "cors.allowed_origins",
        "CORS_ALLOW_CREDENTIALS": "cors.allow_credentials",
        "CORS_ALLOW_HEADERS": "cors.allow_headers",
        "CSRF_TRUSTED_ORIGINS": "cors.csrf_trusted_origins",
        "CACHES": "performance.cache",
        "LOGGING": "logging",
        "MOONSHOT_BASE_URL": "services.moonshot.base_url",
        "MOONSHOT_API_KEY": "services.moonshot.api_key",
        "OLLAMA": "services.ollama",
        "FEISHU": "chat_platforms.feishu",
        "DINGTALK": "chat_platforms.dingtalk",
        "WECHAT_WORK": "chat_platforms.wechat_work",
        "TELEGRAM": "chat_platforms.telegram",
        "SLACK": "chat_platforms.slack",
        "CASE_CHAT": "features.case_chat",
        "COURT_SMS_PROCESSING": "features.court_sms",
        "DOCUMENT_PROCESSING": "features.document_processing",
        "Q_CLUSTER": "performance.q_cluster",
        "RATE_LIMIT": "performance.rate_limit",
        "SCRAPER_ENCRYPTION_KEY": "security.scraper_encryption_key",
        "PERM_OPEN_ACCESS": "security.perm_open_access",
        "API_VERSION": "api.version",
    }
