"""跨模块共享错误码。

各业务模块的内部错误码保留在各自模块中，不强制集中。
只有被 2+ 个模块使用的错误码才放在这里，消除裸字符串重复。
"""

# ── 文档处理 ──
TEMPLATE_RENDER_ERROR = "TEMPLATE_RENDER_ERROR"
PDF_MERGE_FAILED = "PDF_MERGE_FAILED"
FILE_CONVERSION_FAILED = "FILE_CONVERSION_FAILED"
CONTRACT_GENERATION_FAILED = "CONTRACT_GENERATION_FAILED"
FILING_NUMBER_GENERATION_FAILED = "FILING_NUMBER_GENERATION_FAILED"

# ── 聊天/消息 ──
CHAT_CREATION_FAILED = "CHAT_CREATION_FAILED"
MESSAGE_SEND_FAILED = "MESSAGE_SEND_FAILED"
SYSTEM_ERROR = "SYSTEM_ERROR"

# ── SMS ──
SMS_SUBMIT_FAILED = "SMS_SUBMIT_FAILED"
CASE_ASSIGNMENT_FAILED = "CASE_ASSIGNMENT_FAILED"
SMS_RETRY_FAILED = "SMS_RETRY_FAILED"

# ── 通用 ──
CASE_NOT_FOUND = "CASE_NOT_FOUND"
TEXT_EXTRACTION_FAILED = "TEXT_EXTRACTION_FAILED"
REQUEST_ERROR = "REQUEST_ERROR"
