# Generated by Django 6.0.1 on 2026-01-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reminder',
            new_name='reminders_r_due_at_b7eb79_idx',
            old_name='reminders_re_due_at_6bbf33_idx',
        ),
        migrations.RenameIndex(
            model_name='reminder',
            new_name='reminders_r_reminde_c61630_idx',
            old_name='reminders_re_reminde_86cf4f_idx',
        ),
        migrations.RenameIndex(
            model_name='reminder',
            new_name='reminders_r_contrac_f13768_idx',
            old_name='reminders_re_contrac_25f5ba_idx',
        ),
        migrations.RenameIndex(
            model_name='reminder',
            new_name='reminders_r_case_lo_5b9d79_idx',
            old_name='reminders_re_case_lo_eb60b8_idx',
        ),
    ]
