# Generated by Django 6.1.1 on 2026-09-28 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0008_add_calendar_feed_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreminder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='historicalreminder',
            name='completed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='在日历上勾选完成的人；取消完成后清空。', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='historicalreminder',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='已完成'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='在日历上勾选完成的人；取消完成后清空。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reminders', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='已完成'),
        ),
    ]
