# Generated by Django 6.1.1 on 2026-10-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0009_reminder_completion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reminder',
            name='reminders_r_contrac_f13768_idx',
        ),
        migrations.RemoveIndex(
            model_name='reminder',
            name='reminders_r_case_id_11a9db_idx',
        ),
        migrations.RemoveIndex(
            model_name='reminder',
            name='reminders_r_case_lo_5b9d79_idx',
        ),
    ]
