# Generated by Django 6.1.1 on 2026-10-09 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0010_remove_reminder_reminders_r_contrac_f13768_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreminder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="全局提醒的属主；仅创建人与管理员可修改/删除。",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="全局提醒的属主；仅创建人与管理员可修改/删除。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_reminders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
    ]
