# Generated by Django 6.1.1 on 2026-10-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_parsing", "0002_documentparsingtask_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentparsingtask",
            name="q_task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Django-Q 任务 ID（安全修复：对外仅暴露本记录 id，Q id 仅内部反查用）",
                max_length=100,
                verbose_name="队列任务ID",
            ),
        ),
    ]
