# Generated by Django 6.1.1 on 2026-09-29 06:22

import apps.core.filesystem.upload_paths
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_convert', '0002_alter_docconverttool_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocConvertRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='原文件名')),
                ('mbid', models.CharField(db_index=True, max_length=64, verbose_name='文书类型标识')),
                ('mbid_name', models.CharField(blank=True, default='', max_length=128, verbose_name='文书类型名')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=16, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('output_file', models.FileField(blank=True, default='', upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('doc_convert/output'), verbose_name='转换产物')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_convert_records', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '要素式转换记录',
                'verbose_name_plural': '要素式转换记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='doc_convert_status_48072b_idx')],
            },
        ),
    ]
