# Generated by Django 6.1.1 on 2026-10-04 08:18

from typing import Any

from django.conf import settings
from django.db import migrations, models, transaction


def clamp_story_animation_progress(apps: Any, schema_editor: Any) -> None:
    """钳制存量越界 progress_percent 入 [0, 100]，保证 AddConstraint 可执行。"""
    animation = apps.get_model("story_viz", "StoryAnimation")
    with transaction.atomic():
        animation.objects.filter(progress_percent__gt=100).update(progress_percent=100)
        animation.objects.filter(progress_percent__lt=0).update(progress_percent=0)


class Migration(migrations.Migration):

    dependencies = [
        ('story_viz', '0003_add_claim_judgment_viz_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clamp_story_animation_progress, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='storyanimation',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='chk_story_animation_progress_range'),
        ),
    ]
