# Generated by Django 5.2.8 on 2025-12-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        help_text="配置项的唯一标识符，如 FEISHU_APP_ID",
                        max_length=100,
                        unique=True,
                        verbose_name="配置键",
                    ),
                ),
                ("value", models.TextField(blank=True, default="", help_text="配置项的值", verbose_name="配置值")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("feishu", "飞书配置"),
                            ("dingtalk", "钉钉配置"),
                            ("wechat_work", "企业微信配置"),
                            ("court_sms", "法院短信配置"),
                            ("ai", "AI 服务配置"),
                            ("scraper", "爬虫配置"),
                            ("general", "通用配置"),
                        ],
                        default="general",
                        help_text="配置项所属分类",
                        max_length=50,
                        verbose_name="分类",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", help_text="配置项的说明", max_length=255, verbose_name="描述"
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(
                        default=False, help_text="是否为敏感信息（如密钥、密码等）", verbose_name="敏感信息"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否启用此配置项", verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "ordering": ["category", "key"],
                "indexes": [
                    models.Index(fields=["category"], name="core_system_categor_aa7ba2_idx"),
                    models.Index(fields=["key"], name="core_system_key_07f5b4_idx"),
                ],
            },
        ),
    ]
