# Generated by Django 6.0.1 on 2026-02-20 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='会话ID')),
                ('user_id', models.CharField(blank=True, max_length=100, verbose_name='用户ID')),
                ('role', models.CharField(choices=[('system', '系统'), ('user', '用户'), ('assistant', '助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('step', models.CharField(blank=True, help_text='document_type/litigation_goal/evidence_selection/generation', max_length=50, verbose_name='对话步骤')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '对话历史',
                'verbose_name_plural': '对话历史',
                'db_table': 'core_conversation_history',
                'ordering': ['session_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='法院编码')),
                ('name', models.CharField(max_length=200, verbose_name='法院名称')),
                ('level', models.IntegerField(default=1, verbose_name='层级')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='省份')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '法院',
                'verbose_name_plural': '法院',
                'ordering': ['province', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LLMCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='模型')),
                ('prompt_tokens', models.IntegerField(verbose_name='输入 Token')),
                ('completion_tokens', models.IntegerField(verbose_name='输出 Token')),
                ('total_tokens', models.IntegerField(verbose_name='总 Token')),
                ('duration_ms', models.FloatField(verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
            ],
            options={
                'verbose_name': 'LLM 调用记录',
                'verbose_name_plural': 'LLM 调用记录',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('title', models.CharField(max_length=200, verbose_name='显示标题')),
                ('template', models.TextField(verbose_name='模板内容')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('variables', models.JSONField(default=list, verbose_name='变量列表')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='分类')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Prompt 模板',
                'verbose_name_plural': 'Prompt 模板',
                'db_table': 'core_prompt_template',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='配置项的唯一标识符,如 FEISHU_APP_ID', max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(blank=True, default='', help_text='配置项的值', verbose_name='配置值')),
                ('category', models.CharField(choices=[('feishu', '飞书配置'), ('dingtalk', '钉钉配置'), ('wechat_work', '企业微信配置'), ('court_sms', '法院短信配置'), ('ai', 'AI 服务配置'), ('llm', 'LLM 大模型配置'), ('scraper', '爬虫配置'), ('general', '通用配置')], default='general', help_text='配置项所属分类', max_length=50, verbose_name='分类')),
                ('description', models.CharField(blank=True, default='', help_text='配置项的说明', max_length=255, verbose_name='描述')),
                ('is_secret', models.BooleanField(default=False, help_text='是否为敏感信息(如密钥、密码等)', verbose_name='敏感信息')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用此配置项', verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CauseOfAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='案由的唯一编码标识', max_length=50, unique=True, verbose_name='案由编码')),
                ('name', models.CharField(help_text='案由的中文名称', max_length=255, verbose_name='案由名称')),
                ('case_type', models.CharField(choices=[('civil', '民事'), ('criminal', '刑事'), ('administrative', '行政')], help_text='案由所属的案件类型', max_length=32, verbose_name='案件类型')),
                ('level', models.IntegerField(default=1, help_text='案由在层级结构中的深度,从1开始', verbose_name='层级')),
                ('is_active', models.BooleanField(default=True, help_text='是否在系统中启用此案由', verbose_name='是否启用')),
                ('is_deprecated', models.BooleanField(default=False, help_text='案由是否已被法院系统废弃', verbose_name='是否已废弃')),
                ('deprecated_at', models.DateTimeField(blank=True, help_text='案由被标记为废弃的时间', null=True, verbose_name='废弃时间')),
                ('deprecated_reason', models.CharField(blank=True, default='', help_text='案由被废弃的原因说明', max_length=255, verbose_name='废弃原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, help_text='父级案由,用于构建层级结构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.causeofaction', verbose_name='上级案由')),
            ],
            options={
                'verbose_name': '案由',
                'verbose_name_plural': '案由',
                'ordering': ['case_type', 'code'],
            },
        ),
    ]
