# Generated by Django 6.0.1 on 2026-02-20 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('litigation_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationhistory',
            name='litigation_session',
            field=models.ForeignKey(blank=True, help_text='关联到 AI 文书生成会话(如果适用)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_histories', to='litigation_ai.litigationsession', verbose_name='AI文书生成会话'),
        ),
        migrations.AddField(
            model_name='court',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.court', verbose_name='上级法院'),
        ),
        migrations.AddIndex(
            model_name='llmcallrecord',
            index=models.Index(fields=['created_at'], name='core_llmcal_created_830747_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcallrecord',
            index=models.Index(fields=['model'], name='core_llmcal_model_df0279_idx'),
        ),
        migrations.AddIndex(
            model_name='systemconfig',
            index=models.Index(fields=['category'], name='core_system_categor_aa7ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='systemconfig',
            index=models.Index(fields=['key'], name='core_system_key_07f5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='causeofaction',
            index=models.Index(fields=['case_type'], name='core_causeo_case_ty_0bbdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='causeofaction',
            index=models.Index(fields=['name'], name='core_causeo_name_742c92_idx'),
        ),
        migrations.AddIndex(
            model_name='causeofaction',
            index=models.Index(fields=['is_active'], name='core_causeo_is_acti_fc1798_idx'),
        ),
        migrations.AddIndex(
            model_name='causeofaction',
            index=models.Index(fields=['is_deprecated'], name='core_causeo_is_depr_7ecc77_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationhistory',
            index=models.Index(fields=['session_id', 'created_at'], name='core_conver_session_f8b2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationhistory',
            index=models.Index(fields=['user_id', 'created_at'], name='core_conver_user_id_8a9c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationhistory',
            index=models.Index(fields=['litigation_session', 'created_at'], name='core_conver_litigat_77db61_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationhistory',
            index=models.Index(fields=['step'], name='core_conver_step_f2985c_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['province'], name='core_court_provinc_9fe4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['level'], name='core_court_level_dc4c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['name'], name='core_court_name_6afac9_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['is_active'], name='core_court_is_acti_16a9bd_idx'),
        ),
    ]
