# Generated by Django 6.0.1 on 2026-02-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=2, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='court',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
