# Generated by Django 6.1 on 2026-09-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cloudstorageaccount_core_clouds_storage_fe624d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcallrecord',
            name='backend',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='后端'),
        ),
        migrations.AddField(
            model_name='llmcallrecord',
            name='caller',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='调用方'),
        ),
        migrations.AddField(
            model_name='llmcallrecord',
            name='error_summary',
            field=models.TextField(blank=True, default='', verbose_name='错误摘要'),
        ),
        migrations.AddField(
            model_name='llmcallrecord',
            name='error_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='错误类型'),
        ),
        migrations.AddField(
            model_name='llmcallrecord',
            name='success',
            field=models.BooleanField(default=True, verbose_name='是否成功'),
        ),
        migrations.AddIndex(
            model_name='llmcallrecord',
            index=models.Index(fields=['success'], name='core_llmcal_success_be34c7_idx'),
        ),
    ]
