# Generated by Django 6.1.1 on 2026-09-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_llmcallrecord_backend_llmcallrecord_caller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcallrecord',
            name='version',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='审计版本'),
        ),
    ]
