# Generated by Django 6.1.1 on 2026-09-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_llmcallrecord_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='平台名称')),
                ('base_url', models.CharField(help_text='OpenAI-compatible 接口地址，如 https://api.example.com/v1', max_length=500, verbose_name='API 地址')),
                ('api_keys', models.TextField(blank=True, default='', help_text='每行一个 Key；留空表示无需鉴权（本地 vLLM 等）。配置多个 Key 可提升并发上限', verbose_name='API Keys')),
                ('default_model', models.CharField(help_text='未指定模型时使用的模型名称', max_length=100, verbose_name='默认模型')),
                ('extra_models', models.TextField(blank=True, default='', help_text='该平台提供的模型名称，逗号分隔；留空则仅注册默认模型。用于「模型 → 平台」自动路由', verbose_name='模型列表')),
                ('embedding_model', models.CharField(blank=True, default='', help_text='留空沿用默认模型', max_length=100, verbose_name='向量模型')),
                ('timeout', models.PositiveIntegerField(default=120, verbose_name='超时（秒）')),
                ('concurrency_per_key', models.PositiveIntegerField(default=0, help_text='单个 Key 同时进行的请求数上限；0 表示不限制。配合多 Key 可精细控制并发', verbose_name='每 Key 并发上限')),
                ('priority', models.PositiveIntegerField(default=10, help_text='数字越小越优先；模型未匹配任何平台时使用优先级最高的平台', verbose_name='优先级')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 平台',
                'verbose_name_plural': 'AI 平台',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
