# Generated by Django 6.1.1 on 2026-09-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_llm_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='api_keys',
            field=models.TextField(blank=True, default='', verbose_name='API Keys'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='base_url',
            field=models.CharField(max_length=500, verbose_name='API 地址'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='concurrency_per_key',
            field=models.PositiveIntegerField(default=3, verbose_name='每 Key 并发上限'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='default_model',
            field=models.CharField(max_length=100, verbose_name='默认模型'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='向量模型'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='extra_models',
            field=models.TextField(blank=True, default='', verbose_name='模型列表'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='priority',
            field=models.PositiveIntegerField(default=10, verbose_name='优先级'),
        ),
    ]
