# Generated by Django 6.1.1 on 2026-09-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_llmprovider_api_keys_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentParseProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='平台名称')),
                ('provider_type', models.CharField(choices=[('textin', 'TextinParse'), ('mineru', 'MinerU')], max_length=20, verbose_name='解析服务')),
                ('credentials', models.TextField(blank=True, default='', verbose_name='凭证')),
                ('concurrency_per_key', models.PositiveIntegerField(default=3, verbose_name='每凭证并发上限')),
                ('priority', models.PositiveIntegerField(default=10, verbose_name='优先级')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '解析平台',
                'verbose_name_plural': '解析平台',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
