# Generated by Django 6.1.1 on 2026-09-11

"""把旧的 SystemConfig 文档解析配置迁移到 DocumentParseProvider，并删除旧的解析配置键。

文档解析配置由「解析平台」管理页（DocumentParseProvider）全权负责，
旧的 SystemConfig 键（MINERU_API_KEY / TEXTIN_APP_ID / TEXTIN_SECRET_CODE /
DOCUMENT_PARSING_BACKEND）不再使用。
"""

import re
from typing import Any

from django.db import migrations

_LEGACY_KEYS = [
    "MINERU_API_KEY",
    "TEXTIN_APP_ID",
    "TEXTIN_SECRET_CODE",
    "DOCUMENT_PARSING_BACKEND",
]


def _decrypt_secret(codec: Any, value: str) -> str:
    if codec.is_encrypted(value):
        value = codec.decrypt(value)
    return value or ""


def _split_keys(raw: str) -> list[str]:
    seen: list[str] = []
    for part in re.split(r"[,\s\r\n]+", raw):
        key = part.strip()
        if key.startswith("Bearer "):
            key = key[7:].strip()
        if key and key not in seen:
            seen.append(key)
    return seen


def seed_and_cleanup(apps: Any, schema_editor: Any) -> None:
    from apps.core.security.secret_codec import SecretCodec

    SystemConfig = apps.get_model("core", "SystemConfig")
    DocumentParseProvider = apps.get_model("core", "DocumentParseProvider")

    vals = {c.key: c for c in SystemConfig.objects.filter(key__in=_LEGACY_KEYS)}
    codec = SecretCodec()

    preferred_backend = ""
    cfg = vals.get("DOCUMENT_PARSING_BACKEND")
    if cfg is not None and not cfg.is_secret:
        preferred_backend = (cfg.value or "").strip().lower()

    # MinerU：旧 key 可能是空格/逗号分隔的多 key，拆分成多行凭证
    mineru_cfg = vals.get("MINERU_API_KEY")
    if mineru_cfg is not None and mineru_cfg.value:
        keys = _split_keys(_decrypt_secret(codec, mineru_cfg.value))
        if keys and not DocumentParseProvider.objects.filter(
            provider_type="mineru"
        ).exists():
            DocumentParseProvider.objects.create(
                name="MinerU（迁移）",
                provider_type="mineru",
                credentials="\n".join(keys),
                concurrency_per_key=3,
                priority=5 if preferred_backend == "mineru" else 10,
                enabled=True,
            )

    # TextinParse：app_id + secret_code 配对成一行 app_id|secret_code
    textin_app = vals.get("TEXTIN_APP_ID")
    textin_secret = vals.get("TEXTIN_SECRET_CODE")
    if textin_app is not None and textin_secret is not None:
        app_id = _decrypt_secret(codec, textin_app.value).strip()
        secret_code = _decrypt_secret(codec, textin_secret.value).strip()
        if app_id and secret_code and not DocumentParseProvider.objects.filter(
            provider_type="textin"
        ).exists():
            DocumentParseProvider.objects.create(
                name="TextinParse（迁移）",
                provider_type="textin",
                credentials=f"{app_id}|{secret_code}",
                concurrency_per_key=3,
                priority=5 if preferred_backend == "textin" else 10,
                enabled=True,
            )

    # 删除旧的解析配置键
    SystemConfig.objects.filter(key__in=_LEGACY_KEYS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_document_parse_provider"),
    ]

    operations = [
        migrations.RunPython(seed_and_cleanup, migrations.RunPython.noop),
    ]
