# Generated by Django 6.1.1 on 2026-09-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_seed_document_parse_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentparseprovider',
            options={'ordering': ['priority', 'name'], 'verbose_name': '文档解析平台', 'verbose_name_plural': '文档解析平台'},
        ),
    ]
