# Generated by Django 6.1.1 on 2026-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_ollama_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='vision_model',
            field=models.CharField(blank=True, default='', help_text='多模态模型名（用于文书图片/扫描件视觉转写），留空禁用视觉转写走本地 OCR', max_length=100, verbose_name='视觉模型'),
        ),
    ]
