# Generated by Django 6.1.1 on 2026-10-03 00:57

"""LLMProvider.api_keys / DocumentParseProvider.credentials 改为加密存储（审计 P2）。

字段切换为 EncryptedTextField（save 时自动加密、load 时透明解密）后，
存量明文凭证由本迁移统一加密回写，与 AccountCredential.password 的加密标准对齐。
已带 ``enc:v1:`` 前缀的值（历史写入已加密）保持幂等跳过。
"""

from typing import Any

import apps.core.model_fields.encrypted
from django.db import migrations


def encrypt_existing_secrets(apps: Any, schema_editor: Any) -> None:
    from apps.core.security.secret_codec import SecretCodec

    codec = SecretCodec()
    targets: list[tuple[str, str]] = [
        ("LLMProvider", "api_keys"),
        ("DocumentParseProvider", "credentials"),
    ]
    for model_name, field_name in targets:
        model = apps.get_model("core", model_name)
        rows = model.objects.exclude(**{field_name: ""}).exclude(**{f"{field_name}__isnull": True})
        for row in rows:
            value = str(getattr(row, field_name) or "")
            if codec.is_encrypted(value):
                continue
            setattr(row, field_name, codec.encrypt(value))
            row.save(update_fields=[field_name])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_llmprovider_vision_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentparseprovider',
            name='credentials',
            field=apps.core.model_fields.encrypted.EncryptedTextField(blank=True, default='', verbose_name='凭证'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='api_keys',
            field=apps.core.model_fields.encrypted.EncryptedTextField(blank=True, default='', verbose_name='API Keys'),
        ),
        migrations.RunPython(encrypt_existing_secrets, migrations.RunPython.noop),
    ]
