# Generated by Django 6.1.1 on 2026-10-03 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_documentparseprovider_credentials_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolfavorite',
            options={'verbose_name': '工具收藏', 'verbose_name_plural': '工具收藏'},
        ),
        migrations.AlterUniqueTogether(
            name='toolfavorite',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='toolfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'tool_url'), name='uniq_tool_favorite_user_url'),
        ),
    ]
