# Generated by Django 6.1.1 on 2026-10-04 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_toolfavorite_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="toolfavorite",
            options={"ordering": ["-created_at"], "verbose_name": "工具收藏", "verbose_name_plural": "工具收藏"},
        ),
    ]
