# Generated by Django 6.1.1 on 2026-10-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_toolfavorite_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='systemconfig',
            name='core_system_key_07f5b4_idx',
        ),
    ]
