# Generated by Django 6.1.1 on 2026-10-04 17:40

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_systemconfig_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='causeofaction',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='core_cause_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='causeofaction',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code'], name='core_cause_code_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='court',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='core_court_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
