# Generated by Django 6.0.8 on 2026-08-23 12:42

import apps.core.filesystem.upload_paths
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrationDocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('district', models.CharField(choices=[('shizhi', '佛山市直'), ('shunde', '顺德区'), ('chancheng', '禅城区'), ('nanhai', '南海区'), ('sanshui', '三水区'), ('gaoming', '高明区')], default='shizhi', max_length=32, verbose_name='区县')),
                ('list_url', models.URLField(max_length=512, unique=True, verbose_name='列表页 URL')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('parse_backend', models.CharField(choices=[('local', '本地 OCR (PyMuPDF)'), ('mineru', 'MinerU (云端)'), ('textin', 'TextIn (云端)'), ('auto', '自动')], default='local', max_length=16, verbose_name='解析后端')),
                ('max_pages', models.PositiveIntegerField(default=5, help_text='单次更新最多翻几页列表', verbose_name='最大翻页数')),
                ('detail_image_container_selector', models.CharField(blank=True, default='', help_text='如 #content / .article；留空则自动探测内容容器', max_length=256, verbose_name='详情图容器选择器')),
                ('detail_image_selector', models.CharField(blank=True, default='img', help_text='容器内匹配图片的 CSS 选择器', max_length=256, verbose_name='详情图片选择器')),
                ('last_crawl_at', models.DateTimeField(blank=True, null=True, verbose_name='上次爬取时间')),
                ('last_crawl_status', models.CharField(choices=[('idle', '未爬取'), ('running', '爬取中'), ('success', '成功'), ('failed', '失败')], default='idle', max_length=16, verbose_name='上次爬取状态')),
                ('last_crawl_summary', models.JSONField(blank=True, default=dict, null=True, verbose_name='上次爬取摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '仲裁文书来源',
                'verbose_name_plural': '仲裁文书来源',
                'ordering': ['district', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='标题')),
                ('case_number', models.CharField(blank=True, default='', max_length=128, verbose_name='案号')),
                ('detail_url', models.URLField(max_length=1024, unique=True, verbose_name='详情页 URL')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('content_hash', models.CharField(blank=True, default='', help_text='详情页 HTML 指纹，用于变更探测', max_length=64, verbose_name='内容指纹')),
                ('crawl_status', models.CharField(choices=[('pending', '待爬取'), ('crawling', '爬取中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='爬取状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('parse_status', models.CharField(choices=[('pending', '待解析'), ('processing', '解析中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='解析状态')),
                ('parse_backend', models.CharField(blank=True, default='', max_length=16, verbose_name='解析后端')),
                ('parsed_text', models.TextField(blank=True, default='', verbose_name='解析文本')),
                ('parsed_markdown', models.TextField(blank=True, default='', verbose_name='解析 Markdown')),
                ('parse_error', models.TextField(blank=True, default='', verbose_name='解析错误')),
                ('parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='解析时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='labor_arbitration.arbitrationdocumentsource', verbose_name='来源')),
            ],
            options={
                'verbose_name': '仲裁文书',
                'verbose_name_plural': '仲裁文书',
                'ordering': ['-publish_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrationDocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('labor_arbitration/docs'), verbose_name='图片')),
                ('page_index', models.PositiveIntegerField(default=0, verbose_name='页码')),
                ('source_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='原图 URL')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='宽')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='labor_arbitration.arbitrationdocument', verbose_name='文书')),
            ],
            options={
                'verbose_name': '文书图片',
                'verbose_name_plural': '文书图片',
                'ordering': ['document', 'page_index'],
                'indexes': [models.Index(fields=['document', 'page_index'], name='labor_arbit_documen_448f16_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='arbitrationdocument',
            index=models.Index(fields=['source', 'crawl_status'], name='labor_arbit_source__5ece92_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrationdocument',
            index=models.Index(fields=['case_number'], name='labor_arbit_case_nu_f98aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrationdocument',
            index=models.Index(fields=['parse_status'], name='labor_arbit_parse_s_87506a_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrationdocument',
            index=models.Index(fields=['-publish_date'], name='labor_arbit_publish_f59621_idx'),
        ),
    ]
