# Generated by Django 6.0.8 on 2026-08-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor_arbitration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbitrationdocument',
            options={'ordering': ['-publish_datetime', '-publish_date', '-id'], 'verbose_name': '仲裁文书', 'verbose_name_plural': '仲裁文书'},
        ),
        migrations.AddField(
            model_name='arbitrationdocument',
            name='publish_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AddIndex(
            model_name='arbitrationdocument',
            index=models.Index(fields=['-publish_datetime'], name='labor_arbit_publish_bd4265_idx'),
        ),
    ]
