# Generated by Django 6.0.8 on 2026-08-24 03:49

import apps.core.filesystem.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor_arbitration', '0002_alter_arbitrationdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrationdocumentsource',
            name='category_id',
            field=models.PositiveIntegerField(blank=True, help_text='列表接口 postmeta/i/{category_id}.json 的栏目 ID，用于 HTTP 快速抓取', null=True, verbose_name='栏目 ID'),
        ),
        migrations.AlterField(
            model_name='arbitrationdocumentimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('labor_arbitration/docs'), verbose_name='图片'),
        ),
    ]
