# Generated by Django 6.0.8 on 2026-08-25 00:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor_arbitration', '0003_arbitrationdocumentsource_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrationdocument',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='全文搜索向量'),
        ),
        migrations.AddIndex(
            model_name='arbitrationdocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='labor_doc_search_gin'),
        ),
    ]
