# Generated by Django 6.1.1 on 2026-10-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor_arbitration', '0004_arbitrationdocument_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitrationdocumentsource',
            name='detail_image_container_selector',
        ),
        migrations.RemoveField(
            model_name='arbitrationdocumentsource',
            name='detail_image_selector',
        ),
        migrations.RemoveField(
            model_name='arbitrationdocumentsource',
            name='max_pages',
        ),
    ]
