# Generated by Django 6.0.8 on 2026-08-25 02:15

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor_arbitration', '0004_arbitrationdocument_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrationdocument',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True, verbose_name='语义向量'),
        ),
        migrations.AddIndex(
            model_name='arbitrationdocument',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding_vector'], m=16, name='labor_doc_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
