# Generated by Django 6.0.8 on 2026-08-25 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor_arbitration', '0005_arbitrationdocument_embedding_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='arbitrationdocument',
            name='labor_doc_embedding_hnsw',
        ),
        migrations.RemoveField(
            model_name='arbitrationdocument',
            name='embedding_vector',
        ),
    ]
