# Generated by Django 6.1.1 on 2026-10-03 08:34

from typing import Any

from django.db import migrations, models


def _normalize(apps: Any, app_label: str, model_name: str, fields: list[str]) -> None:
    """存量 NULL 归一为空字符串（双空态清理）。"""
    model = apps.get_model(app_label, model_name)
    for f in fields:
        model.objects.filter(**{f"{f}__isnull": True}).update(**{f: ""})


def normalize_null_to_empty(apps: Any, schema_editor: Any) -> None:
    _normalize(apps, "contacts", "CaseContact", ["phone", "address", "stage", "note"])


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(normalize_null_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="casecontact",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="收件地址"),
        ),
        migrations.AlterField(
            model_name="casecontact",
            name="note",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="casecontact",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="电话"),
        ),
        migrations.AlterField(
            model_name="casecontact",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_trial", "一审"),
                    ("second_trial", "二审"),
                    ("enforcement", "执行"),
                    ("labor_arbitration", "劳动仲裁"),
                    ("administrative_review", "行政复议"),
                    ("private_prosecution", "自诉"),
                    ("investigation", "侦查"),
                    ("prosecution_review", "审查起诉"),
                    ("retrial_first", "重审一审"),
                    ("retrial_second", "重审二审"),
                    ("apply_retrial", "申请再审"),
                    ("rehearing_first", "再审一审"),
                    ("rehearing_second", "再审二审"),
                    ("review", "提审"),
                    ("death_penalty_review", "死刑复核程序"),
                    ("petition", "申诉"),
                    ("apply_protest", "申请抗诉"),
                    ("petition_protest", "申诉抗诉"),
                ],
                default="",
                max_length=64,
                verbose_name="所属阶段",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcasecontact",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="收件地址"),
        ),
        migrations.AlterField(
            model_name="historicalcasecontact",
            name="note",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="historicalcasecontact",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="电话"),
        ),
        migrations.AlterField(
            model_name="historicalcasecontact",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_trial", "一审"),
                    ("second_trial", "二审"),
                    ("enforcement", "执行"),
                    ("labor_arbitration", "劳动仲裁"),
                    ("administrative_review", "行政复议"),
                    ("private_prosecution", "自诉"),
                    ("investigation", "侦查"),
                    ("prosecution_review", "审查起诉"),
                    ("retrial_first", "重审一审"),
                    ("retrial_second", "重审二审"),
                    ("apply_retrial", "申请再审"),
                    ("rehearing_first", "再审一审"),
                    ("rehearing_second", "再审二审"),
                    ("review", "提审"),
                    ("death_penalty_review", "死刑复核程序"),
                    ("petition", "申诉"),
                    ("apply_protest", "申请抗诉"),
                    ("petition_protest", "申诉抗诉"),
                ],
                default="",
                max_length=64,
                verbose_name="所属阶段",
            ),
        ),
    ]
