# Generated by Django 6.1.1 on 2026-10-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_casecontact_address_alter_casecontact_note_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='casecontact',
            name='contacts_ca_case_id_dfd478_idx',
        ),
        migrations.RemoveIndex(
            model_name='casecontact',
            name='contacts_ca_authori_857626_idx',
        ),
    ]
