# Generated by Django 6.0.1 on 2026-02-20 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('litigation_ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='litigationsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litigation_sessions', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddIndex(
            model_name='evidencechunk',
            index=models.Index(fields=['evidence_item'], name='litigation__evidenc_13942d_idx'),
        ),
        migrations.AddIndex(
            model_name='litigationsession',
            index=models.Index(fields=['session_id'], name='documents_l_session_80e25a_idx'),
        ),
        migrations.AddIndex(
            model_name='litigationsession',
            index=models.Index(fields=['case', '-created_at'], name='documents_l_case_id_89c48b_idx'),
        ),
        migrations.AddIndex(
            model_name='litigationsession',
            index=models.Index(fields=['user', '-created_at'], name='documents_l_user_id_76982c_idx'),
        ),
        migrations.AddIndex(
            model_name='litigationsession',
            index=models.Index(fields=['status'], name='documents_l_status_250626_idx'),
        ),
        migrations.AddIndex(
            model_name='litigationsession',
            index=models.Index(fields=['document_type'], name='documents_l_documen_5ea5d2_idx'),
        ),
    ]
