# Generated by Django 6.1.1 on 2026-10-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation_ai', '0003_rename_documents_li_session_8e1f3a_idx_documents_l_session_07fff0_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='evidencechunk',
            name='litigation__evidenc_13942d_idx',
        ),
        migrations.RemoveIndex(
            model_name='litigationsession',
            name='documents_l_session_80e25a_idx',
        ),
    ]
