# Generated by Django 6.1.1 on 2026-10-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_evidencelist_merge_progress_constraints'),
        ('litigation_ai', '0004_remove_evidencechunk_litigation__evidenc_13942d_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='evidencechunk',
            constraint=models.UniqueConstraint(fields=('evidence_item', 'page_start'), name='uniq_evidencechunk_item_page_start'),
        ),
    ]
