# Generated by Django 6.1.1 on 2026-09-15 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_hub', '0009_remove_messagesource_message_hub_is_enab_c8fd8c_idx'),
        ('organization', '0008_encrypt_credential_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='draft_state',
            field=models.JSONField(blank=True, default=dict, verbose_name='拆分草稿'),
        ),
        migrations.AlterField(
            model_name='messagesource',
            name='credential',
            field=models.ForeignKey(blank=True, help_text='手动上传来源无外部账号，可留空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_sources', to='organization.accountcredential', verbose_name='账号凭证'),
        ),
        migrations.AlterField(
            model_name='messagesource',
            name='source_type',
            field=models.CharField(choices=[('imap', 'IMAP 邮箱'), ('manual_upload', '前端手动上传'), ('court_inbox', '一张网收件箱'), ('court_schedule', '一张网庭审日程')], default='imap', max_length=32, verbose_name='来源类型'),
        ),
    ]
