# Generated by Django 6.1.1 on 2026-09-18 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_hub', '0011_inboxmessage_uploaded_by'),
        ('organization', '0008_encrypt_credential_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesource',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_sources', to='organization.accountcredential', verbose_name='账号凭证'),
        ),
        migrations.AlterField(
            model_name='messagesource',
            name='sender_blacklist',
            field=models.TextField(blank=True, verbose_name='不同步这些发件人'),
        ),
        migrations.AlterField(
            model_name='messagesource',
            name='sender_whitelist',
            field=models.TextField(blank=True, verbose_name='只同步这些发件人'),
        ),
    ]
