# Generated by Django 6.1.1 on 2026-09-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_hub', '0012_alter_messagesource_credential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesource',
            name='imap_account',
            field=models.CharField(blank=True, max_length=255, verbose_name='IMAP 账号'),
        ),
        migrations.AlterField(
            model_name='messagesource',
            name='imap_host',
            field=models.CharField(blank=True, max_length=255, verbose_name='IMAP 主机'),
        ),
    ]
