# Generated by Django 6.1.1 on 2026-09-29 11:51

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_hub', '0013_alter_messagesource_imap_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # gin_trgm_ops 依赖 pg_trgm 扩展（幂等：已安装时跳过）
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='inboxmessage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['subject'], name='inbox_msg_subject_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='inboxmessage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sender'], name='inbox_msg_sender_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='inboxmessage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['body_text'], name='inbox_msg_body_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
