# Generated by Django 6.1.1 on 2026-10-03 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_hub', '0014_inboxmessage_inbox_msg_subject_trgm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inboxmessage',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='inboxmessage',
            constraint=models.UniqueConstraint(fields=('source', 'message_id'), name='uniq_inbox_message_source_msgid'),
        ),
    ]
