# Generated by Django 6.1.1 on 2026-10-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lprrate',
            name='finance_lpr_eff_date_idx',
        ),
        migrations.AddConstraint(
            model_name='lprrate',
            constraint=models.CheckConstraint(condition=models.Q(('rate_1y__gte', 0)), name='chk_lprrate_rate_1y_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='lprrate',
            constraint=models.CheckConstraint(condition=models.Q(('rate_5y__gte', 0)), name='chk_lprrate_rate_5y_nonneg'),
        ),
    ]
