# Generated by Django 6.0.6 on 2026-07-06 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0035_alter_historicalcontract_created_at_and_more'),
        ('oa_filing', '0012_remove_caseimportsession_oa_filing_c_lawyer__3c2fe4_idx_and_more'),
        ('organization', '0008_encrypt_credential_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StampSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oa_case_number', models.CharField(max_length=100, verbose_name='律所OA案件编号')),
                ('file_path', models.CharField(max_length=1000, verbose_name='上传文件路径')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_sessions', to='contracts.contract', verbose_name='合同')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamp_sessions', to='organization.accountcredential', verbose_name='登录凭证')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_sessions', to=settings.AUTH_USER_MODEL, verbose_name='发起用户')),
            ],
            options={
                'verbose_name': '盖章申请记录',
                'verbose_name_plural': '盖章申请记录',
                'indexes': [models.Index(fields=['contract', '-created_at'], name='oa_filing_s_contrac_583998_idx'), models.Index(fields=['user', '-created_at'], name='oa_filing_s_user_id_949e13_idx'), models.Index(fields=['status', '-created_at'], name='oa_filing_s_status_ff95ea_idx')],
            },
        ),
    ]
