# Generated by Django 6.0.6 on 2026-07-07 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0035_alter_historicalcontract_created_at_and_more"),
        ("oa_filing", "0013_stamp_session"),
        ("organization", "0008_encrypt_credential_password"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("oa_case_number", models.CharField(max_length=100, verbose_name="律所OA案件编号")),
                ("file_paths", models.JSONField(default=list, verbose_name="归档文件路径列表")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待开始"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_sessions",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archive_sessions",
                        to="organization.accountcredential",
                        verbose_name="登录凭证",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "归档申请记录",
                "verbose_name_plural": "归档申请记录",
                "indexes": [
                    models.Index(fields=["contract", "-created_at"], name="oa_filing_a_contrac_58539a_idx"),
                    models.Index(fields=["user", "-created_at"], name="oa_filing_a_user_id_9b0fdf_idx"),
                    models.Index(fields=["status", "-created_at"], name="oa_filing_a_status_0cb219_idx"),
                ],
            },
        ),
    ]
