# Generated by Django 6.1.1 on 2026-10-03 08:34

from typing import Any

from django.db import migrations, models


def _normalize(apps: Any, app_label: str, model_name: str, fields: list[str]) -> None:
    """存量 NULL 归一为空字符串（双空态清理）。"""
    model = apps.get_model(app_label, model_name)
    for f in fields:
        model.objects.filter(**{f"{f}__isnull": True}).update(**{f: ""})


def normalize_null_to_empty(apps: Any, schema_editor: Any) -> None:
    _normalize(apps, "workflow", "StepExecution", ["error_message"])


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0003_remove_workflowrun_workflow_wo_case_id_61f540_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_null_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="stepexecution",
            name="error_message",
            field=models.TextField(blank=True, default="", verbose_name="错误信息"),
        ),
    ]
