# Generated by Django 6.1.1 on 2026-10-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_stepexecution_error_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stepexecution',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stepexecution',
            constraint=models.UniqueConstraint(fields=('workflow_run', 'step_id'), name='uniq_step_execution_run_step'),
        ),
    ]
