# Generated by Django 6.1.1 on 2026-10-04 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_alter_stepexecution_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stepexecution',
            name='acted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批/执行时间'),
        ),
        migrations.AddField(
            model_name='stepexecution',
            name='acted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审批/执行人'),
        ),
    ]
