# Generated by Django 6.0.1 on 2026-02-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="legal_representative_id_number",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="法定代表人/负责人身份证号码"),
        ),
        migrations.AddField(
            model_name="clientidentitydoc",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="到期日期"),
        ),
        migrations.AlterField(
            model_name="client",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=64, null=True, unique=True, verbose_name="身份证号码或统一社会信用代码"
            ),
        ),
        migrations.AlterField(
            model_name="clientidentitydoc",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("id_card", "身份证"),
                    ("passport", "护照"),
                    ("hk_macao_permit", "港澳通行证"),
                    ("residence_permit", "居住证"),
                    ("household_register", "户口本"),
                    ("business_license", "营业执照"),
                    ("legal_rep_id_card", "法定代表人/负责人身份证"),
                ],
                max_length=32,
                verbose_name="证件类型",
            ),
        ),
        migrations.AlterField(
            model_name="propertyclue",
            name="clue_type",
            field=models.CharField(
                choices=[
                    ("bank", "银行账户"),
                    ("alipay", "支付宝账户"),
                    ("wechat", "微信账户"),
                    ("real_estate", "不动产"),
                    ("other", "其他"),
                ],
                default="bank",
                max_length=16,
                verbose_name="线索类型",
            ),
        ),
    ]
