# Generated by Django 6.1.1 on 2026-10-03 06:19

from django.conf import settings
from django.db import migrations, models


def dedup_identity_doc_type(apps, schema_editor):
    """清理 (client, doc_type) 重复行，为唯一约束铺路。

    保留规则：同组内优先保留 file_path 非空的行（保住实际文件引用），
    都为空时保留最早一条。2026-10-03 dev 库实测仅 client 13 有
    2 条 business_license 且 file_path 均为 NULL，删除零数据损失。
    """
    ClientIdentityDoc = apps.get_model("client", "ClientIdentityDoc")
    rows = list(ClientIdentityDoc.objects.order_by("id").values("id", "client_id", "doc_type", "file_path"))
    kept: dict[tuple[int, str], dict] = {}
    to_delete: list[int] = []
    for row in rows:
        key = (row["client_id"], row["doc_type"])
        if key not in kept:
            kept[key] = row
            continue
        keeper = kept[key]
        if not keeper["file_path"] and row["file_path"]:
            # 已保留行丢了文件引用而当前行有 → 换保留当前行
            to_delete.append(keeper["id"])
            kept[key] = row
        else:
            to_delete.append(row["id"])
    if to_delete:
        ClientIdentityDoc.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_historicalclient_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(dedup_identity_doc_type, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='clientidentitydoc',
            constraint=models.UniqueConstraint(fields=('client', 'file_path'), name='uniq_clientidentitydoc_client_file_path'),
        ),
        migrations.AddConstraint(
            model_name='clientidentitydoc',
            constraint=models.UniqueConstraint(fields=('client', 'doc_type'), name='uniq_clientidentitydoc_client_doctype'),
        ),
        migrations.AddConstraint(
            model_name='propertyclueattachment',
            constraint=models.UniqueConstraint(fields=('property_clue', 'file_path'), name='uniq_propertyclueattachment_pc_file_path'),
        ),
    ]
