# Generated by Django 6.1.1 on 2026-10-03 08:34

from typing import Any

from django.db import migrations, models


def _normalize(apps: Any, app_label: str, model_name: str, fields: list[str]) -> None:
    """存量 NULL 归一为空字符串（双空态清理）。"""
    model = apps.get_model(app_label, model_name)
    for f in fields:
        model.objects.filter(**{f"{f}__isnull": True}).update(**{f: ""})


def normalize_null_to_empty(apps: Any, schema_editor: Any) -> None:
    # id_number 是 unique 字段：空串与存量互撞，反向归一为 NULL
    apps.get_model("client", "Client").objects.filter(id_number="").update(id_number=None)
    _normalize(apps, "client", "Client", ["phone", "address", "legal_representative", "legal_representative_id_number"])


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0012_clientidentitydoc_uniq_clientidentitydoc_client_file_path_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_null_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="住所地"),
        ),
        migrations.AlterField(
            model_name="client",
            name="legal_representative",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="法定代表人或负责人"),
        ),
        migrations.AlterField(
            model_name="client",
            name="legal_representative_id_number",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="法定代表人/负责人身份证号码"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="联系电话"),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="住所地"),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="legal_representative",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="法定代表人或负责人"),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="legal_representative_id_number",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="法定代表人/负责人身份证号码"),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="联系电话"),
        ),
    ]
