# Generated by Django 6.1.1 on 2026-10-04 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0013_alter_client_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientIdentityDocParseTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "q_task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Django-Q 任务 ID（对外仅暴露本记录 id，Q id 仅内部反查用）",
                        max_length=100,
                        verbose_name="队列任务ID",
                    ),
                ),
                ("doc_type", models.CharField(blank=True, default="", max_length=50, verbose_name="证件类型")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待处理"), ("success", "成功"), ("failed", "失败")],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_identity_doc_parse_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "证件识别任务",
                "verbose_name_plural": "证件识别任务",
                "ordering": ["-created_at"],
            },
        ),
    ]
