# Generated by Django 6.1.1 on 2026-10-04 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_clientidentitydocparsetask'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='propertyclue',
            name='idx_propclue_client',
        ),
        migrations.RemoveIndex(
            model_name='propertyclueattachment',
            name='idx_pca_propclue',
        ),
        migrations.AlterField(
            model_name='propertyclue',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_clues', to='client.client', verbose_name='当事人'),
        ),
    ]
