# Generated by Django 6.1.1 on 2026-10-04 17:40

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_remove_propertyclue_idx_propclue_client_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='client_client_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
