# Generated by Django 6.1.1 on 2026-10-04 17:40

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_remove_propertyclue_idx_propclue_client_and_more'),
    ]

    operations = [
        # gin_trgm_ops 依赖 pg_trgm 扩展（幂等）：全新测试库按 app 字母序跑迁移时，
        # 本迁移可能先于携带 TrigramExtension 的 message_hub.0014 执行
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='client',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='client_client_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
