# Generated by Django 6.1.1 on 2026-10-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_client_client_client_name_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientidentitydoc',
            name='file_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='文件路径'),
        ),
    ]
