# Generated by Django 5.2.8 on 2025-12-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Document Processor", max_length=64)),
            ],
            options={
                "verbose_name": "文档处理",
                "verbose_name_plural": "文档处理",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NamerTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Namer Tool", max_length=64)),
            ],
            options={
                "verbose_name": "自动命名工具",
                "verbose_name_plural": "自动命名工具",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TestCourt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Test Court", max_length=64)),
            ],
            options={
                "verbose_name": "测试法院系统",
                "verbose_name_plural": "测试法院系统",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CourtDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("c_sdbh", models.CharField(max_length=128, verbose_name="送达编号")),
                ("c_stbh", models.CharField(max_length=512, verbose_name="上传编号")),
                ("wjlj", models.URLField(max_length=1024, verbose_name="文件链接")),
                ("c_wsbh", models.CharField(max_length=128, verbose_name="文书编号")),
                ("c_wsmc", models.CharField(max_length=512, verbose_name="文书名称")),
                ("c_fybh", models.CharField(max_length=64, verbose_name="法院编号")),
                ("c_fymc", models.CharField(max_length=256, verbose_name="法院名称")),
                ("c_wjgs", models.CharField(max_length=32, verbose_name="文件格式")),
                ("dt_cjsj", models.DateTimeField(verbose_name="创建时间（原始）")),
                (
                    "download_status",
                    models.CharField(
                        choices=[
                            ("pending", "待下载"),
                            ("downloading", "下载中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="下载状态",
                    ),
                ),
                (
                    "local_file_path",
                    models.CharField(blank=True, max_length=1024, null=True, verbose_name="本地文件路径"),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True, verbose_name="文件大小（字节）")),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="记录创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("downloaded_at", models.DateTimeField(blank=True, null=True, verbose_name="下载完成时间")),
            ],
            options={
                "verbose_name": "法院文书",
                "verbose_name_plural": "法院文书",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourtSMS",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(verbose_name="短信内容")),
                ("received_at", models.DateTimeField(verbose_name="收到时间")),
                (
                    "sms_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("document_delivery", "文书送达"),
                            ("info_notification", "信息通知"),
                            ("filing_notification", "立案通知"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="短信类型",
                    ),
                ),
                ("download_links", models.JSONField(default=list, verbose_name="下载链接列表")),
                ("case_numbers", models.JSONField(default=list, verbose_name="案号列表")),
                ("party_names", models.JSONField(default=list, verbose_name="当事人名称列表")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("parsing", "解析中"),
                            ("downloading", "下载中"),
                            ("download_failed", "下载失败"),
                            ("matching", "匹配中"),
                            ("pending_manual", "待人工处理"),
                            ("renaming", "重命名中"),
                            ("notifying", "通知中"),
                            ("completed", "已完成"),
                            ("failed", "处理失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="处理状态",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                ("feishu_sent_at", models.DateTimeField(blank=True, null=True, verbose_name="飞书发送时间")),
                ("feishu_error", models.TextField(blank=True, null=True, verbose_name="飞书发送错误")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "法院短信",
                "verbose_name_plural": "法院短信",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="CourtToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(help_text="如：court_zxfw", max_length=128, verbose_name="网站名称")),
                ("account", models.CharField(max_length=128, verbose_name="账号")),
                ("token", models.TextField(help_text="JWT Token 或其他认证令牌", verbose_name="Token")),
                (
                    "token_type",
                    models.CharField(
                        default="Bearer", help_text="如：Bearer, JWT", max_length=32, verbose_name="Token 类型"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "Token管理",
                "verbose_name_plural": "Token管理",
            },
        ),
        migrations.CreateModel(
            name="DocumentDeliverySchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("runs_per_day", models.PositiveIntegerField(default=1, verbose_name="每天运行次数")),
                (
                    "hour_interval",
                    models.PositiveIntegerField(
                        default=24, help_text="在24小时内的运行间隔", verbose_name="运行间隔（小时）"
                    ),
                ),
                (
                    "cutoff_hours",
                    models.PositiveIntegerField(
                        default=24, help_text="只处理最近N小时内的文书", verbose_name="截止时间（小时）"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("last_run_at", models.DateTimeField(blank=True, null=True, verbose_name="上次运行时间")),
                ("next_run_at", models.DateTimeField(blank=True, null=True, verbose_name="下次运行时间")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "文书送达定时任务",
                "verbose_name_plural": "文书送达定时任务",
            },
        ),
        migrations.CreateModel(
            name="DocumentQueryHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("case_number", models.CharField(max_length=128, verbose_name="案号")),
                ("send_time", models.DateTimeField(verbose_name="文书发送时间")),
                ("queried_at", models.DateTimeField(auto_now_add=True, verbose_name="查询时间")),
            ],
            options={
                "verbose_name": "文书查询历史",
                "verbose_name_plural": "文书查询历史",
            },
        ),
        migrations.CreateModel(
            name="InsuranceQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_id", models.CharField(help_text="cId", max_length=64, verbose_name="保险公司ID")),
                ("company_code", models.CharField(help_text="cCode", max_length=64, verbose_name="保险公司编码")),
                ("company_name", models.CharField(help_text="cName", max_length=256, verbose_name="保险公司名称")),
                (
                    "premium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="保险公司给出的担保费报价（通常使用 minPremium）",
                        max_digits=15,
                        null=True,
                        verbose_name="报价金额",
                    ),
                ),
                (
                    "min_premium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="minPremium",
                        max_digits=15,
                        null=True,
                        verbose_name="最低收费1",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="minAmount",
                        max_digits=15,
                        null=True,
                        verbose_name="最低收费2",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="maxAmount",
                        max_digits=15,
                        null=True,
                        verbose_name="最高收费",
                    ),
                ),
                (
                    "min_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="minRate",
                        max_digits=10,
                        null=True,
                        verbose_name="最低费率",
                    ),
                ),
                (
                    "max_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="maxRate",
                        max_digits=10,
                        null=True,
                        verbose_name="最高费率",
                    ),
                ),
                (
                    "max_apply_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="maxApplyAmount",
                        max_digits=15,
                        null=True,
                        verbose_name="最高保全金额",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")], max_length=32, verbose_name="查询状态"
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, help_text="API 返回的完整响应数据", null=True, verbose_name="完整响应"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "保险公司报价",
                "verbose_name_plural": "保险公司报价",
                "ordering": ["min_amount"],
            },
        ),
        migrations.CreateModel(
            name="PreservationQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "preserve_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="需要保全的财产金额", max_digits=15, verbose_name="保全金额"
                    ),
                ),
                (
                    "corp_id",
                    models.CharField(
                        default="2550", help_text="法院系统中的法院标识", max_length=32, verbose_name="法院ID"
                    ),
                ),
                (
                    "category_id",
                    models.CharField(
                        default="127000", help_text="保全分类ID (cPid)", max_length=32, verbose_name="分类ID"
                    ),
                ),
                (
                    "credential_id",
                    models.IntegerField(
                        blank=True,
                        help_text="关联的账号凭证ID（可选，系统会自动获取Token）",
                        null=True,
                        verbose_name="凭证ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("partial_success", "部分成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="任务状态",
                    ),
                ),
                ("total_companies", models.IntegerField(default=0, verbose_name="保险公司总数")),
                ("success_count", models.IntegerField(default=0, verbose_name="成功查询数")),
                ("failed_count", models.IntegerField(default=0, verbose_name="失败查询数")),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
            ],
            options={
                "verbose_name": "财产保全询价",
                "verbose_name_plural": "财产保全询价",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScraperTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("court_document", "下载司法文书"),
                            ("court_filing", "自动立案"),
                            ("justice_bureau", "司法局操作"),
                            ("police", "公安局操作"),
                        ],
                        max_length=32,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "等待中"), ("running", "执行中"), ("success", "成功"), ("failed", "失败")],
                        default="pending",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=5, help_text="1-10，数字越小优先级越高", verbose_name="优先级"),
                ),
                ("url", models.URLField(verbose_name="目标URL")),
                ("config", models.JSONField(default=dict, help_text="存储账号、密码、文件路径等", verbose_name="配置")),
                ("result", models.JSONField(blank=True, null=True, verbose_name="执行结果")),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                ("max_retries", models.IntegerField(default=3, verbose_name="最大重试次数")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, help_text="留空则立即执行", null=True, verbose_name="计划执行时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "任务管理",
                "verbose_name_plural": "任务管理",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenAcquisitionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(help_text="如：court_zxfw", max_length=128, verbose_name="网站名称")),
                ("account", models.CharField(max_length=128, verbose_name="使用账号")),
                (
                    "credential_id",
                    models.IntegerField(
                        blank=True, help_text="关联的AccountCredential ID", null=True, verbose_name="凭证ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                            ("network_error", "网络错误"),
                            ("captcha_error", "验证码错误"),
                            ("credential_error", "账号密码错误"),
                        ],
                        max_length=32,
                        verbose_name="获取状态",
                    ),
                ),
                (
                    "trigger_reason",
                    models.CharField(
                        help_text="如：token_expired, no_token, manual_trigger", max_length=256, verbose_name="触发原因"
                    ),
                ),
                ("attempt_count", models.IntegerField(default=1, verbose_name="尝试次数")),
                ("total_duration", models.FloatField(blank=True, null=True, verbose_name="总耗时（秒）")),
                ("login_duration", models.FloatField(blank=True, null=True, verbose_name="登录耗时（秒）")),
                ("captcha_attempts", models.IntegerField(default=0, verbose_name="验证码尝试次数")),
                ("network_retries", models.IntegerField(default=0, verbose_name="网络重试次数")),
                (
                    "token_preview",
                    models.CharField(
                        blank=True, help_text="Token的前50个字符", max_length=50, null=True, verbose_name="Token预览"
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, help_text="包含完整的错误堆栈和上下文", null=True, verbose_name="详细错误信息"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
            ],
            options={
                "verbose_name": "Token获取历史",
                "verbose_name_plural": "Token获取历史",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuickDownloadTool",
            fields=[],
            options={
                "verbose_name": "快速下载文书",
                "verbose_name_plural": "快速下载文书",
                "managed": False,
                "proxy": True,
            },
            bases=("automation.namertool",),
        ),
    ]
