# Generated by Django 5.2.8 on 2025-12-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automation", "0001_initial"),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtdocument",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="court_documents",
                to="cases.case",
                verbose_name="关联案件",
            ),
        ),
        migrations.AddField(
            model_name="courtsms",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="court_sms_records",
                to="cases.case",
                verbose_name="关联案件",
            ),
        ),
        migrations.AddField(
            model_name="courtsms",
            name="case_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="court_sms_records",
                to="cases.caselog",
                verbose_name="案件日志",
            ),
        ),
        migrations.AddIndex(
            model_name="courttoken",
            index=models.Index(fields=["site_name", "account"], name="automation__site_na_a7e54a_idx"),
        ),
        migrations.AddIndex(
            model_name="courttoken",
            index=models.Index(fields=["expires_at"], name="automation__expires_0932b8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="courttoken",
            unique_together={("site_name", "account")},
        ),
    ]
