# Generated by Django 5.2.8 on 2025-12-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automation", "0002_initial"),
        ("cases", "0002_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentdeliveryschedule",
            name="credential",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_schedules",
                to="organization.accountcredential",
                verbose_name="账号凭证",
            ),
        ),
        migrations.AddField(
            model_name="documentqueryhistory",
            name="court_sms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="query_histories",
                to="automation.courtsms",
                verbose_name="关联短信记录",
            ),
        ),
        migrations.AddField(
            model_name="documentqueryhistory",
            name="credential",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_query_histories",
                to="organization.accountcredential",
                verbose_name="账号凭证",
            ),
        ),
        migrations.AddIndex(
            model_name="preservationquote",
            index=models.Index(fields=["status", "-created_at"], name="automation__status_52dbb3_idx"),
        ),
        migrations.AddIndex(
            model_name="preservationquote",
            index=models.Index(fields=["credential_id"], name="automation__credent_02ffc0_idx"),
        ),
        migrations.AddIndex(
            model_name="preservationquote",
            index=models.Index(fields=["created_at"], name="automation__created_b495d2_idx"),
        ),
        migrations.AddField(
            model_name="insurancequote",
            name="preservation_quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="automation.preservationquote",
                verbose_name="询价任务",
            ),
        ),
        migrations.AddField(
            model_name="scrapertask",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scraper_tasks",
                to="cases.case",
                verbose_name="关联案件",
            ),
        ),
        migrations.AddField(
            model_name="courtsms",
            name="scraper_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="court_sms_records",
                to="automation.scrapertask",
                verbose_name="下载任务",
            ),
        ),
        migrations.AddField(
            model_name="courtdocument",
            name="scraper_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="automation.scrapertask",
                verbose_name="爬虫任务",
            ),
        ),
        migrations.AddIndex(
            model_name="tokenacquisitionhistory",
            index=models.Index(fields=["site_name", "-created_at"], name="automation__site_na_26069d_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenacquisitionhistory",
            index=models.Index(fields=["account", "-created_at"], name="automation__account_c5ade7_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenacquisitionhistory",
            index=models.Index(fields=["status", "-created_at"], name="automation__status_25b8dd_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenacquisitionhistory",
            index=models.Index(fields=["credential_id"], name="automation__credent_835e13_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenacquisitionhistory",
            index=models.Index(fields=["created_at"], name="automation__created_81fc82_idx"),
        ),
        migrations.AddIndex(
            model_name="documentdeliveryschedule",
            index=models.Index(fields=["is_active", "next_run_at"], name="automation__is_acti_ebd2c4_idx"),
        ),
        migrations.AddIndex(
            model_name="documentdeliveryschedule",
            index=models.Index(fields=["credential"], name="automation__credent_eb5b93_idx"),
        ),
        migrations.AddIndex(
            model_name="documentqueryhistory",
            index=models.Index(fields=["credential", "case_number"], name="automation__credent_76d5df_idx"),
        ),
        migrations.AddIndex(
            model_name="documentqueryhistory",
            index=models.Index(fields=["send_time"], name="automation__send_ti_17ce8b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="documentqueryhistory",
            unique_together={("credential", "case_number", "send_time")},
        ),
        migrations.AddIndex(
            model_name="insurancequote",
            index=models.Index(fields=["preservation_quote", "status"], name="automation__preserv_2151c4_idx"),
        ),
        migrations.AddIndex(
            model_name="insurancequote",
            index=models.Index(fields=["company_id"], name="automation__company_fa0a40_idx"),
        ),
        migrations.AddIndex(
            model_name="insurancequote",
            index=models.Index(fields=["premium"], name="automation__premium_2be329_idx"),
        ),
        migrations.AddIndex(
            model_name="scrapertask",
            index=models.Index(fields=["status", "priority", "-created_at"], name="automation__status_381714_idx"),
        ),
        migrations.AddIndex(
            model_name="scrapertask",
            index=models.Index(fields=["task_type"], name="automation__task_ty_53ba98_idx"),
        ),
        migrations.AddIndex(
            model_name="scrapertask",
            index=models.Index(fields=["case"], name="automation__case_id_3547a7_idx"),
        ),
        migrations.AddIndex(
            model_name="scrapertask",
            index=models.Index(fields=["scheduled_at"], name="automation__schedul_080d53_idx"),
        ),
        migrations.AddIndex(
            model_name="courtsms",
            index=models.Index(fields=["status", "-received_at"], name="automation__status_30d0f7_idx"),
        ),
        migrations.AddIndex(
            model_name="courtsms",
            index=models.Index(fields=["sms_type"], name="automation__sms_typ_04630f_idx"),
        ),
        migrations.AddIndex(
            model_name="courtsms",
            index=models.Index(fields=["case"], name="automation__case_id_4acbbe_idx"),
        ),
        migrations.AddIndex(
            model_name="courtdocument",
            index=models.Index(fields=["scraper_task", "download_status"], name="automation__scraper_7a7f42_idx"),
        ),
        migrations.AddIndex(
            model_name="courtdocument",
            index=models.Index(fields=["case"], name="automation__case_id_1e84f1_idx"),
        ),
        migrations.AddIndex(
            model_name="courtdocument",
            index=models.Index(fields=["c_wsbh"], name="automation__c_wsbh_6d4b1c_idx"),
        ),
        migrations.AddIndex(
            model_name="courtdocument",
            index=models.Index(fields=["c_fymc"], name="automation__c_fymc_c87d06_idx"),
        ),
        migrations.AddIndex(
            model_name="courtdocument",
            index=models.Index(fields=["download_status"], name="automation__downloa_cf5e16_idx"),
        ),
        migrations.AddIndex(
            model_name="courtdocument",
            index=models.Index(fields=["created_at"], name="automation__created_b4f148_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="courtdocument",
            unique_together={("c_wsbh", "c_sdbh")},
        ),
    ]
