# Generated by Django 5.2.8 on 2025-12-25 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_initial"),
        ("cases", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRecognitionProxy",
            fields=[],
            options={
                "verbose_name": "文书智能识别",
                "verbose_name_plural": "文书智能识别",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("automation.courtsms",),
        ),
        migrations.CreateModel(
            name="DocumentRecognitionTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.CharField(max_length=1024, verbose_name="文件路径")),
                ("original_filename", models.CharField(max_length=256, verbose_name="原始文件名")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "识别中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="任务状态",
                    ),
                ),
                ("document_type", models.CharField(blank=True, max_length=32, null=True, verbose_name="文书类型")),
                ("case_number", models.CharField(blank=True, max_length=128, null=True, verbose_name="案号")),
                ("key_time", models.DateTimeField(blank=True, null=True, verbose_name="关键时间")),
                ("confidence", models.FloatField(blank=True, null=True, verbose_name="置信度")),
                ("extraction_method", models.CharField(blank=True, max_length=32, null=True, verbose_name="提取方式")),
                ("raw_text", models.TextField(blank=True, null=True, verbose_name="原始文本")),
                (
                    "renamed_file_path",
                    models.CharField(blank=True, max_length=1024, null=True, verbose_name="重命名后路径"),
                ),
                ("binding_success", models.BooleanField(null=True, verbose_name="绑定成功")),
                ("binding_message", models.CharField(blank=True, max_length=512, null=True, verbose_name="绑定消息")),
                (
                    "binding_error_code",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="绑定错误码"),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recognition_tasks",
                        to="cases.case",
                        verbose_name="关联案件",
                    ),
                ),
                (
                    "case_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recognition_tasks",
                        to="cases.caselog",
                        verbose_name="案件日志",
                    ),
                ),
            ],
            options={
                "verbose_name": "文书识别任务",
                "verbose_name_plural": "文书识别任务",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="automation__status_b57405_idx"),
                    models.Index(fields=["case"], name="automation__case_id_13ae57_idx"),
                ],
            },
        ),
    ]
