# Generated by Django 6.0.1 on 2026-02-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courttoken',
            name='token',
            field=models.TextField(help_text='JWT Token 或其他认证令牌', verbose_name='Token'),
        ),
    ]
