# Generated by Django 6.0.1 on 2026-02-23 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0004_courttoken_plaintext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceRecognitionTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="任务名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="任务状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_recognition_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "发票识别任务",
                "verbose_name_plural": "发票识别任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.CharField(max_length=1024, verbose_name="文件路径")),
                ("original_filename", models.CharField(max_length=255, verbose_name="原始文件名")),
                ("invoice_code", models.CharField(blank=True, default="", max_length=50, verbose_name="发票代码")),
                ("invoice_number", models.CharField(blank=True, default="", max_length=50, verbose_name="发票号码")),
                ("invoice_date", models.DateField(blank=True, null=True, verbose_name="开票日期")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="金额（不含税）"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="税额"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="价税合计"
                    ),
                ),
                ("buyer_name", models.CharField(blank=True, default="", max_length=255, verbose_name="购买方名称")),
                ("seller_name", models.CharField(blank=True, default="", max_length=255, verbose_name="销售方名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vat_special", "增值税专用发票"),
                            ("vat_normal", "增值税普通发票"),
                            ("vat_electronic", "增值税电子普通发票"),
                            ("vehicle_sales", "机动车销售统一发票"),
                            ("train_ticket", "火车票"),
                            ("taxi_receipt", "出租车发票"),
                            ("quota_invoice", "定额发票"),
                            ("air_itinerary", "飞机行程单"),
                            ("toll_receipt", "过路费发票"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="发票类目",
                    ),
                ),
                ("raw_text", models.TextField(blank=True, default="", verbose_name="OCR 原始文本")),
                ("is_duplicate", models.BooleanField(default=False, verbose_name="是否重复")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待识别"), ("success", "识别成功"), ("failed", "识别失败")],
                        default="pending",
                        max_length=32,
                        verbose_name="识别状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="automation.invoicerecognitiontask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "发票记录",
                "verbose_name_plural": "发票记录",
            },
        ),
        migrations.AddIndex(
            model_name="invoicerecognitiontask",
            index=models.Index(fields=["status", "-created_at"], name="automation__status_806e2d_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicerecord",
            index=models.Index(fields=["invoice_code", "invoice_number"], name="automation__invoice_7bceb1_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicerecord",
            index=models.Index(fields=["task", "category"], name="automation__task_id_71663a_idx"),
        ),
    ]
