# Generated by Django 5.2.8 on 2025-12-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0004_add_document_recognition_task"),
        ("cases", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrecognitiontask",
            name="notification_error",
            field=models.TextField(blank=True, null=True, verbose_name="通知错误信息"),
        ),
        migrations.AddField(
            model_name="documentrecognitiontask",
            name="notification_file_sent",
            field=models.BooleanField(default=False, verbose_name="文件已发送"),
        ),
        migrations.AddField(
            model_name="documentrecognitiontask",
            name="notification_sent",
            field=models.BooleanField(default=False, verbose_name="通知已发送"),
        ),
        migrations.AddField(
            model_name="documentrecognitiontask",
            name="notification_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="通知发送时间"),
        ),
        migrations.AddIndex(
            model_name="documentrecognitiontask",
            index=models.Index(fields=["notification_sent"], name="automation__notific_6b9b00_idx"),
        ),
    ]
