# Generated by Django 6.0.1 on 2026-02-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_invoicerecognitiontask_invoicerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='项目名称'),
        ),
    ]
