# Generated by Django 6.0.1 on 2026-02-10 08:15

from typing import Any

from django.db import migrations


class Migration(migrations.Migration):

    dependencies: list[Any] = [
        ("automation", "0004_token_history_scrub_and_fingerprint"),
        ("automation", "0005_add_notification_fields_to_recognition_task"),
    ]

    operations: list[Any] = []
