# Generated by Django 6.0.1 on 2026-02-11 13:25

from typing import Any

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: list[Any] = [
        ("automation", "0006_merge_20260210_1615"),
    ]

    operations: list[Any] = [
        migrations.CreateModel(
            name="FeeNoticeTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Fee Notice Test", max_length=64)),
            ],
            options={
                "verbose_name": "交费通知书识别",
                "verbose_name_plural": "交费通知书识别",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ImageRotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Image Rotation", max_length=64)),
            ],
            options={
                "verbose_name": "图片自动旋转",
                "verbose_name_plural": "图片自动旋转",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PreservationDateTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Preservation Date Test", max_length=64)),
            ],
            options={
                "verbose_name": "财产保全日期识别",
                "verbose_name_plural": "财产保全日期识别",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TestToolsHub",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Test Tools Hub", max_length=64)),
            ],
            options={
                "verbose_name": "测试工具",
                "verbose_name_plural": "测试工具",
                "managed": False,
            },
        ),
    ]
