# Generated by Django 6.0.1 on 2026-02-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_add_project_name_to_invoice_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecognitiontask',
            name='merge_config',
            field=models.JSONField(blank=True, default=list, verbose_name='分组合并配置'),
        ),
    ]
