# Generated by Django 6.0.1 on 2026-02-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_add_merge_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='duplicate_of_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='重复的原始记录ID'),
        ),
    ]
