# Generated by Django 6.1.1 on 2026-10-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_remove_documentdeliveryschedule_automation__is_acti_ebd2c4_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickDownloadTool',
        ),
    ]
