# Generated by Django 6.1.1 on 2026-10-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0020_delete_quickdownloadtool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtdocument',
            name='local_file_path',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='本地文件路径'),
        ),
        migrations.AlterField(
            model_name='insurancequote',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
    ]
