# Generated by Django 6.1.1 on 2026-10-03 10:35

from typing import Any

from django.db import migrations, models, transaction


def _normalize(apps: Any, app_label: str, model_name: str, fields: list[str]) -> None:
    """存量 NULL 归一为空字符串（双空态清理）。"""
    model = apps.get_model(app_label, model_name)
    for f in fields:
        model.objects.filter(**{f"{f}__isnull": True}).update(**{f: ""})


def normalize_null_to_empty(apps: Any, schema_editor: Any) -> None:
    with transaction.atomic():
        _normalize(apps, "automation", "CourtDocument", ["error_message"])
        _normalize(apps, "automation", "CourtSMS", ["sms_type", "error_message", "feishu_error"])
        _normalize(apps, "automation", "PreservationQuote", ["error_message"])
        _normalize(apps, "automation", "ScraperTask", ["error_message", "captcha_image_path", "captcha_answer"])
        _normalize(
            apps,
            "automation",
            "TokenAcquisitionHistory",
            ["token_preview", "token_fingerprint", "token_redacted", "error_message"],
        )


class Migration(migrations.Migration):
    # UPDATE 后同事务内 ALTER 可能撞上 DEFERRABLE 外键的 pending trigger 事件
    # （PG 限制，contacts 0002 先例），数据步自包事务先提交。
    atomic = False

    dependencies = [
        ('automation', '0021_alter_courtdocument_local_file_path_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_null_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='courtdocument',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='courtsms',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='courtsms',
            name='feishu_error',
            field=models.TextField(blank=True, default='', verbose_name='飞书发送错误'),
        ),
        migrations.AlterField(
            model_name='courtsms',
            name='sms_type',
            field=models.CharField(blank=True, choices=[('document_delivery', '文书送达'), ('info_notification', '信息通知'), ('filing_notification', '立案通知')], default='', max_length=32, verbose_name='短信类型'),
        ),
        migrations.AlterField(
            model_name='preservationquote',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='scrapertask',
            name='captcha_answer',
            field=models.CharField(blank=True, default='', help_text='用户手动输入的验证码答案', max_length=64, verbose_name='验证码答案'),
        ),
        migrations.AlterField(
            model_name='scrapertask',
            name='captcha_image_path',
            field=models.CharField(blank=True, default='', help_text='手动验证码模式下存储待识别图片路径', max_length=500, verbose_name='验证码图片路径'),
        ),
        migrations.AlterField(
            model_name='scrapertask',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='tokenacquisitionhistory',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='tokenacquisitionhistory',
            name='token_fingerprint',
            field=models.CharField(blank=True, default='', help_text='Token的SHA256指纹(用于排查重复/归因,不可反推Token)', max_length=64, verbose_name='Token指纹'),
        ),
        migrations.AlterField(
            model_name='tokenacquisitionhistory',
            name='token_preview',
            field=models.CharField(blank=True, default='', help_text='Token 前50个字符', max_length=50, verbose_name='Token预览'),
        ),
        migrations.AlterField(
            model_name='tokenacquisitionhistory',
            name='token_redacted',
            field=models.CharField(blank=True, default='', help_text='脱敏后的Token摘要(仅用于人工排查)', max_length=32, verbose_name='Token脱敏摘要'),
        ),
    ]
