# Generated by Django 6.1.1 on 2026-10-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0023_alter_gsxtreporttask_report_file'),
        ('cases', '0037_alter_casetemplatebinding_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courtdocument',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='courttoken',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='courtdocument',
            constraint=models.UniqueConstraint(fields=('c_wsbh', 'c_sdbh'), name='uniq_courtdocument_c_wsbh_c_sdbh'),
        ),
        migrations.AddConstraint(
            model_name='courttoken',
            constraint=models.UniqueConstraint(fields=('site_name', 'account'), name='uniq_courttoken_site_account'),
        ),
    ]
