# Generated by Django 6.1.1 on 2026-10-04 08:18

from typing import Any

from django.db import migrations, models, transaction


def clamp_scraper_task_priority(apps: Any, schema_editor: Any) -> None:
    """钳制存量越界 priority 入 [1, 10]，保证 AddConstraint 可执行。"""
    task = apps.get_model("automation", "ScraperTask")
    with transaction.atomic():
        task.objects.filter(priority__gt=10).update(priority=10)
        task.objects.filter(priority__lt=1).update(priority=1)


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0025_alter_gsxtreporttask_client'),
        ('cases', '0039_remove_casetemplatebinding_cases_caset_templat_8dfc20_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='casepreservationquotebinding',
            name='automation__preserv_9ba9c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='courtdocument',
            name='automation__case_id_1e84f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='courtsms',
            name='automation__case_id_4acbbe_idx',
        ),
        migrations.RemoveIndex(
            model_name='courttoken',
            name='automation__site_na_a7e54a_idx',
        ),
        migrations.RemoveIndex(
            model_name='scrapertask',
            name='automation__case_id_3547a7_idx',
        ),
        migrations.AlterField(
            model_name='scrapertask',
            name='config',
            field=models.JSONField(default=dict, help_text='存储任务配置参数、文件路径等', verbose_name='配置'),
        ),
        migrations.RunPython(clamp_scraper_task_priority, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='scrapertask',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 10)), name='chk_scraper_task_priority_range'),
        ),
    ]
