# Generated by Django 6.1.1 on 2026-10-04 17:01
# 安全审计第4轮：CourtToken.token 由明文 TextField 改为 EncryptedTextField，
# 并附带 RunPython 把存量明文 Token 就地加密（幂等：已加密的 enc:v1: 行跳过）。

import apps.core.model_fields.encrypted
from apps.core.model_fields.encrypted import EncryptedTextField
from django.db import connections, migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def encrypt_existing_tokens(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """存量明文 token 就地加密。

    - 读取走裸 SQL 游标：values_list / 模型读取都会触发 from_db_value 解密，
      若存量密文因密钥轮换缺失而解密失败，会让迁移直接崩掉；
    - 先用 EncryptedTextField.get_prep_value 预加密，再 queryset.update 落库
      （update 会再走一遍 get_prep_value，密文带 enc:v1: 前缀会被原样放行，
      不会双重加密）。
    """
    CourtToken = apps.get_model("automation", "CourtToken")
    field = EncryptedTextField()
    table = CourtToken._meta.db_table
    alias = schema_editor.connection.alias
    with connections[alias].cursor() as cursor:
        cursor.execute(f"SELECT id, token FROM {table}")
        rows = cursor.fetchall()
    for token_id, raw in rows:
        if not raw or raw.startswith(field.prefix):
            continue
        CourtToken.objects.filter(id=token_id).update(token=field.get_prep_value(raw))


def noop_reverse(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """回滚不安全（解密回明文），反向保持现状由 AlterField 自然回退类型。"""
    # 故意留空：反向迁移仅回退字段类型，不回写明文
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0026_remove_casepreservationquotebinding_automation__preserv_9ba9c7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courttoken',
            name='token',
            field=apps.core.model_fields.encrypted.EncryptedTextField(help_text='一张网/保全系统返回的 JWT Token 或其他认证令牌', verbose_name='认证Token'),
        ),
        migrations.RunPython(encrypt_existing_tokens, noop_reverse),
    ]
