# Generated by Django 6.1.1 on 2026-10-04 18:25

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0027_alter_courttoken_token'),
        ('cases', '0040_case_cases_case_name_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='courtsms',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='courtsms_content_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
