# Generated by Django 6.1.1 on 2026-10-04 18:25

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0027_alter_courttoken_token'),
        ('cases', '0040_case_cases_case_name_trgm'),
    ]

    operations = [
        # gin_trgm_ops 依赖 pg_trgm 扩展（幂等）：全新测试库按 app 字母序跑迁移时，
        # 本迁移可能先于携带 TrigramExtension 的 message_hub.0014 执行
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='courtsms',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='courtsms_content_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
