# Generated by Django 6.0.1 on 2026-01-22 16:40

import apps.organization.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_lawyer_license_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='license_pdf',
            field=models.FileField(blank=True, null=True, storage=apps.organization.models.KeepOriginalNameStorage(), upload_to=apps.organization.models.lawyer_license_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='执业证文件'),
        ),
    ]
