# Generated by Django 6.0.1 on 2026-02-07 00:00

import base64

from cryptography.fernet import Fernet, InvalidToken
from django.conf import settings
from django.db import migrations

from apps.core.model_fields.encrypted import EncryptedTextField

PREFIX = "enc:v1:"


def _get_key() -> bytes | None:
    key = getattr(settings, "CREDENTIAL_ENCRYPTION_KEY", None) or getattr(settings, "SCRAPER_ENCRYPTION_KEY", None)
    if not key:
        return None
    if isinstance(key, str):
        return key.encode()
    return key


def _encrypt_passwords(apps, schema_editor) -> None:
    key = _get_key()
    if not key:
        return
    cipher = Fernet(key)
    table_name = "organization_accountcredential"

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT id, password FROM {table_name}")
        rows = cursor.fetchall()
        for credential_id, password in rows:
            if not password:
                continue
            if isinstance(password, bytes):
                password = password.decode()
            if str(password).startswith(PREFIX):
                continue
            token = cipher.encrypt(str(password).encode())
            encrypted_value = f"{PREFIX}{base64.urlsafe_b64encode(token).decode()}"
            cursor.execute(
                f"UPDATE {table_name} SET password = %s WHERE id = %s",
                [encrypted_value, credential_id],
            )


def _decrypt_passwords(apps, schema_editor) -> None:
    key = _get_key()
    if not key:
        return
    cipher = Fernet(key)
    table_name = "organization_accountcredential"

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT id, password FROM {table_name}")
        rows = cursor.fetchall()
        for credential_id, password in rows:
            if not password:
                continue
            if isinstance(password, bytes):
                password = password.decode()
            password = str(password)
            if not password.startswith(PREFIX):
                continue
            token_b64 = password[len(PREFIX) :]
            try:
                token = base64.urlsafe_b64decode(token_b64.encode())
                plain = cipher.decrypt(token).decode()
            except (InvalidToken, ValueError):
                continue
            cursor.execute(
                f"UPDATE {table_name} SET password = %s WHERE id = %s",
                [plain, credential_id],
            )


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_alter_lawyer_license_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountcredential",
            name="password",
            field=EncryptedTextField(verbose_name="密码"),
        ),
        migrations.RunPython(_encrypt_passwords, _decrypt_passwords),
    ]
