# Generated by Django 6.0.1 on 2026-02-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_encrypt_accountcredential_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lawfirm",
            options={"verbose_name": "律所", "verbose_name_plural": "律所"},
        ),
        migrations.AlterModelOptions(
            name="lawyer",
            options={"verbose_name": "律师", "verbose_name_plural": "律师"},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "团队", "verbose_name_plural": "团队"},
        ),
        migrations.AlterField(
            model_name="accountcredential",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="accountcredential",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="lawfirm",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="地址"),
        ),
        migrations.AlterField(
            model_name="lawfirm",
            name="name",
            field=models.CharField(max_length=255, verbose_name="律所名称"),
        ),
        migrations.AlterField(
            model_name="lawfirm",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="联系电话"),
        ),
        migrations.AlterField(
            model_name="lawfirm",
            name="social_credit_code",
            field=models.CharField(blank=True, max_length=18, verbose_name="统一社会信用代码"),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="biz_teams",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"team_type": "biz"},
                related_name="biz_members",
                to="organization.team",
                verbose_name="所属业务团队",
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="id_card",
            field=models.CharField(blank=True, max_length=32, verbose_name="身份证号"),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="是否律所管理员"),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="law_firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lawyers",
                to="organization.lawfirm",
                verbose_name="所属律所",
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="lawyer_teams",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"team_type": "lawyer"},
                related_name="lawyers",
                to="organization.team",
                verbose_name="所属律师团队",
            ),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="license_no",
            field=models.CharField(blank=True, max_length=64, verbose_name="执业证号"),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="手机号码"),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="real_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="真实姓名"),
        ),
        migrations.AlterField(
            model_name="team",
            name="law_firm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="organization.lawfirm",
                verbose_name="所属律所",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=255, verbose_name="团队名称"),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_type",
            field=models.CharField(
                choices=[("lawyer", "律师团队"), ("biz", "业务团队")], max_length=16, verbose_name="团队类型"
            ),
        ),
    ]
