# Generated by Django 6.1.1 on 2026-10-03 10:39

import apps.core.filesystem.storage
import apps.core.filesystem.upload_paths
import django.core.validators
from typing import Any

from django.db import migrations, models, transaction


def _normalize(apps: Any, app_label: str, model_name: str, fields: list[str]) -> None:
    """存量 NULL 归一为空字符串（双空态清理）。"""
    model = apps.get_model(app_label, model_name)
    for f in fields:
        model.objects.filter(**{f"{f}__isnull": True}).update(**{f: ""})


def normalize_null_to_empty(apps: Any, schema_editor: Any) -> None:
    with transaction.atomic():
        _normalize(apps, "organization", "Lawyer", ['license_pdf', 'avatar'])


class Migration(migrations.Migration):
    # UPDATE 后同事务内 ALTER 可能撞上 DEFERRABLE 外键的 pending trigger 事件
    # （PG 限制，contacts 0002 先例），数据步自包事务先提交。
    atomic = False

    dependencies = [
        ('organization', '0009_alter_lawyer_real_name'),
    ]

    operations = [
        migrations.RunPython(normalize_null_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='lawyer',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('avatars'), verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='license_pdf',
            field=models.FileField(blank=True, default='', storage=apps.core.filesystem.storage.KeepOriginalNameStorage(), upload_to=apps.core.filesystem.upload_paths.DatedOriginalPath('lawyers/licenses'), validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='执业证文件'),
        ),
    ]
