# Generated by Django 6.1.1 on 2026-10-04 08:18

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from django.db import migrations, models, transaction

# 哨兵时间（UTC 感知，USE_TZ 下与库中返回的 aware datetime 可比较）
_DATETIME_MIN = datetime.min.replace(tzinfo=UTC)


def _repoint_inbound_fks(apps: Any, model: Any, dup_id: int, keeper_id: int) -> None:
    """把指向重复凭证的其他模型外键改指到保留行，避免 PROTECT 阻断删除。"""
    for other in apps.get_models():
        if other._meta.app_label == "organization" and other.__name__ == model.__name__:
            continue
        for field in other._meta.fields:
            is_fk = isinstance(field, models.ForeignKey)
            is_o2o = isinstance(field, models.OneToOneField)
            if not is_fk or field.related_model is not model or is_o2o:
                continue
            other.objects.filter(**{f"{field.name}_id": dup_id}).update(**{f"{field.name}_id": keeper_id})


def dedupe_account_credentials(apps: Any, schema_editor: Any) -> None:
    """按 (lawyer, site_name, account) 去重。

    保留 last_login_success_at 最新者，其次 id 最大者；删除其余重复行前，
    先把入站外键引用改指保留行，避免 PROTECT（如 legal_research 任务）阻断。
    """
    credential = apps.get_model("organization", "AccountCredential")
    rows = list(credential.objects.values("id", "lawyer_id", "site_name", "account", "last_login_success_at"))
    groups: dict[tuple, list[dict]] = {}
    for row in rows:
        groups.setdefault((row["lawyer_id"], row["site_name"], row["account"]), []).append(row)

    with transaction.atomic():
        for members in groups.values():
            if len(members) < 2:
                continue
            # 纯 Python 侧比较：NULL 视为最早，避免 PG/psycopg 对 year-1
            # 时间戳的时区换算溢出
            keeper = max(members, key=lambda r: (r["last_login_success_at"] or _DATETIME_MIN, r["id"]))
            for row in members:
                if row["id"] == keeper["id"]:
                    continue
                _repoint_inbound_fks(apps, credential, row["id"], keeper["id"])
                credential.objects.filter(id=row["id"]).delete()


def _repoint_team_memberships(apps: Any, team: Any, dup_id: int, keeper_id: int) -> None:
    """把指向重复团队的成员关系迁到保留行（补插缺失的 through 行）。"""
    lawyer = apps.get_model("organization", "Lawyer")
    for field in lawyer._meta.many_to_many:
        if field.related_model is not team:
            continue
        through = field.remote_field.through
        team_fk = next(
            f for f in through._meta.fields
            if isinstance(f, models.ForeignKey) and f.related_model is team
        )
        lawyer_fk = next(
            f for f in through._meta.fields
            if isinstance(f, models.ForeignKey) and f.related_model is lawyer
        )
        dup_rows = through.objects.filter(**{team_fk.name: dup_id}).values_list(lawyer_fk.name, flat=True)
        for lawyer_id in dup_rows:
            # 用 *_id 形式的 kwargs：字段名形式会把 int 赋给 FK 描述符而报错
            through.objects.get_or_create(
                **{f"{lawyer_fk.name}_id": lawyer_id, f"{team_fk.name}_id": keeper_id}
            )


def dedupe_teams(apps: Any, schema_editor: Any) -> None:
    """按 (law_firm, team_type, name) 去重，保留 id 最小者。

    删除重复行前，先把指向重复团队的 M2M 成员关系补插到保留行，
    保证律师团队成员归属不丢（重复行删除时旧 through 行随 CASCADE 消失）。
    """
    team = apps.get_model("organization", "Team")
    rows = list(team.objects.values("id", "law_firm_id", "team_type", "name"))
    groups: dict[tuple, list[dict]] = {}
    for row in rows:
        groups.setdefault((row["law_firm_id"], row["team_type"], row["name"]), []).append(row)

    with transaction.atomic():
        for members in groups.values():
            if len(members) < 2:
                continue
            keeper = min(members, key=lambda r: r["id"])
            for row in members:
                if row["id"] == keeper["id"]:
                    continue
                _repoint_team_memberships(apps, team, row["id"], keeper["id"])
                team.objects.filter(id=row["id"]).delete()


class Migration(migrations.Migration):
    # 去重的 UPDATE 会触碰外键列，产生 DEFERRABLE INITIALLY DEFERRED 的延迟
    # 触发器事件，会挡住同事务内后续 AddConstraint 的 ALTER TABLE（PG 限制，
    # 同 contracts/0041 的处理方式）。数据步各自包在 transaction.atomic 里
    # 先提交，约束 DDL 在干净的事务里执行。
    atomic = False

    dependencies = [
        ('organization', '0010_alter_lawyer_avatar_alter_lawyer_license_pdf'),
    ]

    operations = [
        migrations.RunPython(dedupe_account_credentials, migrations.RunPython.noop),
        migrations.RunPython(dedupe_teams, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='accountcredential',
            constraint=models.UniqueConstraint(fields=('lawyer', 'site_name', 'account'), name='uniq_credential_lawyer_site_account'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('law_firm', 'team_type', 'name'), name='uniq_team_firm_type_name'),
        ),
    ]
