# Generated by Django 5.2.8 on 2026-01-19 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0003_initial"),
        ("contracts", "0002_initial"),
        ("documents", "0001_initial"),
        ("litigation_ai", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencelist",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_evidence_lists",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="evidencelist",
            name="export_template",
            field=models.ForeignKey(
                blank=True,
                help_text="选择用于导出证据清单的 Word 模板",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidence_lists",
                to="documents.documenttemplate",
                verbose_name="导出模板",
            ),
        ),
        migrations.AddField(
            model_name="evidencelist",
            name="previous_list",
            field=models.ForeignKey(
                blank=True,
                help_text="关联前一个清单,用于自动计算起始序号和页码",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_lists",
                to="documents.evidencelist",
                verbose_name="前置清单",
            ),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="evidence_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="documents.evidencelist",
                verbose_name="证据清单",
            ),
        ),
        migrations.AddIndex(
            model_name="foldertemplate",
            index=models.Index(fields=["is_active"], name="documents_f_is_acti_2adc8f_idx"),
        ),
        migrations.AddIndex(
            model_name="foldertemplate",
            index=models.Index(fields=["is_default"], name="documents_f_is_defa_b3de03_idx"),
        ),
        migrations.AddField(
            model_name="documenttemplatefolderbinding",
            name="folder_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_bindings",
                to="documents.foldertemplate",
                verbose_name="文件夹模板",
            ),
        ),
        migrations.AddIndex(
            model_name="generationconfig",
            index=models.Index(fields=["config_type"], name="documents_g_config__3367d5_idx"),
        ),
        migrations.AddIndex(
            model_name="generationconfig",
            index=models.Index(fields=["is_active"], name="documents_g_is_acti_f62582_idx"),
        ),
        migrations.AddField(
            model_name="generationtask",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_tasks",
                to="cases.case",
                verbose_name="关联案件",
            ),
        ),
        migrations.AddField(
            model_name="generationtask",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_tasks",
                to="contracts.contract",
                verbose_name="关联合同",
            ),
        ),
        migrations.AddField(
            model_name="generationtask",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_generation_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="generationtask",
            name="litigation_session",
            field=models.ForeignKey(
                blank=True,
                help_text="如果是 AI 生成,关联到对应的会话",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_tasks",
                to="litigation_ai.litigationsession",
                verbose_name="AI生成会话",
            ),
        ),
        migrations.AddIndex(
            model_name="placeholder",
            index=models.Index(fields=["is_active"], name="documents_p_is_acti_861641_idx"),
        ),
        migrations.AddIndex(
            model_name="promptversion",
            index=models.Index(fields=["name", "is_active"], name="documents_p_name_55877d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="promptversion",
            unique_together={("name", "version")},
        ),
        migrations.AddField(
            model_name="templateauditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencelist",
            index=models.Index(fields=["case", "order"], name="documents_e_case_id_0cb748_idx"),
        ),
        migrations.AddIndex(
            model_name="evidencelist",
            index=models.Index(fields=["case", "list_type"], name="documents_e_case_id_9ff9d0_idx"),
        ),
        migrations.AddIndex(
            model_name="evidencelist",
            index=models.Index(fields=["created_by"], name="documents_e_created_4a285c_idx"),
        ),
        migrations.AddConstraint(
            model_name="evidencelist",
            constraint=models.UniqueConstraint(fields=("case", "list_type"), name="unique_case_list_type"),
        ),
        migrations.AddIndex(
            model_name="evidenceitem",
            index=models.Index(fields=["evidence_list", "order"], name="documents_e_evidenc_9a8ef6_idx"),
        ),
        migrations.AddIndex(
            model_name="documenttemplatefolderbinding",
            index=models.Index(fields=["folder_template", "folder_node_id"], name="documents_d_folder__69fc0d_idx"),
        ),
        migrations.AddIndex(
            model_name="documenttemplatefolderbinding",
            index=models.Index(fields=["document_template"], name="documents_d_documen_3e722a_idx"),
        ),
        migrations.AddIndex(
            model_name="documenttemplatefolderbinding",
            index=models.Index(fields=["is_active"], name="documents_d_is_acti_19e591_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="documenttemplatefolderbinding",
            unique_together={("document_template", "folder_template", "folder_node_id")},
        ),
        migrations.AddIndex(
            model_name="generationtask",
            index=models.Index(fields=["case", "-created_at"], name="documents_g_case_id_57bb8e_idx"),
        ),
        migrations.AddIndex(
            model_name="generationtask",
            index=models.Index(fields=["contract", "-created_at"], name="documents_g_contrac_3b54f8_idx"),
        ),
        migrations.AddIndex(
            model_name="generationtask",
            index=models.Index(fields=["litigation_session"], name="documents_g_litigat_ee5b82_idx"),
        ),
        migrations.AddIndex(
            model_name="generationtask",
            index=models.Index(fields=["status"], name="documents_g_status_3fd33e_idx"),
        ),
        migrations.AddIndex(
            model_name="generationtask",
            index=models.Index(fields=["generation_method"], name="documents_g_generat_96ab0e_idx"),
        ),
        migrations.AddIndex(
            model_name="generationtask",
            index=models.Index(fields=["created_by", "-created_at"], name="documents_g_created_afe336_idx"),
        ),
        migrations.AddIndex(
            model_name="templateauditlog",
            index=models.Index(fields=["content_type", "object_id"], name="documents_t_content_b119bb_idx"),
        ),
        migrations.AddIndex(
            model_name="templateauditlog",
            index=models.Index(fields=["action"], name="documents_t_action_1e19ee_idx"),
        ),
        migrations.AddIndex(
            model_name="templateauditlog",
            index=models.Index(fields=["user"], name="documents_t_user_id_177e24_idx"),
        ),
        migrations.AddIndex(
            model_name="templateauditlog",
            index=models.Index(fields=["-created_at"], name="documents_t_created_033a55_idx"),
        ),
    ]
