# Generated by Django 6.0.1 on 2026-02-23 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_initial'),
        ('core', '0003_add_court_timestamps'),
        ('documents', '0002_initial'),
        ('organization', '0002_password_plaintext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('category', models.CharField(choices=[('property_declaration', '财产申报表'), ('service_address', '送达地址确认书'), ('creditor_declaration', '债权申报表'), ('element_complaint', '要素式诉状'), ('power_of_attorney', '授权委托书'), ('legal_aid', '法律援助申请表'), ('preservation_application', '财产保全申请书'), ('other', '其他')], max_length=50, verbose_name='模板类别')),
                ('source_type', models.CharField(choices=[('court', '法院'), ('administrator', '破产管理人'), ('arbitration', '仲裁委员会'), ('administrative', '行政机关'), ('other', '其他')], max_length=20, verbose_name='来源类型')),
                ('organization_name', models.CharField(blank=True, default='', help_text='破产管理人、仲裁委员会等机构名称', max_length=255, verbose_name='机构名称')),
                ('file_path', models.CharField(help_text='相对于 MEDIA_ROOT 的存储路径', max_length=500, verbose_name='文件路径')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小(字节)')),
                ('structure_fingerprint', models.CharField(blank=True, db_index=True, default='', help_text='基于模板 XML 结构计算的 SHA-256 哈希值', max_length=64, verbose_name='结构指纹')),
                ('structure_json', models.JSONField(blank=True, default=dict, verbose_name='提取的结构JSON')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('analyzing', '分析中'), ('analysis_failed', '分析失败'), ('mapped', '已映射'), ('confirmed', '已确认')], default='uploaded', max_length=20, verbose_name='状态')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('status_changed_at', models.DateTimeField(auto_now=True, verbose_name='状态变更时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('court', models.ForeignKey(blank=True, help_text='来源类型为法院时关联的法院', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.court', verbose_name='关联法院')),
                ('law_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_templates', to='organization.lawfirm', verbose_name='所属律所')),
                ('mapping_source', models.ForeignKey(blank=True, help_text='结构指纹匹配时复用映射的原始模板', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.externaltemplate', verbose_name='映射来源模板')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_external_templates', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '外部模板',
                'verbose_name_plural': '外部模板',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchFillTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('zip_file_path', models.CharField(blank=True, default='', help_text='批量填充生成的 ZIP 压缩包路径', max_length=500, verbose_name='ZIP文件路径')),
                ('summary_json', models.JSONField(blank=True, default=dict, help_text='批量填充的汇总报告 JSON', verbose_name='汇总报告')),
                ('case', models.ForeignKey(help_text='批量填充关联的案件', on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='关联案件')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_batch_fill_tasks', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('templates', models.ManyToManyField(help_text='本次批量填充选择的外部模板', to='documents.externaltemplate', verbose_name='选择的模板')),
            ],
            options={
                'verbose_name': '批量填充任务',
                'verbose_name_plural': '批量填充任务',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalTemplateFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_locator', models.JSONField(verbose_name='位置定位器')),
                ('position_description', models.CharField(blank=True, default='', max_length=500, verbose_name='位置描述')),
                ('semantic_label', models.CharField(max_length=255, verbose_name='语义标签')),
                ('placeholder_key', models.CharField(blank=True, default='', max_length=100, verbose_name='占位符键')),
                ('fill_type', models.CharField(choices=[('text', '文本替换'), ('checkbox', '勾选复选框'), ('delete_inapplicable', '删除不适用项')], default='text', max_length=30, verbose_name='填充类型')),
                ('options', models.JSONField(blank=True, default=list, help_text='delete_inapplicable 类型的可选项', verbose_name='选项列表')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='是否已确认')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='documents.externaltemplate', verbose_name='关联模板')),
            ],
            options={
                'verbose_name': '字段映射',
                'verbose_name_plural': '字段映射',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_at', models.DateTimeField(auto_now_add=True, verbose_name='填充时间')),
                ('file_path', models.CharField(help_text='填充生成的文件相对于 MEDIA_ROOT 的路径', max_length=500, verbose_name='生成文件路径')),
                ('original_output_name', models.CharField(help_text='填充生成的文件原始名称', max_length=255, verbose_name='输出文件名')),
                ('report_json', models.JSONField(blank=True, default=dict, help_text='填充操作的详细报告 JSON', verbose_name='填充报告')),
                ('custom_values', models.JSONField(blank=True, default=dict, help_text='用户手动输入的自定义字段值', verbose_name='自定义填充值')),
                ('file_available', models.BooleanField(default=True, help_text='生成的文件是否仍然可访问', verbose_name='文件是否可用')),
                ('batch_task', models.ForeignKey(blank=True, help_text='所属的批量填充任务, 单次填充时为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='documents.batchfilltask', verbose_name='批量任务')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='关联案件')),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fill_records', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.caseparty', verbose_name='关联当事人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.externaltemplate', verbose_name='关联模板')),
            ],
            options={
                'verbose_name': '填充记录',
                'verbose_name_plural': '填充记录',
                'ordering': ['-filled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='externaltemplate',
            index=models.Index(fields=['law_firm', 'court', 'category'], name='documents_e_law_fir_f1744f_idx'),
        ),
        migrations.AddIndex(
            model_name='externaltemplate',
            index=models.Index(fields=['law_firm', 'is_active'], name='documents_e_law_fir_897043_idx'),
        ),
        migrations.AddIndex(
            model_name='externaltemplate',
            index=models.Index(fields=['structure_fingerprint'], name='documents_e_structu_9ffa3b_idx'),
        ),
        migrations.AddIndex(
            model_name='externaltemplate',
            index=models.Index(fields=['status'], name='documents_e_status_d32985_idx'),
        ),
        migrations.AddIndex(
            model_name='externaltemplatefieldmapping',
            index=models.Index(fields=['template', 'sort_order'], name='documents_e_templat_9d6340_idx'),
        ),
        migrations.AddIndex(
            model_name='fillrecord',
            index=models.Index(fields=['case', '-filled_at'], name='documents_f_case_id_926567_idx'),
        ),
        migrations.AddIndex(
            model_name='fillrecord',
            index=models.Index(fields=['template', '-filled_at'], name='documents_f_templat_8db7a8_idx'),
        ),
    ]
