# Generated by Django 5.2.8 on 2026-01-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="case_sub_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pleading_materials", "诉状材料"),
                    ("evidence_materials", "证据材料"),
                    ("power_of_attorney_materials", "授权委托材料"),
                    ("property_preservation_materials", "财产保全材料"),
                    ("service_address_materials", "送达地址材料"),
                    ("refund_account_materials", "收款退费账户材料"),
                    ("application_materials", "申请材料"),
                    ("other_materials", "其他材料"),
                ],
                help_text="仅在选择'案件文件模板'时有效,可选择诉状材料、证据材料、授权委托材料等",
                max_length=50,
                null=True,
                verbose_name="案件文件子类型",
            ),
        ),
    ]
