# Generated by Django 6.0.1 on 2026-01-21 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documenttemplate_case_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencelist',
            name='export_template',
            field=models.ForeignKey(blank=True, help_text='选择用于导出证据清单的 Word 模板', limit_choices_to={'case_sub_type': 'evidence_materials', 'is_active': True, 'template_type': 'case'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_lists', to='documents.documenttemplate', verbose_name='导出模板'),
        ),
    ]
