# Generated by Django 6.0.1 on 2026-02-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_externaltemplate_batchfilltask_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externaltemplate",
            name="source_type",
        ),
        migrations.AlterField(
            model_name="externaltemplate",
            name="category",
            field=models.CharField(max_length=50, verbose_name="模板类别"),
        ),
    ]
