# Generated by Django 6.0.1 on 2026-01-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_evidencelist_export_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyMatterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(blank=True, choices=[('civil', '民事'), ('administrative', '行政'), ('criminal', '刑事'), ('execution', '申请执行'), ('bankruptcy', '破产')], help_text='为空表示匹配任意案件类型', max_length=32, null=True, verbose_name='案件类型')),
                ('case_stage', models.CharField(blank=True, choices=[('first_trial', '一审'), ('second_trial', '二审'), ('enforcement', '执行'), ('labor_arbitration', '劳动仲裁'), ('administrative_review', '行政复议'), ('private_prosecution', '自诉'), ('investigation', '侦查'), ('prosecution_review', '审查起诉'), ('retrial_first', '重审一审'), ('retrial_second', '重审二审'), ('apply_retrial', '申请再审'), ('rehearing_first', '再审一审'), ('rehearing_second', '再审二审'), ('review', '提审'), ('death_penalty_review', '死刑复核程序'), ('petition', '申诉'), ('apply_protest', '申请抗诉'), ('petition_protest', '申诉抗诉')], help_text='为空表示匹配任意案件阶段', max_length=64, null=True, verbose_name='当前阶段')),
                ('legal_status', models.CharField(choices=[('plaintiff', '原告'), ('defendant', '被告'), ('third', '第三人'), ('applicant', '申请人'), ('respondent', '被申请人'), ('criminal_defendant', '被告人'), ('victim', '被害人'), ('appellant', '上诉人'), ('appellee', '被上诉人'), ('orig_plaintiff', '原审原告'), ('orig_defendant', '原审被告'), ('orig_third', '原审第三人')], max_length=32, verbose_name='我方诉讼地位')),
                ('items_text', models.TextField(blank=True, default='', help_text='每行一条代理事项', verbose_name='代理事项条目')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '代理事项规则',
                'verbose_name_plural': '代理事项规则',
                'indexes': [models.Index(fields=['is_active', 'priority'], name='documents_p_is_acti_fc1829_idx'), models.Index(fields=['case_type', 'case_stage', 'legal_status', 'is_active'], name='documents_p_case_ty_263cf5_idx')],
            },
        ),
    ]
