# Generated by Django 6.0.1 on 2026-02-23 12:30

from django.conf import settings
from django.db import migrations, models


def migrate_source_name(apps, schema_editor):
    """把 court.name / organization_name 合并到 source_name"""
    ExternalTemplate = apps.get_model("documents", "ExternalTemplate")
    for tpl in ExternalTemplate.objects.select_related("court").all():
        if tpl.court_id and tpl.court:
            tpl.source_name = tpl.court.name
        elif tpl.organization_name:
            tpl.source_name = tpl.organization_name
        else:
            tpl.source_name = ""
        tpl.save(update_fields=["source_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_remove_source_type_and_category_choices"),
        ("organization", "0002_password_plaintext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="externaltemplate",
            name="documents_e_law_fir_f1744f_idx",
        ),
        migrations.AddField(
            model_name="externaltemplate",
            name="source_name",
            field=models.CharField(
                blank=True, default="", help_text="法院名称或其他机构名称", max_length=255, verbose_name="来源机构"
            ),
        ),
        migrations.RunPython(migrate_source_name, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="externaltemplate",
            index=models.Index(fields=["law_firm", "source_name", "category"], name="documents_e_law_fir_6832d6_idx"),
        ),
        migrations.RemoveField(
            model_name="externaltemplate",
            name="court",
        ),
        migrations.RemoveField(
            model_name="externaltemplate",
            name="organization_name",
        ),
    ]
