# Generated by Django 6.0.1 on 2026-02-23 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_merge_court_org_to_source_name"),
        ("organization", "0002_password_plaintext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="externaltemplate",
            name="documents_e_law_fir_6832d6_idx",
        ),
        migrations.AddIndex(
            model_name="externaltemplate",
            index=models.Index(fields=["law_firm", "source_name"], name="documents_e_law_fir_31fde5_idx"),
        ),
        migrations.RemoveField(
            model_name="externaltemplate",
            name="category",
        ),
    ]
