# Generated by Django 6.0.1 on 2026-01-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_proxymatterrule'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='proxymatterrule',
            name='documents_p_case_ty_263cf5_idx',
        ),
        migrations.AddField(
            model_name='proxymatterrule',
            name='legal_statuses',
            field=models.JSONField(blank=True, default=list, help_text='可单选或多选;为空表示匹配任意诉讼地位', verbose_name='我方诉讼地位'),
        ),
        migrations.AddIndex(
            model_name='proxymatterrule',
            index=models.Index(fields=['case_type', 'case_stage', 'is_active'], name='documents_p_case_ty_a13a8f_idx'),
        ),
        migrations.RemoveField(
            model_name='proxymatterrule',
            name='legal_status',
        ),
    ]
