# Generated by Django 6.0.1 on 2026-01-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_proxymatterrule_documents_p_case_ty_263cf5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxymatterrule',
            name='legal_status_match_mode',
            field=models.CharField(choices=[('any', '任意匹配'), ('all', '全部包含'), ('exact', '完全一致')], default='any', max_length=16, verbose_name='诉讼地位匹配模式'),
        ),
    ]
