# Generated by Django 6.0.1 on 2026-02-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_remove_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externaltemplatefieldmapping",
            name="is_confirmed",
        ),
        migrations.RemoveField(
            model_name="externaltemplatefieldmapping",
            name="options",
        ),
        migrations.RemoveField(
            model_name="externaltemplatefieldmapping",
            name="placeholder_key",
        ),
        migrations.AlterField(
            model_name="externaltemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "已上传"),
                    ("analyzing", "分析中"),
                    ("analysis_failed", "分析失败"),
                    ("ready", "可填充"),
                ],
                default="uploaded",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
