# Generated by Django 6.0.2 on 2026-02-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_simplify_field_mapping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenttemplate",
            name="function_code",
        ),
    ]
