# Generated by Django 6.0.1 on 2026-01-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_proxymatterrule_legal_status_match_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='legal_status_match_mode',
            field=models.CharField(choices=[('any', '任意匹配'), ('all', '全部包含'), ('exact', '完全一致')], default='any', max_length=16, verbose_name='诉讼地位匹配模式'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='legal_statuses',
            field=models.JSONField(blank=True, default=list, help_text='可单选或多选;为空表示匹配任意诉讼地位', verbose_name='我方诉讼地位'),
        ),
    ]
