# Generated by Django 6.0.1 on 2026-01-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_add_folder_template_legal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='function_code',
            field=models.CharField(blank=True, db_index=True, help_text='用于程序识别特定功能的模板,如 preservation_application、delay_delivery_application', max_length=100, null=True, verbose_name='功能标识'),
        ),
    ]
