# Generated by Django 6.0.5 on 2026-05-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_evidenceitem_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartFillProxy',
            fields=[
            ],
            options={
                'verbose_name': '智能填充',
                'verbose_name_plural': '智能填充',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.documenttemplate',),
        ),
    ]
