# Generated by Django 6.0.7 on 2026-07-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_remove_evidenceitem_documents_e_directi_22020a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceholderOverview',
            fields=[
            ],
            options={
                'verbose_name': '替换词总览',
                'verbose_name_plural': '替换词总览',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.placeholder',),
        ),
    ]
