# Generated by Django 6.1.1 on 2026-10-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_placeholderoverview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltemplate',
            name='status',
            field=models.CharField(choices=[('uploaded', '已上传'), ('analyzing', '分析中'), ('analysis_failed', '分析失败'), ('ready', '可填充'), ('confirmed', '已确认')], default='uploaded', max_length=20, verbose_name='状态'),
        ),
    ]
