# Generated by Django 6.1.1 on 2026-10-03 08:34

from typing import Any

from django.db import migrations, models, transaction


def _normalize(apps: Any, app_label: str, model_name: str, fields: list[str]) -> None:
    """存量 NULL 归一为空字符串（双空态清理）。"""
    model = apps.get_model(app_label, model_name)
    for f in fields:
        model.objects.filter(**{f"{f}__isnull": True}).update(**{f: ""})


def normalize_null_to_empty(apps: Any, schema_editor: Any) -> None:
    with transaction.atomic():
        _normalize(apps, "documents", "DocumentTemplate", ["contract_sub_type", "case_sub_type", "archive_sub_type"])
        _normalize(apps, "documents", "ProxyMatterRule", ["case_type", "case_stage"])

class Migration(migrations.Migration):
    # contacts 表的外键是 DEFERRABLE INITIALLY DEFERRED：UPDATE 产生的延迟触发器
    # 事件会挡住同事务内的 ALTER TABLE（PG 限制）。数据步自包事务先提交。
    atomic = False
    dependencies = [
        ("documents", "0015_alter_externaltemplate_status"),
    ]

    operations = [
        migrations.RunPython(normalize_null_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="documenttemplate",
            name="archive_sub_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("case_cover", "案卷封面模板"),
                    ("closing_archive_register", "结案归档登记表模板"),
                    ("inner_catalog", "卷内目录模板"),
                    ("lawyer_work_log", "律师工作日志模板"),
                    ("service_quality_card", "律师办案服务质量监督卡模板"),
                    ("case_summary", "办案小结模板"),
                ],
                default="",
                help_text="仅在选择'归档文件模板'时有效,可选择案卷封面、结案归档登记表等",
                max_length=50,
                verbose_name="归档文件子类型",
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="case_sub_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pleading_materials", "诉状材料"),
                    ("evidence_materials", "证据材料"),
                    ("power_of_attorney_materials", "授权委托材料"),
                    ("property_preservation_materials", "财产保全材料"),
                    ("service_address_materials", "送达地址材料"),
                    ("refund_account_materials", "收款退费账户材料"),
                    ("application_materials", "申请材料"),
                    ("other_materials", "其他材料"),
                ],
                default="",
                help_text="仅在选择'案件文件模板'时有效,可选择诉状材料、证据材料、授权委托材料等",
                max_length=50,
                verbose_name="案件文件子类型",
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="contract_sub_type",
            field=models.CharField(
                blank=True,
                choices=[("contract", "合同模板"), ("supplementary_agreement", "补充协议模板")],
                default="",
                help_text="仅在选择'合同文件模板'时有效,必须选择合同模板或补充协议模板",
                max_length=30,
                verbose_name="合同子类型",
            ),
        ),
        migrations.AlterField(
            model_name="proxymatterrule",
            name="case_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_trial", "一审"),
                    ("second_trial", "二审"),
                    ("enforcement", "执行"),
                    ("labor_arbitration", "劳动仲裁"),
                    ("administrative_review", "行政复议"),
                    ("private_prosecution", "自诉"),
                    ("investigation", "侦查"),
                    ("prosecution_review", "审查起诉"),
                    ("retrial_first", "重审一审"),
                    ("retrial_second", "重审二审"),
                    ("apply_retrial", "申请再审"),
                    ("rehearing_first", "再审一审"),
                    ("rehearing_second", "再审二审"),
                    ("review", "提审"),
                    ("death_penalty_review", "死刑复核程序"),
                    ("petition", "申诉"),
                    ("apply_protest", "申请抗诉"),
                    ("petition_protest", "申诉抗诉"),
                ],
                default="",
                help_text="为空表示匹配任意案件阶段",
                max_length=64,
                verbose_name="当前阶段",
            ),
        ),
        migrations.AlterField(
            model_name="proxymatterrule",
            name="case_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("civil", "民事"),
                    ("administrative", "行政"),
                    ("criminal", "刑事"),
                    ("execution", "申请执行"),
                    ("bankruptcy", "破产"),
                ],
                default="",
                help_text="兼容旧数据字段，请使用“案件类型（多选）”",
                max_length=32,
                verbose_name="案件类型",
            ),
        ),
    ]
