# Generated by Django 6.1.1 on 2026-10-03 10:39

import apps.core.filesystem.upload_paths
import apps.documents.storage
import apps.evidence.models.evidence_storage
from typing import Any

from django.db import migrations, models, transaction


def _normalize(apps: Any, app_label: str, model_name: str, fields: list[str]) -> None:
    """存量 NULL 归一为空字符串（双空态清理）。"""
    model = apps.get_model(app_label, model_name)
    for f in fields:
        model.objects.filter(**{f"{f}__isnull": True}).update(**{f: ""})


def normalize_null_to_empty(apps: Any, schema_editor: Any) -> None:
    with transaction.atomic():
        _normalize(apps, "documents", "DocumentTemplate", ['file'])
        _normalize(apps, "documents", "EvidenceItem", ['file'])
        _normalize(apps, "documents", "EvidenceList", ['merged_pdf'])
        _normalize(apps, "documents", "GenerationTask", ['result_file'])


class Migration(migrations.Migration):
    # UPDATE 后同事务内 ALTER 可能撞上 DEFERRABLE 外键的 pending trigger 事件
    # （PG 限制，contacts 0002 先例），数据步自包事务先提交。
    atomic = False

    dependencies = [
        ('documents', '0016_alter_documenttemplate_archive_sub_type_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_null_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=models.FileField(blank=True, default='', storage=apps.documents.storage.DocumentTemplateStorage(), upload_to='', verbose_name='上传文件'),
        ),
        migrations.AlterField(
            model_name='evidenceitem',
            name='file',
            field=models.FileField(blank=True, default='', upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('evidence/files'), verbose_name='证据文件'),
        ),
        migrations.AlterField(
            model_name='evidencelist',
            name='merged_pdf',
            field=models.FileField(blank=True, default='', help_text='将所有证据文件合并为一个PDF,便于打印和提交', storage=apps.evidence.models.evidence_storage.EvidenceFileStorage(base_url='/media/evidence/', location='/Users/huangsong21/Downloads/Coding/AI/FachuanHybridSystem/backend/apiSystem/media/evidence'), upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('evidence/merged'), verbose_name='合并PDF'),
        ),
        migrations.AlterField(
            model_name='generationtask',
            name='result_file',
            field=models.FileField(blank=True, default='', upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('generated_documents'), verbose_name='生成文件'),
        ),
    ]
