# Generated by Django 6.1.1 on 2026-10-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_alter_documenttemplate_file_alter_evidenceitem_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documenttemplatefolderbinding',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='documenttemplatefolderbinding',
            constraint=models.UniqueConstraint(fields=('document_template', 'folder_template', 'folder_node_id'), name='uniq_template_folder_binding_node'),
        ),
    ]
