# Generated by Django 6.1.1 on 2026-10-04 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_alter_documenttemplatefolderbinding_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documenttemplatefolderbinding',
            name='documents_d_documen_3e722a_idx',
        ),
        migrations.RemoveIndex(
            model_name='evidencelist',
            name='documents_e_created_4a285c_idx',
        ),
        migrations.RemoveIndex(
            model_name='externaltemplate',
            name='documents_e_structu_9ffa3b_idx',
        ),
        migrations.RemoveIndex(
            model_name='generationtask',
            name='documents_g_litigat_ee5b82_idx',
        ),
        migrations.RemoveIndex(
            model_name='templateauditlog',
            name='documents_t_user_id_177e24_idx',
        ),
        migrations.AlterField(
            model_name='fillrecord',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.externaltemplate', verbose_name='关联模板'),
        ),
    ]
