# Generated by Django 6.1.1 on 2026-10-04 09:30

from typing import Any

from django.conf import settings
from django.db import migrations, models, transaction
from django.db.models import F


def clamp_evidencelist_merge_progress(apps: Any, schema_editor: Any) -> None:
    """钳制存量越界值，保证 AddConstraint 可执行。

    字段语义（见 MergeProgressReporter / EvidenceMergeUseCase）：
    - merge_progress：合并进度百分比，合法终态为完成时 100
    - merge_current：已处理文件数，完成时 == merge_total
    - merge_total：总文件数（items.count()），恒 >= 0

    钳制策略：
    - merge_progress 钳入 [0, 100]
    - merge_total < 0 置 0（先钳 total，后续 current 比较才有正确基准）
    - merge_current < 0 置 0；merge_current > merge_total 时下修 current = total
    """
    evidencelist = apps.get_model("documents", "EvidenceList")
    with transaction.atomic():
        evidencelist.objects.filter(merge_progress__gt=100).update(merge_progress=100)
        evidencelist.objects.filter(merge_progress__lt=0).update(merge_progress=0)
        evidencelist.objects.filter(merge_total__lt=0).update(merge_total=0)
        evidencelist.objects.filter(merge_current__lt=0).update(merge_current=0)
        evidencelist.objects.filter(merge_current__gt=F("merge_total")).update(merge_current=F("merge_total"))


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0039_remove_casetemplatebinding_cases_caset_templat_8dfc20_idx_and_more'),
        ('documents', '0019_remove_documenttemplatefolderbinding_documents_d_documen_3e722a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clamp_evidencelist_merge_progress, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='evidencelist',
            constraint=models.CheckConstraint(condition=models.Q(('merge_progress__gte', 0), ('merge_progress__lte', 100)), name='chk_evidencelist_merge_progress_range'),
        ),
        migrations.AddConstraint(
            model_name='evidencelist',
            constraint=models.CheckConstraint(condition=models.Q(('merge_current__gte', 0)), name='chk_evidencelist_merge_current_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='evidencelist',
            constraint=models.CheckConstraint(condition=models.Q(('merge_current__lte', models.F('merge_total'))), name='chk_evidencelist_merge_current_le_total'),
        ),
        migrations.AddConstraint(
            model_name='evidencelist',
            constraint=models.CheckConstraint(condition=models.Q(('merge_total__gte', 0)), name='chk_evidencelist_merge_total_nonneg'),
        ),
    ]
