# Generated by Django 6.0.5 on 2026-06-06 00:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_review', '0012_formatnormalize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatNormalizeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_method', models.CharField(choices=[('poi', 'POI服务'), ('python', 'Python'), ('auto', '自动选择')], default='auto', max_length=20, verbose_name='格式化方法')),
                ('version_number', models.CharField(blank=True, max_length=20, verbose_name='版本号')),
                ('changelog', models.TextField(blank=True, verbose_name='变更说明')),
                ('annotations', models.JSONField(blank=True, default=list, verbose_name='批注信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('processing_log', models.TextField(blank=True, verbose_name='处理日志')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='format_detail', to='contract_review.reviewtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '格式调整详情',
                'verbose_name_plural': '格式调整详情',
                'ordering': ['-created_at'],
            },
        ),
    ]
