"""
组织相关 Protocol 接口定义

包含:IOrganizationService, ILawyerService, ILawFirmService
"""

from typing import Protocol

from apps.core.dtos import AccountCredentialDTO, LawFirmDTO, LawyerDTO, TeamDTO


class IOrganizationService(Protocol):
    """组织服务接口，定义组织(律所、团队)相关的公共方法。"""

    def get_law_firm(self, law_firm_id: int) -> LawFirmDTO | None: ...

    def get_team(self, team_id: int) -> TeamDTO | None: ...

    def get_lawyers_in_organization(self, organization_id: int) -> list[LawyerDTO]: ...

    def get_all_credentials_internal(self) -> list[AccountCredentialDTO]: ...

    def get_credential_internal(self, credential_id: int) -> AccountCredentialDTO: ...

    def get_lawyer_by_id_internal(self, lawyer_id: int) -> LawyerDTO | None: ...

    def get_default_lawyer_id_internal(self) -> int | None: ...


class ILawyerService(Protocol):
    """律师服务接口，供其他模块使用。"""

    def get_lawyer(self, lawyer_id: int) -> LawyerDTO | None: ...

    def get_lawyers_by_ids(self, lawyer_ids: list[int]) -> list[LawyerDTO]: ...

    def get_team_members(self, team_id: int) -> list[LawyerDTO]: ...

    def validate_lawyer_active(self, lawyer_id: int) -> bool: ...

    def check_lawyer_permission(self, lawyer_id: int, permission: str) -> bool: ...

    def get_admin_lawyer_internal(self) -> LawyerDTO | None: ...

    def get_all_lawyer_names_internal(self) -> list[str]: ...


class ILawFirmService(Protocol):
    """律所服务接口，供其他模块使用。"""

    def get_lawfirm(self, lawfirm_id: int) -> LawFirmDTO | None: ...

    def get_lawfirms_by_ids(self, lawfirm_ids: list[int]) -> list[LawFirmDTO]: ...
