# Generated by Django 6.1.1 on 2026-09-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_recognition", "0002_documentrecognitiontask_managed_and_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrecognitiontask",
            name="degraded",
            field=models.BooleanField(blank=True, null=True, verbose_name="降级识别"),
        ),
        migrations.AddField(
            model_name="documentrecognitiontask",
            name="llm_backend",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="LLM 后端"),
        ),
        migrations.AddField(
            model_name="documentrecognitiontask",
            name="llm_latency_ms",
            field=models.IntegerField(blank=True, null=True, verbose_name="LLM 耗时(ms)"),
        ),
        migrations.AddField(
            model_name="documentrecognitiontask",
            name="llm_model",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="LLM 模型"),
        ),
    ]
