# Generated by Django 6.1.1 on 2026-09-28 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_remove_documentdeliveryschedule_automation__is_acti_ebd2c4_idx_and_more'),
        ('document_recognition', '0003_documentrecognitiontask_degraded_and_more'),
        ('reminders', '0008_add_calendar_feed_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecognitiontask',
            name='date_confirmation_status',
            field=models.CharField(choices=[('none', '无日期候选'), ('pending', '待确认'), ('partial', '部分确认'), ('complete', '全部处理完')], db_index=True, default='none', max_length=16, verbose_name='日期确认状态'),
        ),
        migrations.AddField(
            model_name='documentrecognitiontask',
            name='party_names',
            field=models.JSONField(blank=True, default=list, verbose_name='识别出的当事人'),
        ),
        migrations.AddField(
            model_name='documentrecognitiontask',
            name='source_court_sms',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_tasks', to='automation.courtsms', verbose_name='来源法院短信'),
        ),
        migrations.CreateModel(
            name='DocumentRecognitionDateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(verbose_name='候选日期时间')),
                ('reminder_type', models.CharField(choices=[('hearing', '开庭'), ('asset_preservation_expires', '财产保全到期日'), ('evidence_deadline', '举证到期日'), ('appeal_deadline', '上诉期到期日'), ('statute_limitations', '诉讼时效到期日'), ('payment_deadline', '缴费期限'), ('submission_deadline', '补正/材料提交期限'), ('other', '其他')], default='other', max_length=64, verbose_name='提醒类型')),
                ('context_text', models.CharField(blank=True, default='', max_length=255, verbose_name='原文上下文')),
                ('source', models.CharField(default='regex', max_length=16, verbose_name='提取来源')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='置信度')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('skipped', '已忽略')], db_index=True, default='pending', max_length=16, verbose_name='确认状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_date_candidates', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_candidates', to='reminders.reminder', verbose_name='已写入的提醒')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_candidates', to='document_recognition.documentrecognitiontask', verbose_name='识别任务')),
            ],
            options={
                'verbose_name': '日期候选',
                'verbose_name_plural': '日期候选',
                'ordering': ['due_at', 'id'],
                'indexes': [models.Index(fields=['task', 'status'], name='document_re_task_id_11fc1d_idx')],
            },
        ),
    ]
