# Generated by Django 6.1.1 on 2026-10-03 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_recognition', '0004_documentrecognitiontask_date_confirmation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecognitiontask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_recognition_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
