# Generated by Django 6.1.1 on 2026-10-03 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0020_delete_quickdownloadtool'),
        ('cases', '0034_alter_caseaccessgrant_grantee_and_more'),
        ('document_recognition', '0005_documentrecognitiontask_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentrecognitiontask',
            index=models.Index(fields=['status', '-created_at'], name='idx_docrec_status_created'),
        ),
        migrations.AddIndex(
            model_name='documentrecognitiontask',
            index=models.Index(fields=['case'], name='idx_docrec_case'),
        ),
        migrations.AddIndex(
            model_name='documentrecognitiontask',
            index=models.Index(fields=['case_log'], name='idx_docrec_case_log'),
        ),
    ]
