# Generated by Django 6.1.1 on 2026-10-03 08:34

from typing import Any

from django.db import migrations, models, transaction


def _normalize(apps: Any, app_label: str, model_name: str, fields: list[str]) -> None:
    """存量 NULL 归一为空字符串（双空态清理）。"""
    model = apps.get_model(app_label, model_name)
    for f in fields:
        model.objects.filter(**{f"{f}__isnull": True}).update(**{f: ""})


def normalize_null_to_empty(apps: Any, schema_editor: Any) -> None:
    with transaction.atomic():
        _normalize(
            apps,
            "document_recognition",
            "DocumentRecognitionTask",
            [
                "document_type",
                "case_number",
                "extraction_method",
                "llm_model",
                "llm_backend",
                "raw_text",
                "renamed_file_path",
                "binding_message",
                "binding_error_code",
                "error_message",
                "notification_error",
            ],
        )

class Migration(migrations.Migration):
    # contacts 表的外键是 DEFERRABLE INITIALLY DEFERRED：UPDATE 产生的延迟触发器
    # 事件会挡住同事务内的 ALTER TABLE（PG 限制）。数据步自包事务先提交。
    atomic = False
    dependencies = [
        ("document_recognition", "0006_documentrecognitiontask_idx_docrec_status_created_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_null_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="documentrecognitiontask",
            name="binding_error_code",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="绑定错误码"),
        ),
    ]
