# Generated by Django 6.1.1 on 2026-10-04 08:18

from typing import Any

from django.db import migrations, models, transaction

_NULLABLE_TEXT_FIELDS = [
    "document_type",
    "case_number",
    "extraction_method",
    "llm_model",
    "llm_backend",
    "raw_text",
    "renamed_file_path",
    "binding_message",
    "error_message",
    "notification_error",
]


def normalize_null_to_empty(apps: Any, schema_editor: Any) -> None:
    """存量 NULL 归一为空字符串（双空态清理），随后字段收紧为 NOT NULL。"""
    task = apps.get_model("document_recognition", "DocumentRecognitionTask")
    with transaction.atomic():
        for field in _NULLABLE_TEXT_FIELDS:
            task.objects.filter(**{f"{field}__isnull": True}).update(**{field: ""})


class Migration(migrations.Migration):

    dependencies = [
        ('document_recognition', '0007_alter_documentrecognitiontask_binding_error_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentrecognitiontask',
            name='idx_docrec_case',
        ),
        migrations.RemoveIndex(
            model_name='documentrecognitiontask',
            name='idx_docrec_case_log',
        ),
        migrations.RunPython(normalize_null_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='documentrecognitiontask',
            name='binding_message',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='绑定消息'),
        ),
        migrations.AlterField(
            model_name='documentrecognitiontask',
            name='case_number',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='案号'),
        ),
        migrations.AlterField(
            model_name='documentrecognitiontask',
            name='document_type',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='文书类型'),
        ),
        migrations.AlterField(
            model_name='documentrecognitiontask',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='documentrecognitiontask',
            name='extraction_method',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='提取方式'),
        ),
        migrations.AlterField(
            model_name='documentrecognitiontask',
            name='llm_backend',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='LLM 后端'),
        ),
        migrations.AlterField(
            model_name='documentrecognitiontask',
            name='llm_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='LLM 模型'),
        ),
        migrations.AlterField(
            model_name='documentrecognitiontask',
            name='notification_error',
            field=models.TextField(blank=True, default='', verbose_name='通知错误信息'),
        ),
        migrations.AlterField(
            model_name='documentrecognitiontask',
            name='raw_text',
            field=models.TextField(blank=True, default='', verbose_name='原始文本'),
        ),
        migrations.AlterField(
            model_name='documentrecognitiontask',
            name='renamed_file_path',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='重命名后路径'),
        ),
    ]
