# Generated by Django 6.1.1 on 2026-10-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_printing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='printpresetsnapshot',
            name='batch_print_printer_99eeb3_idx',
        ),
    ]
