# Generated by Django 5.2.8 on 2025-12-24 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContractFinanceLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=64, verbose_name="动作")),
                (
                    "level",
                    models.CharField(
                        choices=[("INFO", "信息"), ("WARN", "预警"), ("ERROR", "错误")],
                        default="INFO",
                        max_length=16,
                        verbose_name="级别",
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="数据")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "财务日志",
                "verbose_name_plural": "财务日志",
            },
        ),
        migrations.CreateModel(
            name="ContractParty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("PRINCIPAL", "委托人"), ("BENEFICIARY", "受益人"), ("OPPOSING", "对方当事人")],
                        default="PRINCIPAL",
                        max_length=16,
                        verbose_name="身份",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同当事人",
                "verbose_name_plural": "合同当事人",
            },
        ),
        migrations.CreateModel(
            name="ContractPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="收款金额")),
                ("received_at", models.DateField(default=django.utils.timezone.localdate, verbose_name="收款日期")),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[
                            ("UNINVOICED", "未开票"),
                            ("INVOICED_PARTIAL", "部分开票"),
                            ("INVOICED_FULL", "已开票"),
                        ],
                        default="UNINVOICED",
                        max_length=32,
                        verbose_name="开票状态",
                    ),
                ),
                (
                    "invoiced_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="已开票金额"),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "合同收款",
                "verbose_name_plural": "合同收款",
            },
        ),
        migrations.CreateModel(
            name="ContractReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hearing", "开庭"),
                            ("asset_preservation", "财产保全"),
                            ("evidence_deadline", "举证期限"),
                            ("statute_limitations", "时效"),
                            ("appeal_period", "上诉期"),
                            ("other", "其他"),
                        ],
                        max_length=32,
                        verbose_name="类型",
                    ),
                ),
                ("content", models.CharField(max_length=255, verbose_name="提醒事项")),
                ("due_date", models.DateField(verbose_name="到期日期")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "重要日期提醒",
                "verbose_name_plural": "重要日期提醒",
            },
        ),
        migrations.CreateModel(
            name="SupplementaryAgreement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=200, null=True, verbose_name="补充协议名称")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
            ],
            options={
                "verbose_name": "补充协议",
                "verbose_name_plural": "补充协议",
            },
        ),
        migrations.CreateModel(
            name="SupplementaryAgreementParty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("PRINCIPAL", "委托人"), ("BENEFICIARY", "受益人"), ("OPPOSING", "对方当事人")],
                        default="PRINCIPAL",
                        max_length=16,
                        verbose_name="身份",
                    ),
                ),
            ],
            options={
                "verbose_name": "补充协议当事人",
                "verbose_name_plural": "补充协议当事人",
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="合同名称")),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("civil", "民商事"),
                            ("criminal", "刑事"),
                            ("administrative", "行政"),
                            ("labor", "劳动仲裁"),
                            ("intl", "商事仲裁"),
                            ("special", "专项服务"),
                            ("advisor", "常法顾问"),
                        ],
                        max_length=32,
                        verbose_name="合同类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "在办"), ("closed", "已结案")],
                        default="active",
                        max_length=32,
                        verbose_name="合同状态",
                    ),
                ),
                ("specified_date", models.DateField(default=django.utils.timezone.localdate, verbose_name="指定日期")),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="开始日期")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="结束日期")),
                ("is_archived", models.BooleanField(default=False, verbose_name="是否已建档")),
                (
                    "fee_mode",
                    models.CharField(
                        choices=[
                            ("FIXED", "固定收费"),
                            ("SEMI_RISK", "半风险收费"),
                            ("FULL_RISK", "全风险收费"),
                            ("CUSTOM", "自定义"),
                        ],
                        default="FIXED",
                        max_length=16,
                        verbose_name="收费模式",
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="固定/前期律师费"
                    ),
                ),
                (
                    "risk_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="风险比例(%)"
                    ),
                ),
                ("custom_terms", models.TextField(blank=True, null=True, verbose_name="自定义收费条款")),
                ("representation_stages", models.JSONField(blank=True, default=list, verbose_name="代理阶段")),
            ],
            options={
                "verbose_name": "合同",
                "verbose_name_plural": "合同",
                "indexes": [
                    models.Index(fields=["case_type"], name="contracts_c_case_ty_14804d_idx"),
                    models.Index(fields=["status"], name="contracts_c_status_aa7a80_idx"),
                    models.Index(fields=["is_archived"], name="contracts_c_is_arch_1df554_idx"),
                    models.Index(fields=["specified_date"], name="contracts_c_specifi_efa563_idx"),
                    models.Index(fields=["-specified_date"], name="contracts_c_specifi_9bfb37_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_primary", models.BooleanField(default=False, verbose_name="是否主办律师")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同指派",
                "verbose_name_plural": "合同指派",
                "ordering": ["-is_primary", "order"],
            },
        ),
    ]
