# Generated by Django 5.2.8 on 2025-12-24 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contractassignment",
            name="lawyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="律师",
            ),
        ),
        migrations.AddField(
            model_name="contractfinancelog",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作者",
            ),
        ),
        migrations.AddField(
            model_name="contractfinancelog",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_logs",
                to="contracts.contract",
                verbose_name="合同",
            ),
        ),
        migrations.AddField(
            model_name="contractparty",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="client.client",
                verbose_name="当事人",
            ),
        ),
        migrations.AddField(
            model_name="contractparty",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_parties",
                to="contracts.contract",
                verbose_name="合同",
            ),
        ),
        migrations.AddField(
            model_name="contractpayment",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="contracts.contract",
                verbose_name="合同",
            ),
        ),
        migrations.AddField(
            model_name="contractreminder",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="contracts.contract",
                verbose_name="合同",
            ),
        ),
        migrations.AddField(
            model_name="supplementaryagreement",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplementary_agreements",
                to="contracts.contract",
                verbose_name="合同",
            ),
        ),
        migrations.AddField(
            model_name="supplementaryagreementparty",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplementary_agreements",
                to="client.client",
                verbose_name="当事人",
            ),
        ),
        migrations.AddField(
            model_name="supplementaryagreementparty",
            name="supplementary_agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parties",
                to="contracts.supplementaryagreement",
                verbose_name="补充协议",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractassignment",
            unique_together={("contract", "lawyer")},
        ),
        migrations.AddIndex(
            model_name="contractfinancelog",
            index=models.Index(fields=["contract", "created_at"], name="contracts_c_contrac_cfcd0d_idx"),
        ),
        migrations.AddIndex(
            model_name="contractfinancelog",
            index=models.Index(fields=["level"], name="contracts_c_level_76f463_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="contractparty",
            unique_together={("contract", "client")},
        ),
        migrations.AddIndex(
            model_name="contractpayment",
            index=models.Index(fields=["contract", "received_at"], name="contracts_c_contrac_6782a0_idx"),
        ),
        migrations.AddIndex(
            model_name="contractpayment",
            index=models.Index(fields=["invoice_status"], name="contracts_c_invoice_fc503d_idx"),
        ),
        migrations.AddIndex(
            model_name="supplementaryagreement",
            index=models.Index(fields=["contract", "-created_at"], name="contracts_s_contrac_ce9f0e_idx"),
        ),
        migrations.AddIndex(
            model_name="supplementaryagreement",
            index=models.Index(fields=["-created_at"], name="contracts_s_created_9b1c28_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="supplementaryagreementparty",
            unique_together={("supplementary_agreement", "client")},
        ),
    ]
