# Generated by Django 6.0.1 on 2026-02-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContractReminder",
        ),
    ]
