# Generated by Django 6.0.1 on 2026-02-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_delete_contractreminder"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractFolderBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "folder_path",
                    models.CharField(
                        help_text="绑定的本地或网络文件夹路径", max_length=1000, verbose_name="文件夹路径"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="绑定时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "合同文件夹绑定",
                "verbose_name_plural": "合同文件夹绑定",
            },
        ),
        migrations.CreateModel(
            name="ContractReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hearing", "开庭"),
                            ("asset_preservation", "财产保全"),
                            ("evidence_deadline", "举证期限"),
                            ("statute_limitations", "时效"),
                            ("appeal_period", "上诉期"),
                            ("other", "其他"),
                        ],
                        max_length=32,
                        verbose_name="类型",
                    ),
                ),
                ("content", models.CharField(max_length=255, verbose_name="提醒事项")),
                ("due_date", models.DateField(verbose_name="到期日期")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "重要日期提醒",
                "verbose_name_plural": "重要日期提醒",
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="filing_number",
            field=models.CharField(
                blank=True,
                help_text="格式: {年份}_{合同类型}_{HT}_{序号}",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="建档编号",
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["filing_number"], name="contracts_c_filing__706b73_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["case_type", "status"], name="contracts_c_case_ty_6edb9b_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["status", "-specified_date"], name="contracts_c_status_5d1a4a_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["is_archived", "-specified_date"], name="contracts_c_is_arch_4b81ea_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["case_type", "status", "-specified_date"], name="contracts_c_case_ty_d0bea9_idx"
            ),
        ),
        migrations.AddField(
            model_name="contractfolderbinding",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_binding",
                to="contracts.contract",
                verbose_name="合同",
            ),
        ),
        migrations.AddField(
            model_name="contractreminder",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_reminders",
                related_query_name="contract_reminder",
                to="contracts.contract",
                verbose_name="合同",
            ),
        ),
        migrations.AddIndex(
            model_name="contractfolderbinding",
            index=models.Index(fields=["contract"], name="contracts_c_contrac_892d47_idx"),
        ),
        migrations.AddIndex(
            model_name="contractfolderbinding",
            index=models.Index(fields=["-created_at"], name="contracts_c_created_beefcb_idx"),
        ),
    ]
