# Generated by Django 6.0.1 on 2026-02-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_delete_contractreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('category', models.CharField(choices=[('contract_original', '合同正本'), ('supplementary_agreement', '补充协议'), ('other', '其他')], default='other', max_length=32, verbose_name='材料分类')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_materials', to='contracts.contract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '定稿材料',
                'verbose_name_plural': '定稿材料',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['contract', '-uploaded_at'], name='contracts_f_contrac_4d4af4_idx')],
            },
        ),
    ]
