# Generated by Django 6.0.1 on 2026-02-23 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_finalizedmaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.CharField(max_length=500, verbose_name="文件路径")),
                ("original_filename", models.CharField(max_length=255, verbose_name="原始文件名")),
                ("remark", models.TextField(blank=True, default="", verbose_name="备注")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="上传时间")),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="contracts.contractpayment",
                        verbose_name="收款记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "发票",
                "verbose_name_plural": "发票",
                "ordering": ["-uploaded_at"],
                "indexes": [models.Index(fields=["payment", "-uploaded_at"], name="contracts_i_payment_3af6ef_idx")],
            },
        ),
    ]
