# Generated by Django 6.0.2 on 2026-02-24 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_initial"),
        ("contracts", "0006_invoice_amount_invoice_invoice_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPaymentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="回款金额")),
                ("image_path", models.CharField(blank=True, max_length=500, null=True, verbose_name="凭证图片路径")),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "cases",
                    models.ManyToManyField(
                        blank=True, related_name="client_payment_records", to="cases.case", verbose_name="关联案件"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_payment_records",
                        to="contracts.contract",
                        verbose_name="关联合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户回款",
                "verbose_name_plural": "客户回款",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["contract"], name="contracts_c_contrac_91115c_idx"),
                    models.Index(fields=["-created_at"], name="contracts_c_created_08e278_idx"),
                ],
            },
        ),
    ]
