# Generated by Django 6.0.2 on 2026-02-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_initial"),
        ("contracts", "0007_clientpaymentrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientpaymentrecord",
            name="cases",
        ),
        migrations.AddField(
            model_name="clientpaymentrecord",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_payment_records",
                to="cases.case",
                verbose_name="关联案件",
            ),
        ),
    ]
