# Generated by Django 6.1 on 2026-09-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0035_alter_historicalcontract_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='law_firm_oa_case_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='律所OA案件编号'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='law_firm_oa_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='律所OA链接'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='law_firm_oa_case_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='律所OA案件编号'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='law_firm_oa_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='律所OA链接'),
        ),
    ]
