# Generated by Django 6.1.1 on 2026-10-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0037_alter_contractfolderbinding_storage_account_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='archiveclassificationrule',
            name='contracts_a_archive_5caba9_idx',
        ),
        migrations.RemoveIndex(
            model_name='archiveplaceholderoverride',
            name='contracts_a_contrac_848705_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientpaymentrecord',
            name='contracts_c_contrac_91115c_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='contracts_c_case_ty_14804d_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='contracts_c_status_aa7a80_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='contracts_c_specifi_9bfb37_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='contracts_c_filing__706b73_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='contracts_c_is_file_b7e9f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='contractassignment',
            name='contracts_c_lawyer__3c302f_idx',
        ),
        migrations.RemoveIndex(
            model_name='contractfolderbinding',
            name='contracts_c_contrac_892d47_idx',
        ),
        migrations.RemoveIndex(
            model_name='contractparty',
            name='contracts_c_client__6764de_idx',
        ),
    ]
