# Generated by Django 6.1.1 on 2026-10-03 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0038_remove_archiveclassificationrule_contracts_a_archive_5caba9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractassignment',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_assignments', to=settings.AUTH_USER_MODEL, verbose_name='律师'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('law_firm_oa_case_number',), name='uniq_contract_law_firm_oa_case_number'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('risk_rate__gte', 0), ('risk_rate__lte', 100)), name='chk_contract_risk_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='contractpayment',
            constraint=models.UniqueConstraint(fields=('contract', 'received_at', 'amount'), name='uniq_contractpayment_contract_received_amount'),
        ),
        migrations.AddConstraint(
            model_name='contractpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='chk_contractpayment_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='contractpayment',
            constraint=models.CheckConstraint(condition=models.Q(('invoiced_amount__gte', 0)), name='chk_contractpayment_invoiced_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='contractpayment',
            constraint=models.CheckConstraint(condition=models.Q(('invoiced_amount__lte', models.F('amount'))), name='chk_contractpayment_invoiced_le_amount'),
        ),
        migrations.AddConstraint(
            model_name='finalizedmaterial',
            constraint=models.UniqueConstraint(fields=('contract', 'file_path'), name='uniq_finalizedmaterial_contract_file_path'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('payment', 'file_path'), name='uniq_invoice_payment_file_path'),
        ),
        migrations.AddConstraint(
            model_name='supplementaryagreement',
            constraint=models.UniqueConstraint(condition=models.Q(('name', ''), _negated=True), fields=('contract', 'name'), name='uniq_supplementaryagreement_contract_name'),
        ),
    ]
