# Generated by Django 6.1.1 on 2026-10-03 08:34

from typing import Any

from django.db import migrations, models, transaction


def _normalize(apps: Any, app_label: str, model_name: str, fields: list[str]) -> None:
    """存量 NULL 归一为空字符串（双空态清理）。"""
    model = apps.get_model(app_label, model_name)
    for f in fields:
        model.objects.filter(**{f"{f}__isnull": True}).update(**{f: ""})


def normalize_null_to_empty(apps: Any, schema_editor: Any) -> None:
    with transaction.atomic():
        _normalize(apps, "contracts", "Contract", ["custom_terms"])
        _normalize(apps, "contracts", "ContractPayment", ["note"])
        _normalize(apps, "contracts", "ClientPaymentRecord", ["image_path", "note"])

class Migration(migrations.Migration):
    # contacts 表的外键是 DEFERRABLE INITIALLY DEFERRED：UPDATE 产生的延迟触发器
    # 事件会挡住同事务内的 ALTER TABLE（PG 限制）。数据步自包事务先提交。
    atomic = False
    dependencies = [
        ("contracts", "0039_alter_contractassignment_lawyer_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_null_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="clientpaymentrecord",
            name="image_path",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="凭证图片路径"),
        ),
        migrations.AlterField(
            model_name="clientpaymentrecord",
            name="note",
            field=models.TextField(blank=True, default="", verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="custom_terms",
            field=models.TextField(blank=True, default="", verbose_name="自定义收费条款"),
        ),
        migrations.AlterField(
            model_name="contractpayment",
            name="note",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="historicalclientpaymentrecord",
            name="image_path",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="凭证图片路径"),
        ),
        migrations.AlterField(
            model_name="historicalclientpaymentrecord",
            name="note",
            field=models.TextField(blank=True, default="", verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="custom_terms",
            field=models.TextField(blank=True, default="", verbose_name="自定义收费条款"),
        ),
        migrations.AlterField(
            model_name="historicalcontractpayment",
            name="note",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="supplementaryagreement",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="补充协议名称"),
        ),
    ]
