# Generated by Django 6.1.1 on 2026-10-03 08:35

from typing import Any

from django.db import migrations, models


def _normalize(apps: Any, app_label: str, model_name: str, fields: list[str]) -> None:
    """存量 NULL 归一为空字符串（双空态清理）。"""
    model = apps.get_model(app_label, model_name)
    for f in fields:
        model.objects.filter(**{f"{f}__isnull": True}).update(**{f: ""})


def normalize_null_to_empty(apps: Any, schema_editor: Any) -> None:
    _normalize(apps, "contracts", "Contract", ["law_firm_oa_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0040_alter_clientpaymentrecord_image_path_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_null_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="contract",
            name="law_firm_oa_url",
            field=models.URLField(blank=True, default="", max_length=500, verbose_name="律所OA链接"),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="law_firm_oa_url",
            field=models.URLField(blank=True, default="", max_length=500, verbose_name="律所OA链接"),
        ),
    ]
