# Generated by Django 6.1.1 on 2026-10-03 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_client_address_and_more'),
        ('contracts', '0041_alter_contract_law_firm_oa_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archiveclassificationrule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='archiveplaceholderoverride',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contractassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contractparty',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplementaryagreementparty',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='archiveclassificationrule',
            constraint=models.UniqueConstraint(fields=('archive_category', 'filename_keyword'), name='uniq_archive_rule_category_keyword'),
        ),
        migrations.AddConstraint(
            model_name='archiveplaceholderoverride',
            constraint=models.UniqueConstraint(fields=('contract', 'template_subtype'), name='uniq_archive_override_contract_subtype'),
        ),
        migrations.AddConstraint(
            model_name='contractassignment',
            constraint=models.UniqueConstraint(fields=('contract', 'lawyer'), name='uniq_contract_assignment_contract_lawyer'),
        ),
        migrations.AddConstraint(
            model_name='contractparty',
            constraint=models.UniqueConstraint(fields=('contract', 'client'), name='uniq_contract_party_contract_client'),
        ),
        migrations.AddConstraint(
            model_name='supplementaryagreementparty',
            constraint=models.UniqueConstraint(fields=('supplementary_agreement', 'client'), name='uniq_supplementary_party_agreement_client'),
        ),
    ]
