# Generated by Django 6.1.1 on 2026-10-03 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_client_address_and_more'),
        ('contracts', '0042_alter_archiveclassificationrule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractparty',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='client.client', verbose_name='当事人'),
        ),
        migrations.AlterField(
            model_name='supplementaryagreementparty',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplementary_agreements', to='client.client', verbose_name='当事人'),
        ),
    ]
