# Generated by Django 6.1.1 on 2026-10-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0043_alter_contractparty_client_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contracttypefolderrootpreset',
            name='contracts_c_case_ty_88f56d_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplementaryagreementparty',
            name='contracts_s_client__e51df2_idx',
        ),
    ]
