# Generated by Django 6.1.1 on 2026-10-04 17:40

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0044_remove_contracttypefolderrootpreset_contracts_c_case_ty_88f56d_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contract',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='contract_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
