# Generated by Django 6.1.1 on 2026-10-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0045_contract_contract_name_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='law_firm_oa_guid',
            field=models.CharField(blank=True, help_text='律所 OA 案件 GUID（keyid），可通过「查询ID」按钮按案号自动获取', max_length=64, null=True, verbose_name='律所ID'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='law_firm_oa_guid',
            field=models.CharField(blank=True, help_text='律所 OA 案件 GUID（keyid），可通过「查询ID」按钮按案号自动获取', max_length=64, null=True, verbose_name='律所ID'),
        ),
    ]
