# Generated by Django 6.1.1 on 2026-10-04 08:18

from typing import Any

from django.conf import settings
from django.db import migrations, models, transaction
from django.db.models import F


def clamp_legal_research_tasks(apps: Any, schema_editor: Any) -> None:
    """钳制存量越界值，保证 AddConstraint 可执行。

    - progress 钳入 [0, 100]
    - min_similarity_score 钳入 [0, 1]
    - target_count > max_candidates 时下修 target_count = max_candidates
    """
    task = apps.get_model("legal_research", "LegalResearchTask")
    with transaction.atomic():
        task.objects.filter(progress__gt=100).update(progress=100)
        task.objects.filter(progress__lt=0).update(progress=0)
        task.objects.filter(min_similarity_score__gt=1).update(min_similarity_score=1)
        task.objects.filter(min_similarity_score__lt=0).update(min_similarity_score=0)
        task.objects.filter(target_count__gt=F("max_candidates")).update(target_count=F("max_candidates"))


class Migration(migrations.Migration):

    dependencies = [
        ('legal_research', '0014_alter_legalresearchresult_pdf_file'),
        ('organization', '0011_accountcredential_uniq_credential_lawyer_site_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedownloadresult',
            name='status',
            field=models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=16, verbose_name='状态'),
        ),
        migrations.RunPython(clamp_legal_research_tasks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='legalresearchtask',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='chk_lr_task_progress_range'),
        ),
        migrations.AddConstraint(
            model_name='legalresearchtask',
            constraint=models.CheckConstraint(condition=models.Q(('min_similarity_score__gte', 0), ('min_similarity_score__lte', 1)), name='chk_lr_task_min_similarity_range'),
        ),
        migrations.AddConstraint(
            model_name='legalresearchtask',
            constraint=models.CheckConstraint(condition=models.Q(('target_count__lte', models.F('max_candidates'))), name='chk_lr_task_target_le_max_candidates'),
        ),
    ]
