# Generated by Django 6.1.1 on 2026-09-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_splitting', '0005_alter_pdfsplitjob_split_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfsplitsegment',
            name='segment_type',
            field=models.CharField(choices=[('complaint', '起诉状'), ('evidence_list', '证据清单及明细'), ('preservation_materials', '财产保全资料'), ('party_identity', '双方当事人主体信息'), ('authorization_materials', '授权委托材料'), ('delivery_address_confirmation', '送达地址确认书'), ('refund_account_confirmation', '诉讼费用退费账户确认书'), ('loan_contract', '借款合同'), ('loan_disbursement_record', '放款凭证'), ('bank_statement', '银行流水'), ('interest_calculation', '利息计算表'), ('delivery_note', '送货单'), ('goods_receipt', '收货单'), ('invoice', '发票'), ('unrecognized', '未识别材料')], default='unrecognized', max_length=48, verbose_name='段类型'),
        ),
    ]
